### ISSUE TITLE
JMESPath::Errors::InvalidTypeError: function length() expects string, array or object

### ISSUE THREAD

**Issue by tyler-ball** [aws/aws-sdk-ruby#1004]
Our code which is raising this (intermittent) error:  https://github.com/test-kitchen/kitchen-ec2/blob/ed68c6ff21b90c91f1cae1493864867041a913e6/lib/kitchen/driver/ec2.rb#L380

Full stacktrace (there are some headers from Test Kitchen):

```
E, [2015-11-17T17:25:05.104604 #2399] ERROR -- Kitchen: ---Nested Exception---
E, [2015-11-17T17:25:05.104631 #2399] ERROR -- Kitchen: Class: JMESPath::Errors::InvalidTypeError
E, [2015-11-17T17:25:05.104663 #2399] ERROR -- Kitchen: Message: function length() expects string, array or object
E, [2015-11-17T17:25:05.104685 #2399] ERROR -- Kitchen: ------Backtrace-------
E, [2015-11-17T17:25:05.104704 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/jmespath-1.1.3/lib/jmespath/nodes/function.rb:178:in `call'
E, [2015-11-17T17:25:05.104723 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/jmespath-1.1.3/lib/jmespath/nodes/function.rb:21:in `visit'
E, [2015-11-17T17:25:05.104742 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/jmespath-1.1.3/lib/jmespath/nodes/comparator.rb:27:in `visit'
E, [2015-11-17T17:25:05.104761 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/jmespath-1.1.3/lib/jmespath/runtime.rb:52:in `search'
E, [2015-11-17T17:25:05.104780 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/jmespath-1.1.3/lib/jmespath.rb:33:in `search'
E, [2015-11-17T17:25:05.104807 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/poller.rb:69:in `matches_path?'
E, [2015-11-17T17:25:05.104839 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/poller.rb:65:in `acceptor_matches?'
E, [2015-11-17T17:25:05.104867 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/poller.rb:49:in `block in call'
E, [2015-11-17T17:25:05.104905 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/poller.rb:48:in `each'
E, [2015-11-17T17:25:05.104937 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/poller.rb:48:in `call'
E, [2015-11-17T17:25:05.104958 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:104:in `block in poll'
E, [2015-11-17T17:25:05.104986 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:101:in `loop'
E, [2015-11-17T17:25:05.105023 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:101:in `poll'
E, [2015-11-17T17:25:05.105054 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:91:in `block (2 levels) in wait'
E, [2015-11-17T17:25:05.105090 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:90:in `catch'
E, [2015-11-17T17:25:05.105138 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:90:in `block in wait'
E, [2015-11-17T17:25:05.105179 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:89:in `catch'
E, [2015-11-17T17:25:05.105216 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:89:in `wait'
E, [2015-11-17T17:25:05.105252 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/client_waiters.rb:110:in `wait_until'
E, [2015-11-17T17:25:05.105275 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-resources-2.2.0/lib/aws-sdk-resources/operations.rb:214:in `call'
E, [2015-11-17T17:25:05.105302 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-resources-2.2.0/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
E, [2015-11-17T17:25:05.105339 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-resources-2.2.0/lib/aws-sdk-resources/resource.rb:131:in `exists?'
E, [2015-11-17T17:25:05.105380 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/bundler/gems/kitchen-ec2-ed68c6ff21b9/lib/kitchen/driver/ec2.rb:380:in `block in wait_until_ready'
E, [2015-11-17T17:25:05.105405 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-resources-2.2.0/lib/aws-sdk-resources/resource.rb:108:in `call'
E, [2015-11-17T17:25:05.105436 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-resources-2.2.0/lib/aws-sdk-resources/resource.rb:108:in `block in wait_until'
E, [2015-11-17T17:25:05.105473 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:104:in `call'
E, [2015-11-17T17:25:05.105576 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:104:in `block in poll'
E, [2015-11-17T17:25:05.105612 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:101:in `loop'
E, [2015-11-17T17:25:05.105637 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:101:in `poll'
E, [2015-11-17T17:25:05.105674 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:91:in `block (2 levels) in wait'
E, [2015-11-17T17:25:05.105699 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:90:in `catch'
E, [2015-11-17T17:25:05.105719 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:90:in `block in wait'
E, [2015-11-17T17:25:05.105740 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:89:in `catch'
E, [2015-11-17T17:25:05.105776 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/waiters/waiter.rb:89:in `wait'
E, [2015-11-17T17:25:05.105814 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/aws-sdk-resources-2.2.0/lib/aws-sdk-resources/resource.rb:115:in `wait_until'
E, [2015-11-17T17:25:05.105862 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/bundler/gems/kitchen-ec2-ed68c6ff21b9/lib/kitchen/driver/ec2.rb:404:in `wait_with_destroy'
E, [2015-11-17T17:25:05.105889 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/bundler/gems/kitchen-ec2-ed68c6ff21b9/lib/kitchen/driver/ec2.rb:374:in `wait_until_ready'
E, [2015-11-17T17:25:05.105909 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/bundler/gems/kitchen-ec2-ed68c6ff21b9/lib/kitchen/driver/ec2.rb:217:in `block in create'
E, [2015-11-17T17:25:05.105941 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/retryable-2.0.3/lib/retryable.rb:67:in `retryable'
E, [2015-11-17T17:25:05.105978 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/bundler/gems/kitchen-ec2-ed68c6ff21b9/lib/kitchen/driver/ec2.rb:207:in `create'
E, [2015-11-17T17:25:05.106002 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `public_send'
E, [2015-11-17T17:25:05.106022 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `block in perform_action'
E, [2015-11-17T17:25:05.106040 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `call'
E, [2015-11-17T17:25:05.106059 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `synchronize_or_call'
E, [2015-11-17T17:25:05.106077 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
E, [2015-11-17T17:25:05.106096 #2399] ERROR -- Kitchen: /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
E, [2015-11-17T17:25:05.106118 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
E, [2015-11-17T17:25:05.106154 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `perform_action'
E, [2015-11-17T17:25:05.106177 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:352:in `create_action'
E, [2015-11-17T17:25:05.106196 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
E, [2015-11-17T17:25:05.106215 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
E, [2015-11-17T17:25:05.106234 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
E, [2015-11-17T17:25:05.106252 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:160:in `verify'
E, [2015-11-17T17:25:05.106271 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:189:in `block in test'
E, [2015-11-17T17:25:05.106292 #2399] ERROR -- Kitchen: /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
E, [2015-11-17T17:25:05.106326 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:185:in `test'
E, [2015-11-17T17:25:05.106351 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `public_send'
E, [2015-11-17T17:25:05.106376 #2399] ERROR -- Kitchen: /home/travis/build/chef/chef/kitchen-tests/vendor/bundle/ruby/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in ```

**Comment by tyler-ball** [comment]
We run integration tests in Travis and they fail more than 50% of the time with this error, checking `exists?` on a [Instance](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Instance.html) Resource

**Comment by trevorrowe** [comment]
I've been able to reproduce the issue locally. It appears to be related to a recent update to the `:instance_exists` waiter where a non-empty list check was added. The failure is caused when the response data is `nil` which happens when you receive a non-200 status code. This is common for invalid instance ids or instance ids which do not belong to your account. The jmespath gem is simply saying you can not run a length check on a `nil` value.

I'll try to submit a PR shortly to address this issue.

**Comment by tyler-ball** [comment]
Thanks @trevorrowe and @awood45 !
