### ISSUE TITLE
"NoMethodError: undefined method `each' for #<Seahorse::Client::Response...>" When counting IAM policies

### ISSUE THREAD

**Issue by danevron** [aws/aws-sdk-ruby#1033]
Hi,
I'm trying to count IAM policy versions.
```Ruby
policy = Aws::IAM::Policy.new("arn:aws:iam::#{@account}:policy/#{name}", client: @iam)
policy.versions.count
/Users/danevron/.rvm/gems/ruby-2.1.2/gems/aws-sdk-core-2.2.6/lib/seahorse/client/response.rb:87:in `method_missing': undefined method `each' for #<Seahorse::Client::Response:0x007fe57cbe10b8> (NoMethodError)
	from /Users/danevron/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.6/lib/aws-sdk-resources/operations.rb:127:in `all_batches'
	from /Users/danevron/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.6/lib/aws-sdk-resources/collection.rb:18:in `each'
	from /Users/danevron/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.6/lib/aws-sdk-resources/collection.rb:18:in `each'
	from ./sync.rb:43:in `count'
```

This work for me last week but I can't find the version in which it worked in.

Gem versions
```Bash
gem list aws-sdk

*** LOCAL GEMS ***

aws-sdk (2.2.6, 2.1.2, 2.0.39)
aws-sdk-core (2.2.6, 2.1.2, 2.0.39)
aws-sdk-resources (2.2.6, 2.1.2, 2.0.39)
aws-sdk-v1 (1.66.0, 1.64.0, 1.63.0)
```

Help will be appreciated.
Thanks.

**Comment by awood45** [comment]
Thanks for the report - I see a commit I'm suspicious of, give me a moment to confirm.

**Comment by awood45** [comment]
This will be fixed in the next release. I'll be looking in to the mistake made on our end that allowed this regression to happen. The regression was introduced in `2.2.4`, so version `2.2.3` will work for your code (as well as `2.2.7`, when it is released).
