### ISSUE TITLE
JSON Engine issue

### ISSUE THREAD

**Issue by kronos** [aws/aws-sdk-ruby#1049]
While switching to aws sdk v2 I had a couple of experiments in irb to understand how to use the new version of the gem and, thanks to the authors, everything was quite straightforward. After putting new gem into my project I encounter a strange issue:
```
Aws::S3::Resource.new(region: S3_REGION, credentials: s3_credentials)
NoMethodError: undefined method `each' for nil:NilClass
	from /apps/singing/source/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.9/lib/aws-sdk-core/waiters/provider.rb:9:in `initialize'
	from /apps/singing/source/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.9/lib/aws-sdk-core/client_waiters.rb:13:in `new'
	from /apps/singing/source/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.9/lib/aws-sdk-core/client_waiters.rb:13:in `set_waiters'
	from /apps/singing/source/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.9/lib/aws-sdk-core/client.rb:43:in `define'
	from /apps/singing/source/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.9/lib/aws-sdk-core.rb:378:in `block in <module:Aws>'
	from /apps/singing/source/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.9/lib/aws-sdk-core.rb:368:in `call'
	from /apps/singing/source/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.9/lib/aws-sdk-core.rb:368:in `block in add_service'
	from /apps/singing/source/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.9/lib/aws-sdk-core.rb:367:in `each'
	from /apps/singing/source/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.9/lib/aws-sdk-core.rb:367:in `add_service'
	from /apps/singing/source/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.2.9/lib/aws-sdk-core/s3.rb:1:in `<top (required)>'
	from /apps/singing/source/vendor/bundle/ruby/2.2.0/bundler/gems/core-a958f13d3f19/lib/wheely-core/common/s3_uploadable.rb:24:in `s3'
	from (irb):2
	from ./console:20:in `<main>'
```

After some digging, the problem became obvious: by default, the gem is trying to use Oj json parser (which was used in my project). But in my case I enable auto-symbolizing json ,
so here (aws-sdk-core/waiters/provider.rb):
```ruby
      def initialize(definitions)
        @waiters = {}
        definitions['waiters'].each do |waiter_name, definition|
```

```definitions['waiters']``` is equal to nil because it is being load from json
here (aws-sdk-core/client-waiter.rb):
```ruby
        def set_waiters(waiters)
          @waiters =
            case waiters
            when Waiters::Provider then waiters
            when Hash then Waiters::Provider.new(waiters)
            when String, Pathname then Waiters::Provider.new(Json.load_file(waiters))
```

I'm not sure whether it's aws client issue or mine, but maybe it would better to use hashes which is compartable with both types of hash keys or maybe avoid loading json?

**Comment by awood45** [comment]
This is an interesting catch! I'm going to reproduce on my end and see what the right behavior should be. Tentatively looking at this as a bug.

**Comment by awood45** [comment]
I am able to recreate this in the following way:
```ruby
Oj.default_options = {symbol_keys: true}
Aws::S3::Resource.new
```
Is this how you're setting your key symbolization in `Oj`, or are you doing this in a different way?

**Comment by trevorrowe** [comment]
I took a quick look at this. It appears to be very straightforward to provide localized options to Oj to avoid getting the system default of symbol keys. Here is what I put together to test. This prevents the example above from failing.

```diff
diff --git a/aws-sdk-core/lib/aws-sdk-core/json.rb b/aws-sdk-core/lib/aws-sdk-core/json.rb
index 3283139..77b4df7 100644
--- a/aws-sdk-core/lib/aws-sdk-core/json.rb
+++ b/aws-sdk-core/lib/aws-sdk-core/json.rb
@@ -23,7 +23,7 @@ module Aws
     class << self
 
       def load(json)
-        ENGINE.load(json)
+        ENGINE.load(json, *ENGINE_LOAD_OPTIONS)
       rescue ENGINE_ERROR => e
         raise ParseError.new(e)
       end
@@ -40,19 +40,19 @@ module Aws
 
       def oj_engine
         require 'oj'
-        [Oj, [{ mode: :compat }], Oj::ParseError]
+        [Oj, [{ mode: :compat }], [{ symbol_keys: false }], Oj::ParseError]
       rescue LoadError
         false
       end
 
       def json_engine
-        [JSON, [], JSON::ParserError]
+        [JSON, [], [], JSON::ParserError]
       end
 
     end
 
     # @api private
-    ENGINE, ENGINE_DUMP_OPTIONS, ENGINE_ERROR = oj_engine || json_engine
+    ENGINE, ENGINE_DUMP_OPTIONS, ENGINE_LOAD_OPTIONS, ENGINE_ERROR = oj_engine || json_engine
 
   end
 end
```

If someone wants to put together a pull-request with this and add a unit test that sets the global default and clear it afterwards to ensure we don't regress, I'll happily merge it.

**Comment by awood45** [comment]
I actually just wrote that and was about to send the PR. One moment...

**Comment by awood45** [comment]
We've merged in the fix, to go out with the next release.

**Comment by kronos** [comment]
Thanks!
