### ISSUE TITLE
APIGateway.Client#put_integration_response "Invalid request input"

### ISSUE THREAD

**Issue by abubics** [aws/aws-sdk-ruby#1080]
If I don't specify `selection_pattern: ''`, I get an error, and halt.
The docs say that parameter isn't required, though, and the error message is quite cryptic.

So, not sure if this is a bug, or misdocumented, I just kind-of reverse debugged it from the console UI.

**Comment by awood45** [comment]
Thanks for reporting this. I had a brief chat with their team, and it would be helpful if you could give me a full reproduction example, and a wire trace.

To enable wire tracing and get the wire logs:
```ruby
client = Aws::APIGateway::Client.new(http_wire_trace: true) # plus whatever other options you use
opts # what options are you using? feel free to strip out anything sensitive
client.put_integration_response(opts)
```
Feel free to strip out anything identifying from the wire logs, but it may help the service team if we can keep the request ID. If you'd be more comfortable emailing me the wire logs, let me know.

**Comment by abubics** [comment]
My current sample is a bit big and noisy. I'll cut it down and send logs through hopefully today or tomorrow :)

**Comment by abubics** [comment]
Sorry for the delay :) 

## `apigateway_test.rb`
```ruby
require 'aws-sdk'

class ApiGatewayDomain

  REGION='ap-northeast-1'

  def api_gateway
    @apigateway ||= Aws::APIGateway::Client.new(http_wire_trace: true, region: REGION)
  end

  def rest_api_name
    "apigateway_test"
  end

  def fetch_candidate_rest_apis
    api_gateway.get_rest_apis.items.select{ |it| it.name == rest_api_name }
  end

  def rest_api
    @resp_apis ||= fetch_candidate_rest_apis[0]
  end

  def gateway_exists?
    rest_api != nil
  end

  def create_gateway
    api_gateway.create_rest_api name: rest_api_name
  end

  def fetch_resources rest_api_id
    api_gateway.get_resources(rest_api_id: rest_api_id).items
  end

  def create_resources
    puts 'create_resources'
    base_id = fetch_resources(rest_api.id).select{ |it| it.path == '/' }[0].id
    api_resources.each do |k, v|
      puts "- creating: /#{k}"
      api_gateway.create_resource(
        rest_api_id: rest_api.id,
        parent_id: base_id,
        path_part: k
      )
    end
  end

  def account_id
    Aws::IAM::Client.new.get_user[:user][:arn].split(':')[4]
  end

  def lambda_arn_uri
    function_name = 'dev-dev-foobar-LambdaFun-1LZOR2U233EO5'
    lambda_arn = "arn:aws:lambda:#{REGION}:#{account_id}:function:#{function_name}"

    path_or_action = "path/2015-03-31/functions/#{lambda_arn}"
    service = 'lambda'
    service_api = 'invocations'
    "arn:aws:apigateway:#{REGION}:#{service}:#{path_or_action}/#{service_api}"
  end

  def create_methods
    puts 'create_methods'
    resources = fetch_resources rest_api.id
    api_resources.each do |k, v|
      resource = resources.select{ |it| it.path_part == k.to_s }[0]
      v.each do |method, config|
        puts "- #{method} /#{k}"
        api_gateway.put_method(
          rest_api_id: rest_api.id,
          resource_id: resource.id,
          http_method: method,
          authorization_type: 'NONE',
          api_key_required: true,
          request_parameters: config[:method_params]
        )
        api_gateway.put_method_response(
          rest_api_id: rest_api.id,
          resource_id: resource.id,
          http_method: method,
          status_code: '200'
        )
        api_gateway.put_integration(
          rest_api_id: rest_api.id,
          resource_id: resource.id,
          http_method: method,
          type: 'AWS',
          integration_http_method: 'POST',
          uri: lambda_arn_uri,
          request_templates: config[:templates]
        )
        api_gateway.put_integration_response(
          rest_api_id: rest_api.id,
          resource_id: resource.id,
          http_method: method,
          status_code: '200',
          #selection_pattern: '' # XXX Adding this fixes the "Invalid request input" error
        )
      end
    end
  end

  def api_resources
    def template action, more_params = nil
      more = ''
      if more_params
        more = ", #{more_params}"
      end
%Q(#set($inputRoot = $input.path('$'))
{ "action": "#{action}"#{more} })
    end

    {
      foo: { GET: {
        method_params: {},
        templates: { 'application/json': template('reviews') }
      } },
      bar: { GET: {
        method_params: { 'method.request.querystring.id': false },
        templates: { 'application/json':
          template('articles', %q("foobar_id": "$input.params('id')"))
        }
      } }
    }
  end

end

api_gateway = ApiGatewayDomain.new

api_gateway.create_gateway
api_gateway.create_resources
api_gateway.create_methods
```

## http_wire_trace:
```
opening connection to apigateway.ap-northeast-1.amazonaws.com:443...
opened
starting SSL for apigateway.ap-northeast-1.amazonaws.com:443...
SSL established
<- "POST /restapis HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.1.36 ruby/2.2.2 x86_64-darwin15\r\nAccept: application/json\r\nX-Amz-Date: 20160202T232542Z\r\nHost: apigateway.ap-northeast-1.amazonaws.com\r\nX-Amz-Content-Sha256: 53ce6911ff07bd861c21adff11600a010d947a17a43ee2f245aad979fe8eb6ef\r\nAuthorization: AWS4-HMAC-SHA256 Credential=____J34A____4EMY____/20160202/ap-northeast-1/apigateway/aws4_request, SignedHeaders=accept;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=619e8a281f9a383e8985073cbd81f51607826d16a04995246a9b9c90424c898c\r\nContent-Length: 26\r\n\r\n"
-> "HTTP/1.1 201 Created\r\n"
-> "x-amzn-RequestId: 47f5f7b4-ca04-11e5-8cdf-0bda7028ac65\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 70\r\n"
-> "Date: Tue, 02 Feb 2016 23:25:44 GMT\r\n"
-> "\r\n"
reading 70 bytes...
-> "{\"createdDate\":1454455544,\"id\":\"hf1lnexvv7\",\"name\":\"apigateway_test\"}\n"
read 70 bytes
Conn keep-alive
create_resources
opening connection to apigateway.ap-northeast-1.amazonaws.com:443...
opened
starting SSL for apigateway.ap-northeast-1.amazonaws.com:443...
SSL established
<- "GET /restapis HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.1.36 ruby/2.2.2 x86_64-darwin15\r\nAccept: application/json\r\nX-Amz-Date: 20160202T232544Z\r\nHost: apigateway.ap-northeast-1.amazonaws.com\r\nX-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\nAuthorization: AWS4-HMAC-SHA256 Credential=____J34A____4EMY____/20160202/ap-northeast-1/apigateway/aws4_request, SignedHeaders=accept;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=df99ffc91c9d7587820d18561215e63ff79b48e70f1db80bbdcfcfdd74e7a8a4\r\nContent-Length: 0\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "x-amzn-RequestId: 4883919d-ca04-11e5-927f-973e573b07ad\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 223\r\n"
-> "Date: Tue, 02 Feb 2016 23:25:44 GMT\r\n"
-> "\r\n"
reading 223 bytes...
-> "{\"item\":[{\"createdDate\":1449694605,\"id\":\"93vsgqazp1\",\"name\":\"api-test\"},{\"createdDate\":1453952132,\"id\":\"aqiqorose6\",\"name\":\"dev-__di____\"},{\"createdDate\":1454455544,\"id\":\"hf1lnexvv7\",\"name\":\"apigateway_test\"}]}\n"
read 223 bytes
Conn keep-alive
opening connection to apigateway.ap-northeast-1.amazonaws.com:443...
opened
starting SSL for apigateway.ap-northeast-1.amazonaws.com:443...
SSL established
<- "GET /restapis/hf1lnexvv7/resources HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.1.36 ruby/2.2.2 x86_64-darwin15\r\nAccept: application/json\r\nX-Amz-Date: 20160202T232544Z\r\nHost: apigateway.ap-northeast-1.amazonaws.com\r\nX-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\nAuthorization: AWS4-HMAC-SHA256 Credential=____J34A____4EMY____/20160202/ap-northeast-1/apigateway/aws4_request, SignedHeaders=accept;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=1e9fc05daa61430c46d770a466fd1a242e09948b6708c214dd0bc7f224853129\r\nContent-Length: 0\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "x-amzn-RequestId: 49082aee-ca04-11e5-927f-973e573b07ad\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 42\r\n"
-> "Date: Tue, 02 Feb 2016 23:25:45 GMT\r\n"
-> "\r\n"
reading 42 bytes...
-> "{\"item\":[{\"id\":\"6a64f4pjb3\",\"path\":\"/\"}]}\n"
read 42 bytes
Conn keep-alive
- creating: /foo
opening connection to apigateway.ap-northeast-1.amazonaws.com:443...
opened
starting SSL for apigateway.ap-northeast-1.amazonaws.com:443...
SSL established
<- "POST /restapis/hf1lnexvv7/resources/6a64f4pjb3 HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.1.36 ruby/2.2.2 x86_64-darwin15\r\nAccept: application/json\r\nX-Amz-Date: 20160202T232545Z\r\nHost: apigateway.ap-northeast-1.amazonaws.com\r\nX-Amz-Content-Sha256: 14892ee034de7d04c1b5b4380a0fc6530f2c316d9ae720822583cf907ba6beb8\r\nAuthorization: AWS4-HMAC-SHA256 Credential=____J34A____4EMY____/20160202/ap-northeast-1/apigateway/aws4_request, SignedHeaders=accept;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=e46e07bd9c96bf8d58d6bc6f756e5926a99a7c52ea1c698fbf9967a66b531aa1\r\nContent-Length: 18\r\n\r\n"
-> "HTTP/1.1 201 Created\r\n"
-> "x-amzn-RequestId: 499e77c1-ca04-11e5-ba1d-d5bc288ba023\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 71\r\n"
-> "Date: Tue, 02 Feb 2016 23:25:46 GMT\r\n"
-> "\r\n"
reading 71 bytes...
-> "{\"id\":\"6xy359\",\"parentId\":\"6a64f4pjb3\",\"path\":\"/foo\",\"pathPart\":\"foo\"}\n"
read 71 bytes
Conn keep-alive
- creating: /bar
opening connection to apigateway.ap-northeast-1.amazonaws.com:443...
opened
starting SSL for apigateway.ap-northeast-1.amazonaws.com:443...
SSL established
<- "POST /restapis/hf1lnexvv7/resources/6a64f4pjb3 HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.1.36 ruby/2.2.2 x86_64-darwin15\r\nAccept: application/json\r\nX-Amz-Date: 20160202T232546Z\r\nHost: apigateway.ap-northeast-1.amazonaws.com\r\nX-Amz-Content-Sha256: 9c53f33a539ba1f4214e3d8fe6b086b87715b95f37de3ab3f9e09f02cceff934\r\nAuthorization: AWS4-HMAC-SHA256 Credential=____J34A____4EMY____/20160202/ap-northeast-1/apigateway/aws4_request, SignedHeaders=accept;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=a11c66f340d27acb68a76a1981663b06dfcb5324849a736edbea7e67fb3ab2bd\r\nContent-Length: 18\r\n\r\n"
-> "HTTP/1.1 201 Created\r\n"
-> "x-amzn-RequestId: 4a7af4e7-ca04-11e5-8cdf-0bda7028ac65\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 71\r\n"
-> "Date: Tue, 02 Feb 2016 23:25:47 GMT\r\n"
-> "\r\n"
reading 71 bytes...
-> "{\"id\":\"0t241d\",\"parentId\":\"6a64f4pjb3\",\"path\":\"/bar\",\"pathPart\":\"bar\"}\n"
read 71 bytes
Conn keep-alive
create_methods
opening connection to apigateway.ap-northeast-1.amazonaws.com:443...
opened
starting SSL for apigateway.ap-northeast-1.amazonaws.com:443...
SSL established
<- "GET /restapis/hf1lnexvv7/resources HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.1.36 ruby/2.2.2 x86_64-darwin15\r\nAccept: application/json\r\nX-Amz-Date: 20160202T232548Z\r\nHost: apigateway.ap-northeast-1.amazonaws.com\r\nX-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\nAuthorization: AWS4-HMAC-SHA256 Credential=____J34A____4EMY____/20160202/ap-northeast-1/apigateway/aws4_request, SignedHeaders=accept;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=5333fa9c94c4d016d9f372a06435f6ec2ca84a762c770f2e88334b4bc2ec1279\r\nContent-Length: 0\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "x-amzn-RequestId: 4b13d988-ca04-11e5-8cdf-0bda7028ac65\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 184\r\n"
-> "Date: Tue, 02 Feb 2016 23:25:49 GMT\r\n"
-> "\r\n"
reading 184 bytes...
-> "{\"item\":[{\"id\":\"0t241d\",\"parentId\":\"6a64f4pjb3\",\"path\":\"/bar\",\"pathPart\":\"bar\"},{\"id\":\"6a64f4pjb3\",\"path\":\"/\"},{\"id\":\"6xy359\",\"parentId\":\"6a64f4pjb3\",\"path\":\"/foo\",\"pathPart\":\"foo\"}]}\n"
read 184 bytes
Conn keep-alive
- GET /foo
opening connection to apigateway.ap-northeast-1.amazonaws.com:443...
opened
starting SSL for apigateway.ap-northeast-1.amazonaws.com:443...
SSL established
<- "PUT /restapis/hf1lnexvv7/resources/6xy359/methods/GET HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.1.36 ruby/2.2.2 x86_64-darwin15\r\nAccept: application/json\r\nX-Amz-Date: 20160202T232549Z\r\nHost: apigateway.ap-northeast-1.amazonaws.com\r\nX-Amz-Content-Sha256: 259f60ae2a005e13e7a42d211aedd0b2f8a2b644d1bae9ca61b6ee9df43e947b\r\nAuthorization: AWS4-HMAC-SHA256 Credential=____J34A____4EMY____/20160202/ap-northeast-1/apigateway/aws4_request, SignedHeaders=accept;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=1e7a38ba785846fd5b3f564943aac1073be2af469d61efc3596e0cd8679455ef\r\nContent-Length: 73\r\n\r\n"
-> "HTTP/1.1 201 Created\r\n"
-> "x-amzn-RequestId: 4bc1ccc9-ca04-11e5-8cdf-0bda7028ac65\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 93\r\n"
-> "Date: Tue, 02 Feb 2016 23:25:50 GMT\r\n"
-> "\r\n"
reading 93 bytes...
-> "{\"apiKeyRequired\":true,\"authorizationType\":\"NONE\",\"httpMethod\":\"GET\",\"requestParameters\":{}}\n"
read 93 bytes
Conn keep-alive
opening connection to apigateway.ap-northeast-1.amazonaws.com:443...
opened
starting SSL for apigateway.ap-northeast-1.amazonaws.com:443...
SSL established
<- "PUT /restapis/hf1lnexvv7/resources/6xy359/methods/GET/responses/200 HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.1.36 ruby/2.2.2 x86_64-darwin15\r\nAccept: application/json\r\nX-Amz-Date: 20160202T232550Z\r\nHost: apigateway.ap-northeast-1.amazonaws.com\r\nX-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\nAuthorization: AWS4-HMAC-SHA256 Credential=____J34A____4EMY____/20160202/ap-northeast-1/apigateway/aws4_request, SignedHeaders=accept;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=57f1bf92c1b57f6f95627cb489efabd6d33b977ebc076d883a9378b95d02fab2\r\nContent-Length: 0\r\n\r\n"
-> "HTTP/1.1 201 Created\r\n"
-> "x-amzn-RequestId: 4c6c8b9f-ca04-11e5-927f-973e573b07ad\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 21\r\n"
-> "Date: Tue, 02 Feb 2016 23:25:51 GMT\r\n"
-> "\r\n"
reading 21 bytes...
-> "{\"statusCode\":\"200\"}\n"
read 21 bytes
Conn keep-alive
opening connection to apigateway.ap-northeast-1.amazonaws.com:443...
opened
starting SSL for apigateway.ap-northeast-1.amazonaws.com:443...
SSL established
<- "PUT /restapis/hf1lnexvv7/resources/6xy359/methods/GET/integration HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.1.36 ruby/2.2.2 x86_64-darwin15\r\nAccept: application/json\r\nX-Amz-Date: 20160202T232553Z\r\nHost: apigateway.ap-northeast-1.amazonaws.com\r\nX-Amz-Content-Sha256: 95ee98e4a264df42e22d580b0a7ea2111efbc4b77860bfe27c7496e8a8556b0b\r\nAuthorization: AWS4-HMAC-SHA256 Credential=____J34A____4EMY____/20160202/ap-northeast-1/apigateway/aws4_request, SignedHeaders=accept;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=25c82e7c688005901670ba3181900ff2fd254ef423749835fb9ff9762f698be7\r\nContent-Length: 335\r\n\r\n"
-> "HTTP/1.1 201 Created\r\n"
-> "x-amzn-RequestId: 4e175571-ca04-11e5-927f-973e573b07ad\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 386\r\n"
-> "Date: Tue, 02 Feb 2016 23:25:54 GMT\r\n"
-> "\r\n"
reading 386 bytes...
-> "{\"cacheKeyParameters\":[],\"cacheNamespace\":\"6xy359\",\"httpMethod\":\"POST\",\"requestTemplates\":{\"application/json\":\"#set($inputRoot = $input.path('$'))\\n{ \\\"action\\\": \\\"reviews\\\" }\"},\"type\":\"AWS\",\"uri\":\"arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:____1907____:function:dev-dev-foobar-LambdaFun-1LZOR2U233EO5/invocations\"}\n"
read 386 bytes
Conn keep-alive
opening connection to apigateway.ap-northeast-1.amazonaws.com:443...
opened
starting SSL for apigateway.ap-northeast-1.amazonaws.com:443...
SSL established
<- "PUT /restapis/hf1lnexvv7/resources/6xy359/methods/GET/integration/responses/200 HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.1.36 ruby/2.2.2 x86_64-darwin15\r\nAccept: application/json\r\nX-Amz-Date: 20160202T232554Z\r\nHost: apigateway.ap-northeast-1.amazonaws.com\r\nX-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\nAuthorization: AWS4-HMAC-SHA256 Credential=____J34A____4EMY____/20160202/ap-northeast-1/apigateway/aws4_request, SignedHeaders=accept;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=619bf052c7f35745930fa367543d3340eb5c214e8b9c3f2ad7e3179cad125151\r\nContent-Length: 0\r\n\r\n"
-> "HTTP/1.1 400 Bad Request\r\n"
-> "x-amzn-RequestId: 4ed415c3-ca04-11e5-927f-973e573b07ad\r\n"
-> "x-amzn-ErrorType: BadRequestException\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 36\r\n"
-> "Date: Tue, 02 Feb 2016 23:25:55 GMT\r\n"
-> "Connection: close\r\n"
-> "\r\n"
reading 36 bytes...
-> "{\"message\":\"Invalid request input\"}\n"
read 36 bytes
Conn close
/Users/abubics/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.36/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Invalid request input (Aws::APIGateway::Errors::BadRequestException)
	from /Users/abubics/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.36/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /Users/abubics/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.36/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /Users/abubics/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.36/lib/seahorse/client/request.rb:70:in `send_request'
	from /Users/abubics/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.36/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from apigateway_test.rb:92:in `block (2 levels) in create_methods'
	from apigateway_test.rb:67:in `each'
	from apigateway_test.rb:67:in `block in create_methods'
	from apigateway_test.rb:65:in `each'
	from apigateway_test.rb:65:in `create_methods'
	from apigateway_test.rb:133:in `<main>'
```

**Comment by awood45** [comment]
Thanks, I've reached out to the API Gateway team to see what is going on.

**Comment by awood45** [comment]
After talking to the service team, this is a known bug in the service right now. So, as you discovered, for now you should make sure to specify that parameter.

Closing as there's nothing we can do on our end. If I am made aware of a change to this I'll update the issue.

**Comment by abubics** [comment]
Cool, thanks. I wonder which will come first: updated docs, or bugfix ;D

**Comment by natemacinnes** [comment]
Still waiting on an update... to the code base or the docs 🕐

**Comment by awood45** [comment]
I'd consider raising an issue with AWS Support on this one, there isn't much that we can do ourselves on this. Will try to raise it up again with the API Gateway team.

**Comment by kd2eom** [comment]
Any progress on this? Still an issue...
