### ISSUE TITLE
Large collection errors

### ISSUE THREAD

**Issue by nikolai-b** [aws/aws-sdk-ruby#1112]
Not sure what is happening here but we've just started getting strange errors.

```
> source_bucket.class
=> AWS::S3::Bucket < Object

> source_bucket.objects.with_prefix('assets').collect &:key
=> NoMethodError: undefined method `has_key?' for #<String:0x005598fb358538>
from .rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/data.rb:117:in `method_missing'

> source_bucket.objects.with_prefix('assets').count
=> NoMethodError: undefined method `has_key?' for #<String:0x005598fa5b8db0>
from .rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/data.rb:117:in `method_missing'

> source_bucket.objects.with_prefix('assets').page(per_page: 5)
=> [
  [0] <AWS::S3::S3Object:BUCKET/assets/fonts/Apercu-Bold.otf>,
  [1] <AWS::S3::S3Object:BUCKETassets/fonts/Apercu-Light.otf>,
  [2] <AWS::S3::S3Object:BUCKET/assets/fonts/Apercu-Medium.otf>,
  [3] <AWS::S3::S3Object:fBUCKETassets/fonts/ConduitITCBold.otf>,
  [4] <AWS::S3::S3Object:BUCKET/assets/fonts/ConduitITCExtraLight.otf>
]

> source_bucket.objects.with_prefix(prefix).page(per_page: 191)
=> [ ..... ] # works

> source_bucket.objects.with_prefix(prefix).page(per_page: 192)
=> NoMethodError: undefined method `has_key?' for #<String:0x005598f931c8f0>
from .rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/data.rb:117:in `method_missing'
```

**Comment by nikolai-b** [comment]
https://github.com/aws/aws-sdk-ruby/issues/1112

Was due to strange chars in the file name, could do with an easier to decode error (or better file name handling...?)

**Comment by awood45** [comment]
Can you elaborate a bit more?

**Comment by nikolai-b** [comment]
The file name had a strange character.  In S3 the file name as url was 
`frui%14t.png` but when editing the file name the character didn't appear.  I'm not sure what the character actually was, I'll try find out how that happened but it did brake this gem.

**Comment by nikolai-b** [comment]
Turns out it was a `\u0014`, not sure how that crept in there...

**Comment by trevorrowe** [comment]
Can you provide a full stack trace for one of the failures? It is difficult to debug without more context.

**Comment by awood45** [comment]
Closing for lack of activity - feel free to reopen if you have more context to add.

**Comment by nikolai-b** [comment]
Sorry I missed the request for a full stack trace, it was very similar to https://github.com/clarete/s3sync/issues/30#issue-32116130 (except they are on an older gem version) but if you'd like me to reproduce it I can try.
