### ISSUE TITLE
NoMethodError: undefined method `each' for nil:NilClass when initializing Firehose

### ISSUE THREAD

**Issue by MaxGabriel** [aws/aws-sdk-ruby#1123]
Hi, we're initializing Firehose like so:

```ruby 
def self.firehose
  @firehose ||= Aws::Firehose::Client.new
end
```

But we're getting this exception:
```
NoMethodError: undefined method `each' for nil:NilClass
```

Here's the stacktrace:

```
[GEM_ROOT]/gems/aws-sdk-core-2.2.24/lib/seahorse/client/plugin_list.rb:18:in `initialize'
[GEM_ROOT]/gems/aws-sdk-core-2.2.24/lib/seahorse/client/base.rb:223:in `new'
[GEM_ROOT]/gems/aws-sdk-core-2.2.24/lib/seahorse/client/base.rb:223:in `inherited'
[GEM_ROOT]/gems/aws-sdk-core-2.2.24/lib/aws-sdk-core/client.rb:40:in `initialize'
[GEM_ROOT]/gems/aws-sdk-core-2.2.24/lib/aws-sdk-core/client.rb:40:in `new'
[GEM_ROOT]/gems/aws-sdk-core-2.2.24/lib/aws-sdk-core/client.rb:40:in `define'
[GEM_ROOT]/gems/aws-sdk-core-2.2.24/lib/aws-sdk-core.rb:382:in `block in <module:Aws>'
[GEM_ROOT]/gems/aws-sdk-core-2.2.24/lib/aws-sdk-core.rb:372:in `call'
[GEM_ROOT]/gems/aws-sdk-core-2.2.24/lib/aws-sdk-core.rb:372:in `block in add_service'
[GEM_ROOT]/gems/aws-sdk-core-2.2.24/lib/aws-sdk-core.rb:371:in `each'
[GEM_ROOT]/gems/aws-sdk-core-2.2.24/lib/aws-sdk-core.rb:371:in `add_service'
[GEM_ROOT]/gems/aws-sdk-core-2.2.24/lib/aws-sdk-core/firehose.rb:1:in `<top (required)>'
[PROJECT_ROOT]/app/models/analytics_logger.rb:13:in `firehose'
[PROJECT_ROOT]/app/models/analytics_logger.rb:41:in `block in log'
/usr/lib/ruby/2.1.0/timeout.rb:90:in `block in timeout'
/usr/lib/ruby/2.1.0/timeout.rb:100:in `call'
/usr/lib/ruby/2.1.0/timeout.rb:100:in `timeout'
[PROJECT_ROOT]/app/models/analytics_logger.rb:39:in `log'
[PROJECT_ROOT]/app/models/ad_stats.rb:495:in `notify_classifier'
[PROJECT_ROOT]/app/models/ad_stats.rb:112:in `add_impression'
[PROJECT_ROOT]/lib/ads/attribution.rb:173:in `add_impression'
[PROJECT_ROOT]/lib/resque_delayable.rb:84:in `perform'
```

<hr>

AWS SDK gem versions:
```
aws-sdk (2.2.24)
  aws-sdk-resources (= 2.2.24)
aws-sdk-core (2.2.24)
  jmespath (~> 1.0)
aws-sdk-resources (2.2.24)
  aws-sdk-core (= 2.2.24)
aws-sdk-v1 (1.66.0)
```

(aws-sdk-v1 is in the gemfile, but you can see from the stacktrace we're using v2)

Other version info:
Ruby: 2.1.8
Rails: 4.1.8
Resque: 1.24.1
Linux: Ubuntu 14.04.4 LTS

ccing my coworkers: @kcrayon @sadiqj @m5

**Comment by awood45** [comment]
I'm unable to recreate this. Can you tell me a bit more about how you're calling this and setting up your environment?

**Comment by awood45** [comment]
Closing due to no activity in a month. If you have additional information, feel free to reopen and I'll be happy to help.

**Comment by hanibash** [comment]
@MaxGabriel Did you end up resolving this issue? We are seeing something similar:

```
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/seahorse/client/plugin_list.rb" line 18 in initialize
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/seahorse/client/base.rb" line 223 in new
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/seahorse/client/base.rb" line 223 in inherited
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core/client.rb" line 40 in initialize
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core/client.rb" line 40 in new
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core/client.rb" line 40 in define
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core.rb" line 440 in block in <module:Aws>
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core.rb" line 430 in call
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core.rb" line 430 in block in add_service
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core.rb" line 429 in each
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core.rb" line 429 in add_service
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core/codecommit.rb" line 1 in <top (required)>
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core.rb" line 389 in const_get
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core.rb" line 389 in block in sub_modules
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core.rb" line 388 in each
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core.rb" line 388 in inject
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core.rb" line 388 in sub_modules
File "/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.3.0/lib/aws-sdk-core.rb" line 376 in eager_autoload!
File "/app/app/classes/firehose.rb", line 131 in firehose
```
