### ISSUE TITLE
sometimes undefined method `new' for nil:NilClass when get ses response 

### ISSUE THREAD

**Issue by mwangm** [aws/aws-sdk-ruby#1135]
It looks like the XMLParser didn't  get a engine object to parse xml..

/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/aws-sdk-core/xml/parser.rb:44:in `parse'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/aws-sdk-core/query/handler.rb:53:in `parse_xml'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/aws-sdk-core/query/handler.rb:29:in `block in call'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/response.rb:43:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/response.rb:43:in `block in on'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/http/response.rb:139:in `block in on_success'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/http/response.rb:166:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/http/response.rb:166:in `block in listener'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/http/response.rb:130:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/http/response.rb:130:in `on_done'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/http/response.rb:137:in `on_success'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/response.rb:42:in `on'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/response.rb:51:in `on_success'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/aws-sdk-core/query/handler.rb:27:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/request.rb:70:in `send_request'
/usr/local/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.11/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/jobs/lib/utils/ses.rb:10:in `send'

**Comment by bmurtagh** [comment]
Can you provide more details or sample code on how you ended up running into this error?

**Comment by awood45** [comment]
It would probably be an extra help if we can get a wire trace on the client.

```ruby
client = Aws::SES::Client.new(http_wire_trace: true)
```

I definitely would be interested in tracking this down. Is this a transient error, or is it consistently reproducible?

**Comment by mwangm** [comment]
@bmurtagh  the code is very simple, It is just `@ses_client.send_email payload`

**Comment by awood45** [comment]
I'm not able to recreate this, trying to test the `#send_email` method isn't revealing any problems on my end. If you can provide a wire trace that includes the response you're getting that is having parse issues, that would be a huge help.

**Comment by awood45** [comment]
Have you been able to recreate the issue with a wire trace?

**Comment by awood45** [comment]
Closing for inactivity - feel free to reopen or to open a new issue if you are able to provide more information. Or, if you found another root cause, let us know!

**Comment by trevorrowe** [comment]
This issue has been reported against by another user and we have a minimal test case to reproduce the issue. I'll update this issue with more information as we work to resolve it. In short there is a concurrency issue with how the XML parser is choosing an issue that can create this issue in a multithreaded environment.

**Comment by trevorrowe** [comment]
Here is the snippet I am using to reproduce the issue:

```ruby
require 'aws-sdk-core'
require 'thread'

threads = 10.times.map do
  Thread.new do
    sqs = Aws::SQS::Client.new
    sqs.send_message(queue_url:"https://sqs.us-east-1.amazonaws.com/469596866844/trowe", message_body:'string')
  end
end
threads.map(&:join)
```
