### ISSUE TITLE
Getting NoMethodError: undefined method `resolve' for Aws::EndpointProvider:Class

### ISSUE THREAD

**Issue by ravi05cse** [aws/aws-sdk-ruby#1183]
```ruby
module MyAwsDynamoDbModule
  def self.myclient
    Aws.config.update(
        {
            region: <region>,
            credentials: Aws::Credentials.new(<access_key_id>, <secret_access_key>)
        }
    )
    Aws::DynamoDB::Client.new
  end
end

MyAwsDynamoDbModule.myclient
```
**When calling above getting following error:**

2016-05-11 06:30:58 UTC+5:30 rake aborted!
2016-05-11 06:30:58 UTC+5:30 NoMethodError: undefined method `resolve' for Aws::EndpointProvider:Class
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/aws-sdk-core/plugins/regional_endpoint.rb:24:in `block in <class:RegionalEndpoint>'
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/seahorse/client/configuration.rb:64:in `call'
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/seahorse/client/configuration.rb:64:in `call'
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/seahorse/client/configuration.rb:199:in `block in resolve_defaults'
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/seahorse/client/configuration.rb:57:in `each'
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/seahorse/client/configuration.rb:57:in `each'
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/seahorse/client/configuration.rb:198:in `resolve_defaults'
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/seahorse/client/configuration.rb:194:in `value_at'
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/seahorse/client/configuration.rb:183:in `block in resolve'
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/seahorse/client/configuration.rb:183:in `resolve'
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/seahorse/client/configuration.rb:171:in `apply_defaults'
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/seahorse/client/configuration.rb:144:in `build!'
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/seahorse/client/base.rb:68:in `build_config'
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/seahorse/client/base.rb:19:in `initialize'
2016-05-11 06:30:58 UTC+5:30 /home/deploy/.bundler/backgroundprocessingapp/ruby/2.2.0/gems/aws-sdk-core-2.2.12/lib/seahorse/client/base.rb:105:in `new'

**Comment by ravi05cse** [comment]
I am using following gems
gem 'aws-sdk', '1.66.0'
gem 'aws-sdk-resources', '2.2.12'

**Comment by awood45** [comment]
I can't really follow your code above. Are you actually setting `:region` to ` `?

If so, I can imagine where errors could pop up. What are you trying to do?

**Comment by ravi05cse** [comment]
Yes i am setting :region. Also i want to share you that I am using thread pool here

**Comment by awood45** [comment]
Quick hunch then - what happens if you add: 
```ruby
Aws.eager_autoload!
```

It's also very likely that an upgrade to the latest `aws-sdk-resources` version fixes this.

**Comment by trevorrowe** [comment]
@ravi05cse The thread-safety issue should be resolve in current versions of the SDK now. You should be able to update from 2.2.12 to the latest version to resolve this issue.
