### ISSUE TITLE
[Aws::SQS] Keep polling on network errors

### ISSUE THREAD

**Issue by rejeep** [aws/aws-sdk-ruby#1196]
Hi,

I have a job that polls an SQS-queue and starts a job when a new message is received. Simplified it looks like this:

```ruby
poller = Aws::SQS::QueuePoller.new(url, client: client)
poller.poll do |message|
  # ...
end
```

Every now and then that process dies with this stacktrace.

```
/home/burt/apps/my-app/current/lib/ruby/lib/ruby/2.2.0/net/http.rb:879:in `initialize': getaddrinfo: Name or service not known (Seahorse::Client::NetworkingError)
from /home/burt/apps/my-app/current/lib/ruby/lib/ruby/2.2.0/net/http.rb:879:in `open'
from /home/burt/apps/my-app/current/lib/ruby/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
from /home/burt/apps/my-app/current/lib/ruby/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
from /home/burt/apps/my-app/current/lib/ruby/lib/ruby/2.2.0/timeout.rb:99:in `call'
from /home/burt/apps/my-app/current/lib/ruby/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
from /home/burt/apps/my-app/current/lib/ruby/lib/ruby/2.2.0/net/http.rb:878:in `connect'
from /home/burt/apps/my-app/current/lib/ruby/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
from /home/burt/apps/my-app/current/lib/ruby/lib/ruby/2.2.0/net/http.rb:858:in `start'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/seahorse/client/net_http/connection_pool.rb:292:in `start_session'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/seahorse/client/net_http/connection_pool.rb:104:in `session_for'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/seahorse/client/net_http/handler.rb:108:in `session'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/seahorse/client/net_http/handler.rb:60:in `transmit'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/seahorse/client/net_http/handler.rb:34:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/seahorse/client/plugins/content_length.rb:12:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/request_signer.rb:85:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/retry_errors.rb:87:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/retry_errors.rb:118:in `retry_request'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/retry_errors.rb:101:in `retry_if_possible'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/retry_errors.rb:89:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/retry_errors.rb:118:in `retry_request'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/retry_errors.rb:101:in `retry_if_possible'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/retry_errors.rb:89:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/retry_errors.rb:118:in `retry_request'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/retry_errors.rb:101:in `retry_if_possible'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/retry_errors.rb:89:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/sqs_queue_urls.rb:13:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/query/handler.rb:27:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/logging.rb:39:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/seahorse/client/plugins/response_target.rb:21:in `call'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/seahorse/client/request.rb:70:in `send_request'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-core-2.2.8/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-resources-2.2.8/lib/aws-sdk-resources/services/sqs/queue_poller.rb:390:in `send_request'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-resources-2.2.8/lib/aws-sdk-resources/services/sqs/queue_poller.rb:383:in `get_messages'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-resources-2.2.8/lib/aws-sdk-resources/services/sqs/queue_poller.rb:332:in `block (2 levels) in poll'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-resources-2.2.8/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `loop'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-resources-2.2.8/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `block in poll'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-resources-2.2.8/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `catch'
from /media/ephemeral/apps/my-app/current/lib/vendor/ruby/2.2.0/gems/aws-sdk-resources-2.2.8/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `poll'
from ./bin/sqs_poll:66:in `<main>'
```

I don't know why this happens, but when it does I don't want the whole process to die. Is there any way of catch and ignore these errors?

**Comment by awood45** [comment]
Immediate workaround would be to wrap the method calling the poller with something that catches this error and creates a new poller.

We already do retry networking errors, so if you're seeing that in your stack trace, multiple retries at the client level have already failed. Other than infinitely retrying, I'm not sure what else the code side can do.

**Comment by awood45** [comment]
One other option is that you can increase the `:retry_limit` in the client, to make this kind of error less likely and to increase the exponential backoff time. For example:

```ruby
client = Aws::SQS::Client.new(retry_limit: 5)
poller = Aws::SQS::QueuePoller.new(url, client: client)
poller.poll do |message|
  # ...
end
```

Closing as that's the most reasonable workaround I can think of (again, we can't infinitely retry networking errors, risks an infinite loop). Feel free to add any further questions you have, or reopen/create a new issue if there are other concerns.

**Comment by rejeep** [comment]
For anyone else with this issue, I solved it like this:

```ruby
retries = 0
begin
  poller = Aws::SQS::QueuePoller.new(url, client: client)
  poller.poll do |message|
    # ...
  end
rescue Seahorse::Client::NetworkingError => e
  if (retries += 1) < 10
    logger.warn('Unexpected networking error occured')
    logger.warn(e.message)
    sleep 10
    retry
  end
end
```

**Comment by awood45** [comment]
I should have mentioned it sooner, but you'd get the same retry behavior, except with exponential backoff and for all retryable cases, simply by adjusting `:retry_limit`. Nothing stopping this, for example:

```ruby
client = Aws::SQS::Client.new(retry_limit: 25)
poller = Aws::SQS::QueuePoller.new(url, client: client)
poller.poll do |message|
  # ...
end
```

The retry periods could get really long, but it would terminate and would retry with similar aggressiveness - per client call.

**Comment by rejeep** [comment]
Would that help though? Are you saying that the exception occurs when there are no more retries? My impression was that the exception occurred at any point and aborted the retry chain.

**Comment by awood45** [comment]
No, it is already retried. See [the RetryErrors plugin.](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/plugins/retry_errors.rb#L63)
