### ISSUE TITLE
Updating cloudformation stack with tags options raises validation error

### ISSUE THREAD

**Issue by robert2d** [aws/aws-sdk-ruby#1206]
Trying to update a cloud formation stack with the tags argument supplied raises a validation error.
Documentation mentions you can pass tags to the update method: http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudFormation/Client.html#update_stack-instance_method

Example:
```
options  =  {tags: [{key: "department", value: "marketing"}], parameters: ..., etc..}

cf_client = Aws::CloudFormation::Client.new({region: 'us-west-1'})
cf = Aws::CloudFormation::Resource.new(:client => cf_client)
cf_stack.update(options)
```

Error raised:
```
/Users/dave/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.2.18/lib/aws-sdk-core/param_validator.rb:26:in `validate!': unexpected value at params[:tags] (ArgumentError)
	from /Users/dave/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.2.18/lib/aws-sdk-core/param_validator.rb:11:in `validate!'
	from /Users/dave/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.2.18/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'
	from /Users/dave/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.2.18/lib/aws-sdk-core/plugins/logging.rb:39:in `call'
	from /Users/dave/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.2.18/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /Users/dave/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.2.18/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /Users/dave/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.2.18/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /Users/dave/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.2.18/lib/seahorse/client/request.rb:70:in `send_request'
	from /Users/dave/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-2.2.18/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
```

**Comment by robert2d** [comment]
bundle update derp

**Comment by awood45** [comment]
Glad you got things working quickly!
