### ISSUE TITLE
Specifying an invalid KMS key on `create_volume` silently fails to create a volume

### ISSUE THREAD

**Issue by ljfranklin** [aws/aws-sdk-ruby#1222]
Hi all,

We're running into an issue with KMS keys on version '2.3.14' of the SDK. Attempting to create a Volume with a specified `kms_key_id` will silently fail if the key does not exist. The `create_volume` call succeeds and returns a volume id, but subsequent calls to `describe_volumes` will throw `InvalidVolumeNotFound` and no Volume appears in the console. This is especially painful as it is easy to confuse the KMS Key Alias (which fails) with the actual ID (which works).

Here's a snippet of code to reproduce the issue:

```
require 'aws-sdk'

ec2 = Aws::EC2::Client.new

resp = ec2.create_volume({
  size: 10000,
  availability_zone: "us-east-1a", # required
  volume_type: "gp2",
  encrypted: true,
  kms_key_id: "my-fake-kms-key-asdf",
})

volume_id = resp.volume_id
puts "Volume ID: #{resp.volume_id}"
puts "Volume State: #{resp.state}"

10.times do
  resp = ec2.describe_volumes({
    volume_ids: [volume_id],
  })
  puts "Volume Description: #{resp.volumes}"
  sleep(5)
end
```

This produces the following output:

```
$ be ruby create_volume.rb
Volume ID: vol-a0171105
Volume State: creating
Volume Description: [#<struct Aws::EC2::Types::Volume volume_id="vol-a0171105", size=10000, snapshot_id="", availability_zone="us-east-1a", state="creating", create_time=2016-06-17 22:19:53 UTC, attachments=[], tags=[], volume_type="gp2", iops=10000, encrypted=true, kms_key_id="my-fake-bosh-key-asdf">]
/Users/pivotal/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The volume 'vol-a0171105' does not exist. (Aws::EC2::Errors::InvalidVolumeNotFound)
	from /Users/pivotal/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.3.14/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /Users/pivotal/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.3.14/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
	from /Users/pivotal/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /Users/pivotal/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/request.rb:70:in `send_request'
	from /Users/pivotal/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from create_volume.rb:19:in `block in <main>'
	from create_volume.rb:18:in `times'
	from create_volume.rb:18:in `<main>'
```

If you specify a valid KMS key ID, everything works as expected.

Thanks!

- Lyle && Forrest, Pivotal Cloud Foundry

**Comment by trevorrowe** [comment]
I can certainly use your script and reproduce the issue. Amazon EC2 is returning a successful 200 response with a volume id. Here is the output of a HTTP wire trace:

```
-> "HTTP/1.1 200 OK\r\n"
-> "Content-Type: text/xml;charset=UTF-8\r\n"
-> "Transfer-Encoding: chunked\r\n"
-> "Vary: Accept-Encoding\r\n"
-> "Date: Fri, 17 Jun 2016 23:08:51 GMT\r\n"
-> "Server: AmazonEC2\r\n"
-> "\r\n"
-> "223\r\n"
reading 547 bytes...
-> "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<CreateVolumeResponse xmlns=\"http://ec2.amazonaws.com/doc/2015-10-01/\">\n    <requestId>f066a84f-c33d-46bf-b63e-d8bccb6522e8</requestId>\n    <volumeId>vol-93212943</volumeId>\n    <size>10000</size>\n    <snapshotId/>\n    <availabilityZone>us-east-1a</availabilityZone>\n    <status>creating</status>\n    <createTime>2016-06-17T23:08:51.909Z</createTime>\n    <volumeType>gp2</volumeType>\n    <iops>10000</iops>\n    <encrypted>true</encrypted>\n    <kmsKeyId>my-fake-kms-key-asdf</kmsKeyId>\n</CreateVolumeResponse>"
```

Subsequent API calls to describe the volume reveals the issue, and this does not provide information or context as to why the create failed, only that the volume does not exist. I'm not sure what the SDK can do. I can forward this issue to the service team, but I'm not sure there is anything actionable by the AWS SDK for Ruby.

**Comment by ljfranklin** [comment]
>  I can forward this issue to the service team

Much appreciated. Agreed that it's not worth adding a workaround in the SDK, hopefully an easy fix for the server-side team. Closing this out, thanks!
