### ISSUE TITLE
Rare NameError crashes 

### ISSUE THREAD

**Issue by fdr** [aws/aws-sdk-ruby#1233]
I have noticed these two stack traces that reference unbound symbols. I an using Ruby 2.3.1p112 and SDK 2.3.19. After crashing the process it does appear they seldom reproduce, so they're not causing me dire problems, yet since I saw them in my exception logger I thought to report them.

```
NameError: uninitialized constant Aws::Rest::Response::Parser::Body
Did you mean?  Aws::Rest::Response::Body
  from aws-sdk-core/rest/response/parser.rb:29:in `extract_body'
  from aws-sdk-core/rest/response/parser.rb:13:in `apply'
  from aws-sdk-core/rest/handler.rb:8:in `block in call'
  from seahorse/client/response.rb:43:in `block in on'
  from seahorse/client/http/response.rb:139:in `block in on_success'
  from seahorse/client/http/response.rb:166:in `block in listener'
  from seahorse/client/http/response.rb:130:in `on_done'
  from seahorse/client/http/response.rb:137:in `on_success'
  from seahorse/client/response.rb:42:in `on'
  from aws-sdk-core/rest/handler.rb:8:in `call'
  from aws-sdk-core/plugins/user_agent.rb:12:in `call'
  from seahorse/client/plugins/endpoint.rb:41:in `call'
  from aws-sdk-core/plugins/s3_url_encoded_keys.rb:39:in `manage_keys'
  from aws-sdk-core/plugins/s3_url_encoded_keys.rb:31:in `call'
  from aws-sdk-core/plugins/param_validator.rb:21:in `call'
  from seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  from aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
  from aws-sdk-core/plugins/s3_accelerate.rb:33:in `call'
  from aws-sdk-core/plugins/param_converter.rb:20:in `call'
  from aws-sdk-core/plugins/response_paging.rb:26:in `call'
  from seahorse/client/plugins/response_target.rb:21:in `call'
  from seahorse/client/request.rb:70:in `send_request'
  from seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
```

```
NameError: uninitialized constant Aws::Xml::Parser::Stack::Frame
Did you mean?  Aws::Xml::Parser::Frame
  from aws-sdk-core/xml/parser/stack.rb:49:in `child_frame'
  from aws-sdk-core/xml/parser/stack.rb:18:in `start_element'
  from aws-sdk-core/xml/parser/engines/rexml.rb:27:in `tag_start'
  from rexml/parsers/streamparser.rb:27:in `parse'
  from aws-sdk-core/xml/parser/engines/rexml.rb:19:in `parse'
  from aws-sdk-core/xml/parser.rb:44:in `parse'
  from aws-sdk-core/rest/response/body.rb:37:in `parse'
  from aws-sdk-core/rest/response/body.rb:23:in `apply'
  from aws-sdk-core/rest/response/parser.rb:32:in `extract_body'
  from aws-sdk-core/rest/response/parser.rb:13:in `apply'
  from aws-sdk-core/rest/handler.rb:8:in `block in call'
  from seahorse/client/response.rb:43:in `block in on'
  from seahorse/client/http/response.rb:139:in `block in on_success'
  from seahorse/client/http/response.rb:166:in `block in listener'
  from seahorse/client/http/response.rb:130:in `on_done'
  from seahorse/client/http/response.rb:137:in `on_success'
  from seahorse/client/response.rb:42:in `on'
  from aws-sdk-core/rest/handler.rb:8:in `call'
  from aws-sdk-core/plugins/user_agent.rb:12:in `call'
  from seahorse/client/plugins/endpoint.rb:41:in `call'
  from aws-sdk-core/plugins/s3_url_encoded_keys.rb:39:in `manage_keys'
  from aws-sdk-core/plugins/s3_url_encoded_keys.rb:31:in `call'
  from aws-sdk-core/plugins/param_validator.rb:21:in `call'
  from seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  from aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
  from aws-sdk-core/plugins/s3_accelerate.rb:33:in `call'
  from aws-sdk-core/plugins/param_converter.rb:20:in `call'
  from aws-sdk-core/plugins/response_paging.rb:26:in `call'
  from seahorse/client/plugins/response_target.rb:21:in `call'
  from seahorse/client/request.rb:70:in `send_request'
  from seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
```

**Comment by awood45** [comment]
Are you running your application under concurrency? `Aws.eager_autoload!` avoids concurrency loading issues with the `autoload` method.

That said, I'll investigate to see if we can make those values thread safe despite autoload.

**Comment by fdr** [comment]
Yeah, I'm using Sidekiq in a typical way.

Does `eager_autoload!` also load every part of the SDK? That's a cure worse than the disease, in my case...

**Comment by awood45** [comment]
It does, but you can call it with only a subset of services as well. For example: `Aws.eager_autoload!(services: %w(S3 EC2))`

**Comment by fdr** [comment]
On Thu, Jul 7, 2016 at 4:33 PM Alex Wood <notifications@github.com> wrote:

> It does, but you can call it with only a subset of services as well. For
> example: Aws.eager_autoload!(services: %w(S3 EC2))
>
That could help a great deal: I will do this. Thank you for your help.

**Comment by trevorrowe** [comment]
Closing this as a known issue/limitation of autoloading. We are investigating removing use of Ruby's `autoload` from the SDK in the future.
