### ISSUE TITLE
Aws::S3::Errors::SignatureDoesNotMatch when passing credentials directly to Aws::S3::Resource.new 

### ISSUE THREAD

**Issue by mpick92** [aws/aws-sdk-ruby#1258]
While using [this script](https://gist.github.com/vikas027/be1010dd13f70ecd2f5e) on my local machine I ran upon the vague `Aws::S3::Errors::SignatureDoesNotMatch` error in `us-east-1` region.
```
/Users/mp042400/.rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.4.3/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The request signature we calculated does not match the signature you provided. Check your key and signing method. (Aws::S3::Errors::SignatureDoesNotMatch)
	from /Users/mp042400/.rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.4.3/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
	from /Users/mp042400/.rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.4.3/lib/aws-sdk-core/plugins/s3_accelerate.rb:33:in `call'
	from /Users/mp042400/.rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.4.3/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /Users/mp042400/.rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.4.3/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /Users/mp042400/.rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.4.3/lib/seahorse/client/request.rb:70:in `send_request'
	from /Users/mp042400/.rvm/gems/ruby-2.2.1/gems/aws-sdk-core-2.4.3/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /Users/mp042400/.rvm/gems/ruby-2.2.1/gems/aws-sdk-resources-2.4.3/lib/aws-sdk-resources/services/s3/file_uploader.rb:42:in `block in put_object'
	from /Users/mp042400/.rvm/gems/ruby-2.2.1/gems/aws-sdk-resources-2.4.3/lib/aws-sdk-resources/services/s3/file_uploader.rb:49:in `open_file'
	from /Users/mp042400/.rvm/gems/ruby-2.2.1/gems/aws-sdk-resources-2.4.3/lib/aws-sdk-resources/services/s3/file_uploader.rb:41:in `put_object'
	from /Users/mp042400/.rvm/gems/ruby-2.2.1/gems/aws-sdk-resources-2.4.3/lib/aws-sdk-resources/services/s3/file_uploader.rb:34:in `upload'
	from /Users/mp042400/.rvm/gems/ruby-2.2.1/gems/aws-sdk-resources-2.4.3/lib/aws-sdk-resources/services/s3/object.rb:251:in `upload_file'
	from s3test.rb:20:in `<main>'
```

To reproduce this error:
* Download [this script](https://gist.github.com/vikas027/be1010dd13f70ecd2f5e) and configure buckets and credentials appropriately
* `echo hello > hello.txt`
* `ruby s3test.rb hello.txt`

My fix:
* Ensure ~/.aws/ contains your credentials per [this guide](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-config-files)
* Do not pass the credentials directly in during `Aws::S3::Resource.new`
  * remove `credentials: Aws::Credentials.new(access_key, secret_access_key)` from script

**Comment by mpick92** [comment]
I am still having the same error in a different environment (Windows 2012 R2), regardless of credential location...
Might as well close this issue and role it into #455, I have wasted too much time trying to debug this vague error today.

**Comment by mpick92** [comment]
Between an error in copy/pasting and special characters in my credentials, I finally fixed the error. 
Location of credentials is irrelevant to this issue.
[This issue](https://github.com/aws/aws-cli/issues/602) helped me fix my problem using the aws cli.
