### ISSUE TITLE
Aws::S3::Bucket#objects cannot be used with start_after

### ISSUE THREAD

**Issue by javawizard** [aws/aws-sdk-ruby#1335]
Attempting to invoke `objects(start_after: ...)` on a Bucket resource doesn't work:

```
/home/docker/.gem/ruby/2.3.0/gems/aws-sdk-core-2.6.15/lib/aws-sdk-core/param_validator.rb:28:in `validate!': unexpected value at params[:start_after] (ArgumentError)
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-core-2.6.15/lib/aws-sdk-core/param_validator.rb:13:in `validate!'
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-core-2.6.15/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-core-2.6.15/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-core-2.6.15/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-core-2.6.15/lib/aws-sdk-core/plugins/s3_dualstack.rb:24:in `call'
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-core-2.6.15/lib/aws-sdk-core/plugins/s3_accelerate.rb:34:in `call'
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-core-2.6.15/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-core-2.6.15/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-core-2.6.15/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-core-2.6.15/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-core-2.6.15/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-resources-2.6.15/lib/aws-sdk-resources/request.rb:24:in `call'
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-resources-2.6.15/lib/aws-sdk-resources/operations.rb:139:in `all_batches'
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-resources-2.6.15/lib/aws-sdk-resources/collection.rb:18:in `each'
	from /home/docker/.gem/ruby/2.3.0/gems/aws-sdk-resources-2.6.15/lib/aws-sdk-resources/collection.rb:18:in `each'
	...
```

I would expect this to work, and pass along `start-after` to the underlying API call.

**Comment by javawizard** [comment]
```
Aws::S3::Bucket.instance_variable_get(:@operations)[:objects].request.instance_variable_set(:@method_name, 'list_objects_v2')
```
works around it, so I assume it's just hitting the v1 endpoint right now?

**Comment by trevorrowe** [comment]
Sorry for the slow response. You are correct. We should be able to modify the resource definition to make use of the v2 list operation. This should be backwards compatible from the resource interface. I'll add this as a feature request.

**Comment by awood45** [comment]
Added to feature request backlog.

**Comment by abepetrillo** [comment]
@awendt was this ever fixed? I'm hitting the same issue:
```
aws-sdk-core-3.46.2/lib/aws-sdk-core/param_validator.rb:32:in `validate!': unexpected value at params[:start_after] (ArgumentError)
```

**Comment by mullermp** [comment]
I've fixed this issue and pushed the changes upstream. They will need to be built using our internal build system and deployed to all of the SDKs. Please allow some time for this to happen.

**Comment by Haseeb717** [comment]
Is that issue fixed?

**Comment by mullermp** [comment]
I believe so - https://github.com/aws/aws-sdk-ruby/blob/master/apis/s3/2006-03-01/resources-1.json#L238
