### ISSUE TITLE
sqs client with fifo queues, message_group_id and message_deduplication_id problem

### ISSUE THREAD

**Issue by gitleet** [aws/aws-sdk-ruby#1430]
I can't seem to be able to send a simple message using fifo queues.
I am setting both the message_deduplication_id and message_group_id but I keep getting the error:

```
ArgumentError: parameter validator found 2 errors:
  - unexpected value at params[:message_deduplication_id]
  - unexpected value at params[:message_group_id]
```

The code I am using is from the documentation with a small modifications:

```
                      sqs.send_message({
			  queue_url: q_url, # required
			  message_body: "hello", # required
			  delay_seconds: 1,
			  message_attributes: {
			    "someattribute1" => {
			      string_value: "String",
			      data_type: "String", # required
			    },
			  },
			  message_deduplication_id: "dedup1",
			  message_group_id: "mg123"
			})
```

What am I doing wrong here?

Thanks!

**Comment by awood45** [comment]
This makes it look like you have an older version of the model, since these are client-side validation errors.

What version of the SDK are you using?

**Comment by awood45** [comment]
This should work in version `2.6.24` and up.

**Comment by gitleet** [comment]
Thanks working now.

Strange I just put 'gem aws-sdk' and it pulled down such an old version (2.3)

Thanks, I spent the morning trying to figure this out and appreciate your prompt help!

**Comment by ykessler** [comment]
Same here: upgraded gem to 2.10 and issue resolved

**Comment by hvdnew** [comment]
I am getting the same exception and the libraries I'm using are:
1. Logstash - 6.6
2. jruby - 2.3.0
3. AWS SDK - 2.11.202 

2019-02-18T13:11:21,904][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<Aws::SQS::Errors::InvalidParameterValue: The request must contain the parameter MessageGroupId.>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.11.202/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.11.202/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.11.202/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.11.202/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.11.202/lib/seahorse/client/plugins/response_target.rb:21:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.11.202/lib/seahorse/client/request.rb:70:in `send_request'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-core-2.11.202/lib/seahorse/client/base.rb:207:in `block in define_operation_methods'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-sqs-5.1.2/lib/logstash/outputs/sqs.rb:172:in `send_message_batch'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-sqs-5.1.2/lib/logstash/outputs/sqs.rb:142:in `block in multi_receive_encoded_batch'", "org/jruby/RubyArray.java:1734:in `each'", "org/jruby/RubyEnumerable.java:1067:in `each_with_index'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-sqs-5.1.2/lib/logstash/outputs/sqs.rb:133:in `multi_receive_encoded_batch'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-sqs-5.1.2/lib/logstash/outputs/sqs.rb:120:in `multi_receive_encoded'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:87:in `multi_receive'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:114:in `multi_receive'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:97:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:373:in `block in output_batch'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:372:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:324:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:287:in `block in start_workers'"]}
