### ISSUE TITLE
"force" param on Aws::EC2::Client#stop_instances fails param validator

### ISSUE THREAD

**Issue by shortdudey123** [aws/aws-sdk-ruby#1432]
**Gem Version:**
2.7.11

**Client call that exceptions out:**
```
instance_id = "i-123456"
client.stop_instances(instance_ids: [instance_id], force: true)
```

**API Json:**
```
cat .bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.11/apis/ec2/2016-11-15/api-2.json | grep -A18 \"StopInstancesRequest\"\:
    "StopInstancesRequest":{
      "type":"structure",
      "required":["InstanceIds"],
      "members":{
        "DryRun":{
          "shape":"Boolean",
          "locationName":"dryRun"
        },
        "InstanceIds":{
          "shape":"InstanceIdStringList",
          "locationName":"InstanceId"
        },
        "Force":{
          "shape":"Boolean",
          "locationName":"force"
        }
      }
    },
    "StopInstancesResult":{
$
```

**Stacktrace**
```
/path/to/script/.bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.11/lib/aws-sdk-core/param_validator.rb:28:in `validate!': unexpected value at params[:force] (ArgumentError)
    from /path/to/script/.bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.11/lib/aws-sdk-core/param_validator.rb:13:in `validate!'
    from /path/to/script/.bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.11/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'
    from /path/to/script/.bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.11/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
    from /path/to/script/.bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.11/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
    from /path/to/script/.bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.11/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
    from /path/to/script/.bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.11/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
    from /path/to/script/.bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.11/lib/seahorse/client/plugins/response_target.rb:21:in `call'
    from /path/to/script/.bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.11/lib/seahorse/client/request.rb:70:in `send_request'
    from /path/to/script/.bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.11/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
    from /path/to/script/helper.rb:109:in `ec2_stop'
    from main.rb:206:in `main'
    from main.rb:212:in `<main>'
```

**Comment by awood45** [comment]
I'm unable to recreate this locally. I'm actually thinking you may want to try reinstalling the SDK, just on a hunch.

**Comment by shortdudey123** [comment]
I blew away by bundle dir and reran `bundle install`.  After that, i can't reproduce:

```
[1] pry(main)> require 'aws-sdk'
=> true
[2] pry(main)> Aws::VERSION
=> "2.7.11"
[3] pry(main)> client = Aws::EC2::Client.new
=> #<Aws::EC2::Client>
[4] pry(main)> instance_id = 'i-12345678'
=> "i-12345678"
[5] pry(main)> client.stop_instances(instance_ids: [instance_id])
=> #<struct Aws::EC2::Types::StopInstancesResult
 stopping_instances=
  [#<struct Aws::EC2::Types::InstanceStateChange
    instance_id="i-12345678",
    current_state=#<struct Aws::EC2::Types::InstanceState code=64, name="stopping">,
    previous_state=#<struct Aws::EC2::Types::InstanceState code=16, name="running">>]>
[6] pry(main)> client.stop_instances(instance_ids: [instance_id], force: true)
=> #<struct Aws::EC2::Types::StopInstancesResult
 stopping_instances=
  [#<struct Aws::EC2::Types::InstanceStateChange
    instance_id="i-12345678",
    current_state=#<struct Aws::EC2::Types::InstanceState code=64, name="stopping">,
    previous_state=#<struct Aws::EC2::Types::InstanceState code=64, name="stopping">>]>
[7] pry(main)> client.start_instances(instance_ids: [instance_id])
=> #<struct Aws::EC2::Types::StartInstancesResult
 starting_instances=
  [#<struct Aws::EC2::Types::InstanceStateChange
    instance_id="i-12345678",
    current_state=#<struct Aws::EC2::Types::InstanceState code=0, name="pending">,
    previous_state=#<struct Aws::EC2::Types::InstanceState code=80, name="stopped">>]>
[8] pry(main)> 
```

**Comment by shortdudey123** [comment]
Based on that, i am going to chock this up to a screwed up gem installation for some reason.

**Comment by awood45** [comment]
I think that's most likely. I've seen this about one or two other times (different services/params each time), and that's always fixed it. There's possibly an investigation in to if JSON-based code gen makes this kind of issue more likely, but that would be mooted by the upcoming major version bump of the SDK.

Closing this for now, if you see any kind of recurrence feel free to reopen.
