### ISSUE TITLE
Handle upstream S3 timeouts with an Aws::S3::Errors namespaced exception

### ISSUE THREAD

**Issue by blimmer** [aws/aws-sdk-ruby#1435]
With the current S3 outage, we're seeing an exception from Seahorse vs. something in the `Aws::S3::Errors` namespace.

```
execution expired (Seahorse::Client::NetworkingError)
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/seahorse/client/net_http/connection_pool.rb:285:in `start_session'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/seahorse/client/net_http/connection_pool.rb:92:in `session_for'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/seahorse/client/net_http/handler.rb:119:in `session'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/seahorse/client/net_http/handler.rb:71:in `transmit'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/seahorse/client/net_http/handler.rb:45:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/seahorse/client/plugins/content_length.rb:12:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/s3_request_signer.rb:88:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/s3_request_signer.rb:23:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/s3_request_signer.rb:65:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/s3_redirects.rb:15:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/retry_errors.rb:88:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/s3_dualstack.rb:32:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/s3_accelerate.rb:49:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/s3_md5s.rb:31:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/s3_expect_100_continue.rb:21:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/s3_bucket_name_restrictions.rb:12:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/s3_bucket_dns.rb:31:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/rest/handler.rb:7:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/s3_dualstack.rb:24:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/s3_accelerate.rb:34:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/seahorse/client/plugins/response_target.rb:21:in `call'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/seahorse/client/request.rb:70:in `send_request'
from /Users/blimmer/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.7.4/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
```

Does it make sense to namespace this error before it bubbles to the consumer?

It could be nice to abstract this away so if this changed downstream (using something other than Seahorse), it wouldn't break author's handling of this type of exception.

**Comment by awood45** [comment]
The main issue is that there is no good way to distinguish this error from other causes of networking errors. I'm open to ways we can wrap this that are non-breaking (since other types of network errors definitely have occurred for customers), but I'm not sure off the top of my head what that would look like.

**Comment by cjyclaire** [comment]
Closing this right now due to ages, feel free to reopen anytime with further comments or questions : )
