### ISSUE TITLE
ecs register_task_definition does not accept memory_reservation and network_mode in container_definitions

### ISSUE THREAD

**Issue by 141984** [aws/aws-sdk-ruby#1444]
ecstatic register_task_definition does not accept memory_reservation and network_mode in container_definitions

```
  resp = ecs_client.register_task_definition({
         family: "#{name}",
        network_mode: "bridge",
         container_definitions: [ # required
           {
             name: "#{package_name}",
             image: "#{docker_reg_url}/#{package_name}:#{package_version}",
             cpu: 600,
             memory: 512,
             memory_reservation: 256,
             port_mappings: [
        {
          container_port: "#{container_port}",
          protocol: "tcp", # accepts tcp, udp
        },
      ],
     essential: true,
      docker_labels: {
        "name" => "#{package_name}:#{package_version}-#{build_number}"
      },
      log_configuration: {
        log_driver: "awslogs", # required, accepts json-file, syslog, journald, gelf, fluentd, awslogs, splunk
        options: {
          "awslogs-group" => "/my/containers/mYservices",
          "awslogs-region" => "ap-southeast-1"
        },
      },
    },
  ],
})
```

```
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/aws-sdk-core/param_validator.rb:26:in `validate!': unexpected value at params[:container_definitions][0][:memory_reservation] (ArgumentError)
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/aws-sdk-core/param_validator.rb:11:in `validate!'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-
```

```
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/aws-sdk-core/param_validator.rb:26:in `validate!': parameter validator found 2 errors: (ArgumentError)
  - unexpected value at params[:network_mode]
  - unexpected value at params[:container_definitions][0][:memory_reservation]
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/aws-sdk-core/param_validator.rb:11:in `validate!'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-
```

**Comment by cjyclaire** [comment]
@141984 Thanks for the information, I cannot reproduce this locally. Since our documentation is reflecting our latest SDK version, and I noticed that it seems like you are using `v2.3.4`, and the `memory` is [introduced](https://github.com/aws/aws-sdk-ruby/commit/1f7d7a66f832ecdd8c89d0eec1f3a840bd7284eb) in `v2.5.3` could you try upgrade : ) ?

**Comment by 141984** [comment]
updated the gem and works fine, Thanks :)
