### ISSUE TITLE
Unable to tag KMS CMK resources using `create_key` or `tag_resource`

### ISSUE THREAD

**Issue by atreat** [aws/aws-sdk-ruby#1457]
I'm unable to tag keys created using a KMS client. 

Using the example in [`create_key`](http://docs.aws.amazon.com/sdkforruby/api/Aws/KMS/Client.html#create_key-instance_method)

```ruby
client = Aws::KMS::Client.new    #region/credentials set in `~/.aws/credentials`
resp = client.create_key({
  tags: [
    {
      tag_key: "CreatedBy", 
      tag_value: "ExampleUser", 
    }, 
  ], # One or more tags. Each tag consists of a tag key and a tag value.
})
```
Gives the following output:
```
ArgumentError: unexpected value at params[:tags]
    from /Users/me/.gem/ruby/2.3.3/gems/aws-sdk-core-2.7.3/lib/aws-sdk-core/param_validator.rb:28:in `validate!'
    from /Users/me/.gem/ruby/2.3.3/gems/aws-sdk-core-2.7.3/lib/aws-sdk-core/param_validator.rb:13:in `validate!'
    from /Users/me/.gem/ruby/2.3.3/gems/aws-sdk-core-2.7.3/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'
    from /Users/me/.gem/ruby/2.3.3/gems/aws-sdk-core-2.7.3/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
    from /Users/me/.gem/ruby/2.3.3/gems/aws-sdk-core-2.7.3/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
    from /Users/me/.gem/ruby/2.3.3/gems/aws-sdk-core-2.7.3/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
    from /Users/me/.gem/ruby/2.3.3/gems/aws-sdk-core-2.7.3/lib/seahorse/client/plugins/response_target.rb:21:in `call'
    from /Users/me/.gem/ruby/2.3.3/gems/aws-sdk-core-2.7.3/lib/seahorse/client/request.rb:70:in `send_request'
    from /Users/me/.gem/ruby/2.3.3/gems/aws-sdk-core-2.7.3/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
    from (irb):12
```

---
Similarly, using the [`tag_resource`](http://docs.aws.amazon.com/sdkforruby/api/Aws/KMS/Client.html#tag_resource-instance_method) method on the client gives a `NoMethodError`

```
resp = client.create_key
client.tag_resource(resp.key_metadata.arn, tags: [{tag_key: 'CreatedBy', tag_value: 'ExampleUser'}]

#NoMethodError: undefined method `tag_resource' for #<Aws::KMS::Client>
```

Snippet from my Gemfile.lock
```
    aws-sdk (2.7.3)
      aws-sdk-resources (= 2.7.3)
    aws-sdk-core (2.7.3)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-resources (2.7.3)
      aws-sdk-core (= 2.7.3)
    aws-sigv4 (1.0.0)
```

Let me know if there is anything I should try out.

**Comment by cjyclaire** [comment]
@atreat From your error log, looks like you are using `v2.7.3`, `tags` is introduced in `v2.7.9`(https://github.com/aws/aws-sdk-ruby/commit/4fd867bc4e2209df7972f4f9c2d232939fcabced), could you try upgrade? : )

**Comment by atreat** [comment]
That makes perfect sense, after an update these work great.

Thanks!
