### ISSUE TITLE
Aws::SQS::Errors::ExpiredToken when using ECS IAM Role

### ISSUE THREAD

**Issue by mik3rgit** [aws/aws-sdk-ruby#1490]
I have a simple SQS poller that uses the IAM Role associated with an ECS task. This has been working great for over a month and then all of a sudden today my service crashed with the following error. I assumed that the AWS SDK automatically fetched new credentials when they expired. I'm not sure if this is a bug in the AWS SDK or a temporary failure in the AWS ECS MetaData service in eu-central-1 at 2017-04-20T14:43:18+00:00

After restarted the process everything started working again and I have not seen this this exception again.

Here's the stack trace as well as the code that triggered the error.
```
Time: 2017-04-20T14:43:18.888
ERROR poll events loop #<Aws::SQS::Errors::ExpiredToken: The security token included in the request is expired>

/home/ec2-user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.9.7/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
    /home/ec2-user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
    /home/ec2-user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
    /home/ec2-user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
    /home/ec2-user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.9.7/lib/seahorse/client/plugins/response_target.rb:21:in `call'
    /home/ec2-user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.9.7/lib/seahorse/client/request.rb:70:in `send_request'
    /home/ec2-user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.9.7/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
    /home/ec2-user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.7/lib/aws-sdk-resources/services/sqs/queue_poller.rb:390:in `send_request'
    /home/ec2-user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.7/lib/aws-sdk-resources/services/sqs/queue_poller.rb:383:in `get_messages'
    /home/ec2-user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.7/lib/aws-sdk-resources/services/sqs/queue_poller.rb:332:in `block (2 levels) in poll'
    /home/ec2-user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.7/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `loop'
    /home/ec2-user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.7/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `block in poll'
    /home/ec2-user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.7/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `catch'
    /home/ec2-user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.7/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `poll'
    /home/ec2-user/system/notification/lib/notification/server.rb:137:in `block in configure'"

105:  @poller =  Aws::SQS::QueuePoller.new(@sqs_queue_url[@sqs_queue_type], {client: @sqs_event_client[@sqs_queue_type]})

135:  begin
136:    @log.info "Starting polling Queue SQS"
137:    @poller.poll(max_number_of_messages: 10) do |msgs|
138:      @log.debug "Pulled  #{msgs.count} SQS messages"
139:      process_SQS_messages(msgs)
140:
141:      # Set the number of messages received in this poll to help determine
142:      # how quickly to poll again
143:      msgs_received = msgs.count
144:    end
145:  rescue StandardError => e
146:    @log.error "ERROR poll events loop #{e.inspect}"
147:    @log.error "#{e.backtrace.join("\t\n")}"
148:    sleep 0.5
149:    attempts += 1
150:    retry unless attempts > 3
151:  end # begin
```

**Comment by awood45** [comment]
Given the transient nature of this, I'm suspecting a cause other than the SDK. The SDK does fetch credentials on expiration or when we see an expired token exception (then it will retry).

I'd recommend filing a ticket with AWS Support if you have ongoing concerns, but also feel free to reopen if this occurs again and we might be able to help.
