### ISSUE TITLE
Seahorse::Client::NetworkingError: Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by route** [aws/aws-sdk-ruby#1572]
I'm seeing an intermittent error like this sometimes in my long running process. So it all works but all of a sudden sometimes this start happening when I want to send a message to SQS with:

`sqs.send_message(queue_url: queue_url, message_body: message.to_json, message_group_id: bla)`

```
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:933:in `connect'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:858:in `start'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/net_http/connection_pool.rb:285:in `start_session'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/net_http/connection_pool.rb:92:in `session_for'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/net_http/handler.rb:119:in `session'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/net_http/handler.rb:71:in `transmit'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/net_http/handler.rb:45:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/plugins/content_length.rb:12:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/request_signer.rb:88:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:89:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:120:in `retry_request'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:103:in `retry_if_possible'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:91:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:120:in `retry_request'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:103:in `retry_if_possible'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:91:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:120:in `retry_request'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:103:in `retry_if_possible'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:91:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/sqs_queue_urls.rb:13:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/query/handler.rb:27:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/sqs_md5s.rb:17:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/request.rb:70:in `send_request'
/home/deploy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
```

Then boom after a few more tries it works again which gives me an idea it's unlikely an issue in my code. I wonder why this happens.

**Comment by route** [comment]
Also maybe it's not related to this but sometimes on another side when I receive messages, this issue started to happen more often recently:

```
We encountered an internal error. Please try again.

/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.17/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.17/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.17/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.17/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.17/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.17/lib/seahorse/client/request.rb:70:in `send_request'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.17/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/app/app/lib/crawl/sqs_client.rb:20:in `receive_message'
/app/app/lib/crawl/queue_listener/base.rb:35:in `block in poll'
/app/app/lib/crawl/queue_listener/base.rb:33:in `loop'
/app/app/lib/crawl/queue_listener/base.rb:33:in `poll'
/app/app/lib/crawl/queue_listener/crawl.rb:18:in `block in start'
/app/app/lib/crawl/queue_listener/base.rb:62:in `block in thread_pool'
/app/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/app/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/app/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/app/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/app/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/app/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```
Error class remains unknown so far, but I can figure it out later on.

**Comment by awood45** [comment]
This looks like a networking issue. It's unclear from this alone if it's a networking issue from your side or the service side without more context. It may be worth reaching out to [AWS Support](https://console.aws.amazon.com/support/home) in this case.

**Comment by awood45** [comment]
Though for some context, are you running on EC2 or from a local machine?

**Comment by route** [comment]
The SQS publisher is on DigitalOcean (Seahorse::Client::NetworkingError error), while consumer is on Heroku which is experiencing "We encountered an internal error. Please try again" error.

**Comment by awood45** [comment]
Going through and cleaning up old issues, this appears to have been a networking issue - the best avenue to continue to investigate this would be via AWS Support.
