### ISSUE TITLE
Aws::CloudWatchLogs::Client.new() produces NameError in versions >=3.0.0

### ISSUE THREAD

**Issue by Resisty** [aws/aws-sdk-ruby#1590]
Please fill out the sections below to help us address your issue

### Issue description
The aws-sdk-core gem seems to have broken support for CloudWatchLogs. Attempting to use Aws::CloudWatchLogs::Client.new() fails.

### Gem name
'aws-sdk-core' 3.1.0, 3.0.0

### Code snippets / steps to reproduce
First I tried to simply load a fluentd plugin using the aws-sdk-core gem into a docker image:
```
2017-08-31 18:12:29 +0000 [error]: #0 unexpected error error_class=NameError error="uninitialized constant Aws::CloudWatchLogs"
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.4.0/lib/fluent/plugin/out_cloudwatch_logs.rb:69:in `start'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/compat/call_super_mixin.rb:42:in `start'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/root_agent.rb:165:in `block in start'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/root_agent.rb:153:in `each'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/root_agent.rb:153:in `block in lifecycle'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/root_agent.rb:140:in `each'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/root_agent.rb:140:in `lifecycle'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/root_agent.rb:164:in `start'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/engine.rb:274:in `start'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/engine.rb:219:in `run'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/supervisor.rb:772:in `run_engine'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/supervisor.rb:521:in `block in run_worker'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/supervisor.rb:697:in `main_process'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/supervisor.rb:516:in `run_worker'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.20/bin/fluentd:5:in `<top (required)>'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/bin/fluentd:22:in `load'
  2017-08-31 18:12:29 +0000 [error]: #0 /usr/bin/fluentd:22:in `<main>'
```

Then I used rbenv to install various versions of aws-sdk-core directly and try to create a Client. 3.1.0 and 3.0.0 were similarly nonfunctional, but 2.7.0 worked as expected:
```
user@dir 🍔  gem install aws-sdk-core
Fetching: aws-sdk-core-3.1.0.gem (100%)
Successfully installed aws-sdk-core-3.1.0
Parsing documentation for aws-sdk-core-3.1.0
Installing ri documentation for aws-sdk-core-3.1.0
Done installing documentation for aws-sdk-core after 2 seconds
1 gem installed
user@dir 🍔  irb
irb(main):001:0> require aws-sdk-core
NameError: undefined local variable or method `aws' for main:Object
Did you mean?  cws
    from (irb):1
    from /Users/user/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
irb(main):002:0> require 'aws-sdk-core'
=> true
irb(main):003:0> thing = Aws::CloudWatchLogs::Client.new({})
NameError: uninitialized constant Aws::CloudWatchLogs
    from (irb):3
    from /Users/user/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
irb(main):004:0> Aws
=> Aws
irb(main):005:0> help(Aws)
=> nil
irb(main):006:0>
user@dir 🍔  gem uninstall aws-sdk-core
Successfully uninstalled aws-sdk-core-3.1.0
user@dir 🍔  gem install aws-sdk-core -v 3.0.0
Fetching: aws-sdk-core-3.0.0.gem (100%)
Successfully installed aws-sdk-core-3.0.0
Parsing documentation for aws-sdk-core-3.0.0
Installing ri documentation for aws-sdk-core-3.0.0
Done installing documentation for aws-sdk-core after 2 seconds
1 gem installed
user@dir 🍔  irb
irb(main):001:0> require 'aws-sdk-core'
=> true
irb(main):002:0> a = Aws::CloudWatchLogs::Client.new({})
NameError: uninitialized constant Aws::CloudWatchLogs
    from (irb):2
    from /Users/user/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
irb(main):003:0> a = Aws::Credentials.new({})
ArgumentError: wrong number of arguments (given 1, expected 2..3)
    from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/credentials.rb:7:in `initialize'
    from (irb):3:in `new'
    from (irb):3
    from /Users/user/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
irb(main):004:0>
user@dir 🍔  gem uninstall aws-sdk-core
Successfully uninstalled aws-sdk-core-3.0.0
user@dir 🍔  gem install aws-sdk-core 2.7.0
Fetching: aws-sdk-core-3.1.0.gem (100%)
Successfully installed aws-sdk-core-3.1.0
Parsing documentation for aws-sdk-core-3.1.0
Installing ri documentation for aws-sdk-core-3.1.0
Done installing documentation for aws-sdk-core after 2 seconds
ERROR:  Could not find a valid gem '2.7.0' (>= 0) in any repository
1 gem installed
user@dir 🍔  gem uninstall aws-sdk-core
Successfully uninstalled aws-sdk-core-3.1.0
user@dir 🍔  gem install aws-sdk-core -v 2.7.0
Fetching: aws-sdk-core-2.7.0.gem (100%)
Successfully installed aws-sdk-core-2.7.0
Parsing documentation for aws-sdk-core-2.7.0
Installing ri documentation for aws-sdk-core-2.7.0
Done installing documentation for aws-sdk-core after 2 seconds
1 gem installed
user@dir 🍔  irb
irb(main):001:0> require 'aws-sdk-core'
=> true
irb(main):002:0> a = Aws::CloudWatchLogs::Client.new({})
Aws::Errors::MissingRegionError: missing region; use :region option or export region name to ENV['AWS_REGION']
    from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.7.0/lib/aws-sdk-core/plugins/regional_endpoint.rb:34:in `after_initialize'
    from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.7.0/lib/seahorse/client/base.rb:84:in `block in after_initialize'
    from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.7.0/lib/seahorse/client/base.rb:83:in `each'
    from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.7.0/lib/seahorse/client/base.rb:83:in `after_initialize'
    from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.7.0/lib/seahorse/client/base.rb:21:in `initialize'
    from /Users/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.7.0/lib/seahorse/client/base.rb:105:in `new'
    from (irb):2
    from /Users/user/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
irb(main):003:0>
```

Also: https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md 404s.

**Comment by awood45** [comment]
You'll need to depend on the `aws-sdk-cloudwatch` gem rather than core, per the [relevant section in the upgrading guide](https://github.com/aws/aws-sdk-ruby/blob/master/V3_UPGRADING_GUIDE.md#user-of-the-aws-sdk-core-gem), then include `require 'aws-sdk-cloudwatch`. The `aws-sdk-core` gem in V3 does not contain service clients.

**Comment by Resisty** [comment]
Thanks for the info on that! For downstream projects (like the `definitely currently maintained` fluentd plugin) that end-users have no control over, the upgrading guide doesn't seem like an obvious document to read. Could we get that CHANGELOG visible, maybe?

**Comment by awood45** [comment]
Closing this as the question is answered. Let me know if you have any follow-up questions or issues.
