### ISSUE TITLE
Bundler::GemRequireError: There was an error while trying to load the gem 'aws-sdk-s3'

### ISSUE THREAD

**Issue by PetrKaleta** [aws/aws-sdk-ruby#1599]
Hey,
I've upgraded to sdk v3. But I have problem when launching my app. It freezes when loading `aws-sdk-s3` gem. When you kill it (Cmd+c), it shows this error.

```
Petrs-MacBook-Air:aws-sdk3-test Petr$ puma
Puma starting in single mode...
* Version 3.10.0 (jruby 9.1.12.0 - ruby 2.3.3), codename: Russell's Teapot
* Min threads: 0, max threads: 16
* Environment: development
^C- Gracefully stopping, waiting for requests to finish
! Unable to load application: Bundler::GemRequireError: There was an error while trying to load the gem 'aws-sdk-s3'.
Gem Load Error is: undefined method `stop' for nil:NilClass
Backtrace for gem load error is:
/Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/puma-3.10.0-java/lib/puma/single.rb:28:in `stop_blocked'
/Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/puma-3.10.0-java/lib/puma/launcher.rb:291:in `graceful_stop'
/Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/puma-3.10.0-java/lib/puma/launcher.rb:407:in `block in setup_signals'
Bundler Error Backtrace:
Bundler::GemRequireError: There was an error while trying to load the gem 'aws-sdk-s3'.
Gem Load Error is: undefined method `stop' for nil:NilClass
Backtrace for gem load error is:
/Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/puma-3.10.0-java/lib/puma/single.rb:28:in `stop_blocked'
/Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/puma-3.10.0-java/lib/puma/launcher.rb:291:in `graceful_stop'
/Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/puma-3.10.0-java/lib/puma/launcher.rb:407:in `block in setup_signals'
Bundler Error Backtrace:

          block in require at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/runtime.rb:85
                      each at org/jruby/RubyArray.java:1734
          block in require at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/runtime.rb:77
                      each at org/jruby/RubyArray.java:1734
                   require at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/runtime.rb:66
                   require at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler.rb:108
  block in new_from_string at config.ru:3
             instance_eval at org/jruby/RubyBasicObject.java:1691
                initialize at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/rack-2.0.3/lib/rack/builder.rb:55
                    <eval> at config.ru:1
                      eval at org/jruby/RubyKernel.java:1000
           new_from_string at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/rack-2.0.3/lib/rack/builder.rb:49
                parse_file at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/rack-2.0.3/lib/rack/builder.rb:40
               load_rackup at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/puma-3.10.0-java/lib/puma/configuration.rb:314
                       app at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/puma-3.10.0-java/lib/puma/configuration.rb:243
             load_and_bind at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/puma-3.10.0-java/lib/puma/runner.rb:138
                       run at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/puma-3.10.0-java/lib/puma/single.rb:87
                       run at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/puma-3.10.0-java/lib/puma/launcher.rb:183
                       run at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/puma-3.10.0-java/lib/puma/cli.rb:77
                    <main> at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/lib/ruby/gems/shared/gems/puma-3.10.0-java/bin/puma:10
                      load at org/jruby/RubyKernel.java:979
                    <main> at /Users/Petr/.rbenv/versions/jruby-9.1.12.0/bin/puma:22
```

 I've created minimalistic application where you can test this behaviour.

```ruby
# Gemfile
source 'https://rubygems.org'

ruby '2.3.3', engine: 'jruby', engine_version: '9.1.12.0'

gem 'puma'
gem 'sinatra', require: false
gem 'aws-sdk-s3'
```

```
# Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    aws-partitions (1.19.0)
    aws-sdk-core (3.2.0)
      aws-partitions (~> 1.0)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-kms (1.0.0)
      aws-sdk-core (~> 3)
      aws-sigv4 (~> 1.0)
    aws-sdk-s3 (1.1.0)
      aws-sdk-core (~> 3)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.0)
    aws-sigv4 (1.0.2)
    jmespath (1.3.1)
    mustermann (1.0.1)
    puma (3.10.0-java)
    rack (2.0.3)
    rack-protection (2.0.0)
      rack
    sinatra (2.0.0)
      mustermann (~> 1.0)
      rack (~> 2.0)
      rack-protection (= 2.0.0)
      tilt (~> 2.0)
    tilt (2.0.8)

PLATFORMS
  java

DEPENDENCIES
  aws-sdk-s3
  puma
  sinatra

RUBY VERSION
   ruby 2.3.3p0 (jruby 9.1.12.0)

BUNDLED WITH
   1.15.4
```

```ruby
# config.ru
require 'bundler'

Bundler.require :default

require_relative 'web_app'

run WebApp
```

```ruby
# web_app.rb
require 'sinatra/base'

class WebApp < Sinatra::Base
  get '/' do
    'Hello world!'
  end
end
```

**Comment by cjyclaire** [comment]
@PetrKaleta Hi, I think it might related to a jruby bug that I thought was travis ci only. I've already merged a PR fix issue [here](https://github.com/aws/aws-sdk-ruby/pull/1597). I'll do a version bump for kms to make this available. I'll ping the thread once that goes out, thanks!

**Comment by cjyclaire** [comment]
@PetrKaleta The latest kms version is [out](https://rubygems.org/gems/aws-sdk-kms/versions/1.1.0), could you try update and let me know if it works? (s3 gem has dependency on this) : )

**Comment by cjyclaire** [comment]
Adding to that, jruby fixed this themselves as well at [`master`](https://github.com/jruby/jruby/issues/4728)

**Comment by PetrKaleta** [comment]
Yes, works like a charm now! Thank you!

**Comment by LeKristapino** [comment]
I am having a similar issue without JRuby


```
! Unable to load application: Bundler::GemRequireError: There was an error while trying to load the gem 'aws-sdk-sqs'.
Gem Load Error is: undefined method `stop' for nil:NilClass
Backtrace for gem load error is:
/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/single.rb:37:in `stop_blocked'
/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/launcher.rb:292:in `graceful_stop'
/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/launcher.rb:396:in `block in setup_signals'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/compile_cache/iseq.rb:12:in `compile_file'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/compile_cache/iseq.rb:12:in `input_to_storage'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/compile_cache/iseq.rb:37:in `fetch'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/compile_cache/iseq.rb:37:in `load_iseq'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/binary.rb:1:in `<main>'
/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/binary.rb:1:in `<main>'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core.rb:66:in `<main>'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
/bundle/ruby/2.4.0/gems/aws-sdk-sqs-1.4.0/lib/aws-sdk-sqs.rb:8:in `<main>'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:76:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:76:in `block in require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:65:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:65:in `require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler.rb:114:in `require'
/app/config/application.rb:18:in `<top (required)>'
/app/config/environment.rb:2:in `require_relative'
/app/config/environment.rb:2:in `<top (required)>'
config.ru:3:in `require_relative'
config.ru:3:in `block in <main>'
/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
config.ru:in `new'
config.ru:in `<main>'
/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/configuration.rb:318:in `load_rackup'
/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/configuration.rb:243:in `app'
/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/runner.rb:145:in `load_and_bind'
/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/single.rb:96:in `run'
/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'
/bundle/ruby/2.4.0/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'
/bundle/ruby/2.4.0/bin/puma:23:in `load'
/bundle/ruby/2.4.0/bin/puma:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli.rb:424:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Bundler Error Backtrace:
bundler: failed to load command: puma (/bundle/ruby/2.4.0/bin/puma)
Bundler::GemRequireError: There was an error while trying to load the gem 'aws-sdk-sqs'.
Gem Load Error is: undefined method `stop' for nil:NilClass
Backtrace for gem load error is:
/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/single.rb:37:in `stop_blocked'
/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/launcher.rb:292:in `graceful_stop'
/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/launcher.rb:396:in `block in setup_signals'
/bundle/ruby/2.4.0/gems/bootsnap-1.3.1/lib/bootsnap/compile_cache/iseq.rb:12:in `compile_file'
- Gracefully stopping, waiting for requests to finish
Puma starting in single mode...
* Version 3.12.0 (ruby 2.4.4-p296), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: demo
```

```
ruby '2.4.4'

gem 'rails', '~> 5.2.0'
...
gem 'shoryuken'
gem 'aws-sdk-sqs'
gem 'aws-sdk', '~> 3'
```
