### ISSUE TITLE
NameError: undefined local variable or method 'v' for Aws::Util:Module

### ISSUE THREAD

**Issue by tarcieri** [aws/aws-sdk-ruby#1603]
Occurring here:

https://github.com/aws/aws-sdk-ruby/blob/734a23dfb940c4dfa8e2fb8fb6056d947bfef20a/gems/aws-sdk-core/lib/aws-sdk-core/util.rb#L34

It's likely `v` should be `obj` (or perhaps `obj.dup`/`obj.clone`?). I can send a PR...

**Comment by cjyclaire** [comment]
@tarcieri Ah thanks for catching! exactly, happy to review the PR if possible, if you don't have time, let me know and I can take this too.

**Comment by tarcieri** [comment]
If I were to do a PR, I guess my first question would be what is the correct behavior here re: `dup`/`clone`?

**Comment by cjyclaire** [comment]
@tarcieri Taking a second look, this `:deep_copy` is actually not used else where in the sdk, you can refer the `:deep_copy` we have at code generation [here](https://github.com/aws/aws-sdk-ruby/blob/734a23dfb940c4dfa8e2fb8fb6056d947bfef20a/build_tools/aws-sdk-code-generator/lib/aws-sdk-code-generator/helper.rb#L152).

**Comment by tarcieri** [comment]
I encountered this error attempting to invoke `batch_create_tags` on an `Aws::EC2::Instance`:

```
NameError: undefined local variable or method `v' for Aws::Util:Module
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/util.rb:34:in `deep_copy'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/util.rb:28:in `block in deep_copy'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/util.rb:27:in `each'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/util.rb:27:in `inject'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/util.rb:27:in `deep_copy'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/util.rb:32:in `block in deep_copy'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/util.rb:32:in `map'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/util.rb:32:in `deep_copy'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/util.rb:28:in `block in deep_copy'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/util.rb:27:in `each'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/util.rb:27:in `inject'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/util.rb:27:in `deep_copy'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/util.rb:18:in `copy_hash'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-ec2-1.0.0/lib/aws-sdk-ec2/instance.rb:1399:in `block in batch_create_tags'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/resources/collection.rb:100:in `yield'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/resources/collection.rb:100:in `block (2 levels) in non_empty_batches'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/resources/collection.rb:99:in `each'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-core-3.0.0/lib/aws-sdk-core/resources/collection.rb:99:in `block in non_empty_batches'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-ec2-1.0.0/lib/aws-sdk-ec2/instance.rb:1398:in `each'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-ec2-1.0.0/lib/aws-sdk-ec2/instance.rb:1398:in `each'
  /home/tony/.gem/ruby/2.4.0/gems/aws-sdk-ec2-1.0.0/lib/aws-sdk-ec2/instance.rb:1398:in `batch_create_tags'
```

**Comment by cjyclaire** [comment]
@tarcieri Thanks for the info! I'll work on thw fix and add tests

**Comment by cjyclaire** [comment]
Soft update, took a while yet PR #1604 is opened to address this issue add add more test for batch operation behavior, which is under review

**Comment by cjyclaire** [comment]
The PR fix has been merged, will be out in next release.
Appreciate your patience, will ping the thread again once the release is out : )

**Comment by cjyclaire** [comment]
Thank you for your patience! The release is [out](https://rubygems.org/gems/aws-sdk-ec2/versions/1.3.0), closing.
