### ISSUE TITLE
aws-sdk error where awscli works

### ISSUE THREAD

**Issue by ook** [aws/aws-sdk-ruby#1659]
Hi,

I meet a weird bug when using ruby `aws-sdk` with non standard endpoint (localstack), whereas `awscli` works perfectly with it.

```
Aws::S3::Resource.new.bucket('mybucket').exists?

/usr/local/lib/ruby/2.2.0/net/http.rb:879:in `initialize': unable to connect to `mybucket.localstack`; SocketError: getaddrinfo: Name or service not known (Seahorse::Client::NetworkingError)` raised by Aws Seahorse.
```

In the same container, it works with awscli:

```
root@35afc611394b:/app/user# aws --endpoint-url=http://localstack:4572 s3 mb s3://mybucket
make_bucket: mybucket
```

I created a project with a docker-compose setup to show the problem: https://github.com/ook/localstack-s3-problem

Have I forget some configuration to make `aws-sdk-ruby` works or is it a bug in aws-sdk-ruby ?

Thank you by advance.

**Comment by awood45** [comment]
It would be helpful to see how you've configured your custom endpoint in your client, to determine why you're seeing this issue. It looks like a standard networking error.

**Comment by ook** [comment]
Sure. Let me show you a complete session:

```
root@35afc611394b:/app/user# aws --endpoint-url=http://localstack:4572 s3 mb s3://mybucket
make_bucket: mybucket
root@35afc611394b:/app/user# ping -c 2 localstack
PING localstack (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: icmp_seq=0 ttl=64 time=6.260 ms
64 bytes from 172.18.0.2: icmp_seq=1 ttl=64 time=7.359 ms
--- localstack ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 6.260/6.809/7.359/0.550 ms
root@35afc611394b:/app/user# irb
irb(main):001:0> require 'aws-sdk'
=> true
irb(main):002:0> Aws.config.update(endpoint: "http://localstack:4572/", credentials: Aws::Credentials.new('credentials', 'areIgnored'))
=> {:endpoint=>"http://localstack:4572/", :credentials=>#<Aws::Credentials access_key_id="credentials">}
irb(main):003:0> Aws::S3::Resource.new.bucket('mybucket').exists?
Seahorse::Client::NetworkingError: unable to connect to `mybucket.localstack`; SocketError: getaddrinfo: Name or service not known
	from /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
	from /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /usr/local/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
	from /usr/local/lib/ruby/2.2.0/timeout.rb:98:in `call'
	from /usr/local/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
	from /usr/local/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /usr/local/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /usr/local/lib/ruby/2.2.0/net/http.rb:858:in `start'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/seahorse/client/net_http/connection_pool.rb:288:in `start_session'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/seahorse/client/net_http/connection_pool.rb:95:in `session_for'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/seahorse/client/net_http/handler.rb:121:in `session'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/seahorse/client/net_http/handler.rb:73:in `transmit'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/seahorse/client/net_http/handler.rb:47:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/seahorse/client/plugins/content_length.rb:12:in `call'
	from /usr/local/bundle/gems/aws-sdk-s3-1.6.0/lib/aws-sdk-s3/plugins/s3_signer.rb:109:in `call'
... 34 levels...
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/aws-sdk-core/waiters/poller.rb:63:in `send_request'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/aws-sdk-core/waiters/poller.rb:49:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/aws-sdk-core/waiters/waiter.rb:105:in `block in poll'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/aws-sdk-core/waiters/waiter.rb:102:in `loop'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/aws-sdk-core/waiters/waiter.rb:102:in `poll'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/aws-sdk-core/waiters/waiter.rb:92:in `block (2 levels) in wait'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/aws-sdk-core/waiters/waiter.rb:91:in `catch'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/aws-sdk-core/waiters/waiter.rb:91:in `block in wait'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/aws-sdk-core/waiters/waiter.rb:90:in `catch'
	from /usr/local/bundle/gems/aws-sdk-core-3.7.0/lib/aws-sdk-core/waiters/waiter.rb:90:in `wait'
	from /usr/local/bundle/gems/aws-sdk-s3-1.6.0/lib/aws-sdk-s3/waiters.rb:57:in `wait'
	from /usr/local/bundle/gems/aws-sdk-s3-1.6.0/lib/aws-sdk-s3/bucket.rb:93:in `wait_until_exists'
	from /usr/local/bundle/gems/aws-sdk-s3-1.6.0/lib/aws-sdk-s3/bucket.rb:74:in `exists?'
	from (irb):3
	from /usr/local/bin/irb:11:in `<main>'
irb(main):004:0> require 'net/http'
=> false
irb(main):005:0> Net::HTTP.get(URI('http://localstack:4572/'))
=> "<ListAllMyBucketsResult xmlns=\"http://s3.amazonaws.com/doc/2006-03-01\"><Owner><ID>bcaf1ffd86f41161ca5fb16fd081034f</ID><DisplayName>webfile</DisplayName></Owner><Buckets><Bucket><Name>test1</Name><CreationDate>2006-02-03T16:45:09.000Z</CreationDate></Bucket><Bucket><Name>mybucket</Name><CreationDate>2006-02-03T16:45:09.000Z</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>"
```

So, it shows the link is well configured and reachable into the container, `awscli` can access it without a problem. In a ruby console, the stdlib `net/http` can reach the endpoint, only `aws-sdk` have problem with it.

Am I misusing `Aws.config.update` method?

**Comment by ook** [comment]
As followup, someone on SO found a workaroud:  adding `force_path_style: true` to Aws.config make the sdk behave as expected.
Shouldn't this option been set by default to be consistent with `awscli` ?

**Comment by awood45** [comment]
That was my instinct on this as well. The behavior the SDK exhibits is valid against S3 endpoints. Given that the issue here applies only to a custom endpoint setup, the workaround seems sufficient. Closing, let me know if you have any follow-up questions.
