### ISSUE TITLE
Aws::EC2::Snapshot#wait_until_completed throws ArgumentError

### ISSUE THREAD

**Issue by lenon** [aws/aws-sdk-ruby#1675]
### Issue description

Calling `Aws::EC2::Snapshot#wait_until_completed` always throws an `ArgumentError`. It seems to be caused by this line in `snapshot.rb`:

https://github.com/aws/aws-sdk-ruby/blob/55aaef1b75e730386f6e34154e40f15efbab82e5/gems/aws-sdk-ec2/lib/aws-sdk-ec2/snapshot.rb#L177

I think it should be

```ruby
Snapshot.new({
  id: @id,
  data: resp.data.snapshots[0],
  client: @client
})
```

### Gem name

`gem 'aws-sdk', '~> 3'`

### Version of Ruby, OS environment

```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
```

### Code snippets / steps to reproduce

The following code raises `ArgumentError`:

```ruby
require 'aws-sdk-ec2'

ec2 = Aws::EC2::Resource.new
snapshot = ec2.create_snapshot(volume_id: '<volume id>')
snapshot.wait_until_completed

puts 'done'
```

Output:

```
/Users/lenon/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aws-sdk-ec2-1.21.0/lib/aws-sdk-ec2/snapshot.rb:177:in `[]': wrong number of arguments (given 0, expected 1..2) (ArgumentError)
	from /Users/lenon/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aws-sdk-ec2-1.21.0/lib/aws-sdk-ec2/snapshot.rb:177:in `wait_until_completed'
	from test.rb:11:in `<main>'
```

**Comment by cjyclaire** [comment]
Thanks for reporting, working on the generator fix.

At same time, you can use [`wait_until`](http://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Client.html#wait_until-instance_method) method from EC2 client to workaround the issue (recommended).

**Comment by cjyclaire** [comment]
Another soft update, this is a bug in shared resource model (here](https://github.com/aws/aws-sdk-ruby/blob/master/apis/ec2/2016-11-15/resources-1.json#L1795), and our generator trusted the path value there, I'll create a PR shortly from our side and fix the shared resource model upstream.

**Comment by cjyclaire** [comment]
The PR fix has been reviewed and merged in, will be available in the next release
