### ISSUE TITLE
Support credential_source from shared profile

### ISSUE THREAD

**Issue by llibicpep** [aws/aws-sdk-ruby#1677]
### Issue description

`credential_source` currently is not supported.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core 2.10.104

### Version of Ruby, OS environment

Mac OS, Debian, ruby v2.4.2

### Code snippets / steps to reproduce

The following config:

```bash
AWS="aws --profile ${PROFILE_NAME}"
${AWS} configure set role_arn "${ROLE_ARN}"
${AWS} configure set credential_source "${CREDENTIALS_SOURCE}"
```

Will produce error:

```
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/aws-sdk-core/shared_config.rb:156:in `assume_role_from_profile': Profile jarvis has a role_arn, but no source_profile. (Aws::Errors::NoSourceProfileError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/aws-sdk-core/shared_config.rb:111:in `assume_role_credentials_from_config'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/aws-sdk-core/credential_provider_chain.rb:95:in `assume_role_with_profile'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/aws-sdk-core/credential_provider_chain.rb:78:in `assume_role_credentials'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/aws-sdk-core/credential_provider_chain.rb:12:in `block in resolve'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/aws-sdk-core/credential_provider_chain.rb:11:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/aws-sdk-core/credential_provider_chain.rb:11:in `resolve'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/aws-sdk-core/plugins/request_signer.rb:37:in `block in <class:RequestSigner>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/seahorse/client/configuration.rb:70:in `call'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/seahorse/client/configuration.rb:205:in `block in resolve_defaults'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/seahorse/client/configuration.rb:57:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/seahorse/client/configuration.rb:57:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/seahorse/client/configuration.rb:204:in `resolve_defaults'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/seahorse/client/configuration.rb:200:in `value_at'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/seahorse/client/configuration.rb:189:in `block in resolve'
	from /opt/chefdk/embedded/lib/ruby/2.4.0/set.rb:324:in `each_key'
	from /opt/chefdk/embedded/lib/ruby/2.4.0/set.rb:324:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/seahorse/client/configuration.rb:189:in `resolve'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/seahorse/client/configuration.rb:177:in `apply_defaults'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/seahorse/client/configuration.rb:150:in `build!'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/seahorse/client/base.rb:68:in `build_config'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/seahorse/client/base.rb:19:in `initialize'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.90/lib/seahorse/client/base.rb:105:in `new'
	from /home/jenkins/workspace/test@tmp/durable-7147b3d0/script.sh:4:in `<main>'
```

**Comment by awood45** [comment]
You're correct that this is not yet supported. Definitely noting the interest here.

**Comment by awood45** [comment]
This work is in progress for version 3 of the SDK. Backporting to V2 will be prioritized depending on how simple/complex the refactor ends up being.

**Comment by awood45** [comment]
This has been added, and the follow-up PR for additional features beyond the scope of the issue may or may not be merged. Still, this is resolved.
