### ISSUE TITLE
shared credentials doesn't parse region from specific profile

### ISSUE THREAD

**Issue by ccammilleri** [aws/aws-sdk-ruby#1686]
Please fill out the sections below to help us address your issue

### Issue description
The gem fails to set the region if it's specified outside the default profile in `~/.aws/credentials` .
 
Note: A workaround is to set the default profile with the region specified in it. Although, I don't think this would allow you to use multiple regions per profile.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
```
    aws-partitions (1.51.0)
    aws-sdk-core (3.12.0)
      aws-partitions (~> 1.0)
      aws-sigv4 (~> 1.0)
    aws-sdk-ses (1.6.0)
      aws-sdk-core (~> 3)
      aws-sigv4 (~> 1.0)
    aws-sigv4 (1.0.2)
  aws-sdk-ses
```

### Version of Ruby, OS environment
debian (ubuntu), ruby 2.4.2

### Code snippets / steps to reproduce
I'm setting the credentials like so:
```
credentials = Aws::SharedCredentials.new(profile_name: 'automailer')
ses = Aws::SES::Client.new(credentials: credentials)
```

My `~/.aws/credentials` looks like this:
```
[automailer]
aws_access_key_id = XXXXX
aws_secret_access_key = XXXXX
region = us-east-1
```

backtrace:
```
2017-12-31 20:53:19 - Aws::Errors::MissingRegionError - missing region; use :region option or export region name to ENV['AWS_REGION']:
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/aws-sdk-core/plugins/signature_v4.rb:88:in `build_signer'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/aws-sdk-core/plugins/signature_v4.rb:9:in `block in <class:SignatureV4>'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:70:in `call'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:205:in `block in resolve_defaults'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:57:in `each'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:57:in `each'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:204:in `resolve_defaults'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:200:in `value_at'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:189:in `block in resolve'
	/home/ubuntu/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/set.rb:324:in `each_key'
	/home/ubuntu/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/set.rb:324:in `each'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:189:in `resolve'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:177:in `apply_defaults'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:150:in `build!'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/seahorse/client/base.rb:62:in `build_config'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/seahorse/client/base.rb:19:in `initialize'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-ses-1.6.0/lib/aws-sdk-ses/client.rb:143:in `initialize'
	/home/ubuntu/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-3.12.0/lib/seahorse/client/base.rb:99:in `new'
```

**Comment by awood45** [comment]
If you want to pick up the region and credentials, you should try this:

```ruby
ses = Aws::SES::Client.new(profile: "automailer")
```

That would pick up both your shared credentials and the region specification. The credentials object class is just that.

If you're unable to use the default credential provider chain (for example, because you also have environment variable credentials but don't want to use them here), you could specify the profile (for the region setting) AND set your credentials object directly as you did above.

Closing, feel free to reopen if you have more issues or follow-up questions.
