### ISSUE TITLE
No valid waiter names for SSM API

### ISSUE THREAD

**Issue by vanguard737** [aws/aws-sdk-ruby#1692]
In the v2 SDK, it appears that SSMs don't expose any valid waiters.  If I throw a bogus waiter at (for example) the CloudFormation client, I get a well-formed exception with the list of valid CFN waiter names.  However, when I do the same to the SSM client, I don't get any waiter names back.

[This](https://github.com/aws/aws-sdk-ruby/issues/1185) issue may be relevant.  Perhaps this has been implemented for SSM in the latest v3 SDK (and not v2)?

Gem:  aws-sdk, 2.9.26.
Environment:  Ruby 2.4.1, Windows 10.

Code, run from irb:
```
require 'aws-sdk'
Aws.config.update({
    region: 'us-west-2',
    credentials: Aws::Credentials.new('AKIAid', 'secret')
})

cfn = Aws::CloudFormation::Client.new
cfn.wait_until(:bogus)

ssm = Aws::SSM::Client.new
ssm.wait_until(:bogus)
```

The respective exceptions:

CFN:
```
Aws::Waiters::Errors::NoSuchWaiterError: no such waiter :bogus; valid waiter names are: :stack_exists, :stack_create_complete, :stack_delete_complete, :stack_update_complete, :change_set_create_complete
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.9.26/lib/aws-sdk-core/waiters/provider.rb:29:in `waiter'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.9.26/lib/aws-sdk-core/client_waiters.rb:108:in `wait_until'
        from (irb):7
        from C:/tools/ruby24/bin/irb.cmd:19:in `<main>'
```

SSM:
```
Aws::Waiters::Errors::NoSuchWaiterError: no such waiter :bogus; valid waiter names are:
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.9.26/lib/aws-sdk-core/waiters/provider.rb:29:in `waiter'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.9.26/lib/aws-sdk-core/client_waiters.rb:108:in `wait_until'
        from (irb):9
        from C:/tools/ruby24/bin/irb.cmd:19:in `<main>'
```

**Comment by cjyclaire** [comment]
You are right, currently there is no waiter available for SSM, marking this as a feature request for adding waiters for SSM service.
