### ISSUE TITLE
Aws::S3::Client.get_object(): Failed to allocate memory (NoMemoryError)

### ISSUE THREAD

**Issue by adolski** [aws/aws-sdk-ruby#1703]
Hi,

I'm encountering a `NoMemoryError` when using the AWS S3 SDK in a Rails app. When a page is requested that uses the S3 client, the application hangs while consuming more and more memory until the error is triggered.

* Ruby 2.4.2
* Rails 5.1.4
* CentOS on an EC2 instance (5GB free memory at idle)
* Gemfile: `gem 'aws-sdk-s3', '~> 1'` (currently 1.8)

Here's how I'm using the client (this is what's appearing in the trace below):
```ruby
class Binary
  def read_size
    # This is a small object, only a few MB
    response = Aws::S3::Client.new.get_object(
        bucket: 'my-bucket',
        key: 'my-object-key')
    self.byte_size = response.content_length
  end
end
```
I'm using the Passenger standalone server, but have also tried Puma with the same result. Interestingly it only happens in a web server in a production environment. If I invoke the same method via `bin/rails console` in production, or any way in development, it works fine.

There is nothing interesting in the Rails log, but my `passenger.3000.log` contains a trace of the error:

```
[ W 2018-01-29 19:04:01.0203 6654/T7 age/Cor/Con/InternalUtils.cpp:96 ]: [Client 2-1] Sending 502 response: application did not send a complete response
App 6696 stderr: /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/http/response.rb:62:in `write': failed to allocate memory (NoMemoryError)
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/http/response.rb:62:in `signal_data'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/net_http/handler.rb:83:in `block (3 levels) in transmit'
App 6696 stderr: 	from /home/centos/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/protocol.rb:429:in `call_block'
App 6696 stderr: 	from /home/centos/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/protocol.rb:420:in `<<'
App 6696 stderr: 	from /home/centos/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/protocol.rb:122:in `read'
App 6696 stderr: 	from /home/centos/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http/response.rb:293:in `block in read_body_0'
App 6696 stderr: 	from /home/centos/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http/response.rb:253:in `inflater'
App 6696 stderr: 	from /home/centos/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http/response.rb:283:in `read_body_0'
App 6696 stderr: 	from /home/centos/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http/response.rb:204:in `read_body'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/net_http/handler.rb:81:in `block (2 levels) in transmit'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/net_http/patches.rb:39:in `block in new_transport_request'
App 6696 stderr: 	from /home/centos/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http/response.rb:165:in `reading_body'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/net_http/patches.rb:38:in `new_transport_request'
App 6696 stderr: 	from /home/centos/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http.rb:1416:in `request'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/net_http/connection_pool.rb:333:in `request'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/net_http/handler.rb:74:in `block in transmit'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/net_http/handler.rb:123:in `block in session'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/net_http/connection_pool.rb:99:in `session_for'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/net_http/handler.rb:121:in `session'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/net_http/handler.rb:73:in `transmit'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/net_http/handler.rb:47:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/plugins/content_length.rb:12:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/s3_signer.rb:109:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/s3_signer.rb:57:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/s3_host_id.rb:15:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/s3_signer.rb:87:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/redirects.rb:18:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/retry_errors.rb:92:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/dualstack.rb:34:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/accelerate.rb:50:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/md5s.rb:28:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/bucket_name_restrictions.rb:13:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/expect_100_continue.rb:22:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/bucket_dns.rb:33:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/rest/handler.rb:8:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/request.rb:70:in `send_request'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/client.rb:2661:in `get_object'
App 6696 stderr: 	from /home/centos/app-capistrano/releases/20180129182701/app/models/binary.rb:457:in `read_size'
App 6696 stderr: 	from /home/centos/app-capistrano/releases/20180129182701/app/models/collection.rb:573:in `representative_image_binary'
App 6696 stderr: 	from /home/centos/app-capistrano/releases/20180129182701/app/helpers/application_helper.rb:91:in `block in entities_as_cards'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/delegation.rb:39:in `each'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/delegation.rb:39:in `each'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/elasticsearch-model-5.0.1/lib/elasticsearch/model/respons
App 6696 stderr: e/records.rb:13:in `each'
App 6696 stderr: 	from /home/centos/app-capistrano/releases/20180129182701/app/helpers/application_helper.rb:84:in `entities_as_cards'
App 6696 stderr: 	from /home/centos/app-capistrano/releases/20180129182701/app/views/landing/index.html.erb:12:in `_app_views_landing_index_html_erb___483537752831094340_58883480'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/template.rb:157:in `block in render'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/template.rb:352:in `instrument_render_template'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/template.rb:155:in `render'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `block in instrument'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `instrument'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/renderer/template_renderer.rb:50:in `render_template'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/renderer/template_renderer.rb:14:in `render'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/renderer/renderer.rb:42:in `render_template'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/renderer/renderer.rb:23:in `render'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/rendering.rb:103:in `_render_template'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/streaming.rb:217:in `_render_template'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/rendering.rb:83:in `render_to_body'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/renderers.rb:141:in `render_to_body'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/abstract_controller/rendering.rb:24:in `render'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/rendering.rb:36:in `render'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
App 6696 stderr: 	from /home/centos/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/core_ext/benchmark.rb:12:in `ms'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:43:in `render'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/implicit_render.rb:33:in `default_render'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:186:in `process_action'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/rescue.rb:20:in `process_action'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `block in instrument'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `instrument'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:124:in `process'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/rendering.rb:30:in `process'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/live.rb:253:in `block (2 levels) in process'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:40:in `block in running'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share
App 6696 stderr: _lock.rb:160:in `sharing'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:39:in `running'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/live.rb:245:in `block in process'
App 6696 stderr: 	from /home/centos/app-capistrano/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/live.rb:289:in `block in new_controller_thread'
[ W 2018-01-29 19:04:05.0735 6654/Td age/Cor/App/Poo/AnalyticsCollection.cpp:102 ]: Process (pid=6716, group=/home/centos/user/public (production)) no longer exists! Detaching it from the pool.
[ N 2018-01-29 19:04:05.0735 6654/Td age/Cor/CoreMain.cpp:917 ]: Checking whether to disconnect long-running connections for process 6716, application /home/centos/user/public (production)

**Comment by awood45** [comment]
I'm curious what your usage pattern is for these objects. Are you getting this on your first request, or do you believe that these few-MB objects are just piling up and not being garbage collected to the point where you use up your process memory?

It's hard to determine from the information here if there's anything on the SDK end to do. It's especially interesting to see this be environment specific.

**Comment by adolski** [comment]
Sorry, this was my mistake. I didn't know that `get_object()` with no `:response_target` option downloaded an object into memory. I thought additional steps were required to do that (e.g. reading the `body` of the `GetObjectOutput`). What I needed was `head_object()`.
