### ISSUE TITLE
ec2 client describe_* failed at region 'cn-northwest-1'

### ISSUE THREAD

**Issue by zhangtiny123** [aws/aws-sdk-ruby#1706]
### Issue description
I use the  ```client``` of ```ec2``` module to fetch images , security_groups or other resources info by ```describe_images``` , ```describe_security_groups``` and something like this. It works well at all regions but ```cn-northwest-1```... 

The error stack:
```
Seahorse::Client::NetworkingError: Failed to open TCP connection to ec2.cn-northwest-1.amazonaws.com:443 (getaddrinfo: Name or service not known)
	from /usr/local/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
	from /usr/local/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	from /usr/local/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /usr/local/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /usr/local/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /usr/local/lib/ruby/2.3.0/net/http.rb:858:in `start'
	from /usr/local/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
	from /usr/local/bundle/gems/aws-sdk-core-2.1.11/lib/seahorse/client/net_http/connection_pool.rb:292:in `start_session'
	from /usr/local/bundle/gems/aws-sdk-core-2.1.11/lib/seahorse/client/net_http/connection_pool.rb:104:in `session_for'
	from /usr/local/bundle/gems/aws-sdk-core-2.1.11/lib/seahorse/client/net_http/handler.rb:108:in `session'
	from /usr/local/bundle/gems/aws-sdk-core-2.1.11/lib/seahorse/client/net_http/handler.rb:60:in `transmit'
	from /usr/local/bundle/gems/aws-sdk-core-2.1.11/lib/seahorse/client/net_http/handler.rb:34:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.1.11/lib/seahorse/client/plugins/content_length.rb:12:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.1.11/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.1.11/lib/aws-sdk-core/plugins/request_signer.rb:85:in `call'
... 14 levels...
	from /usr/local/bundle/gems/aws-sdk-core-2.1.11/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.1.11/lib/aws-sdk-core/plugins/param_converter.rb:21:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.1.11/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.1.11/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.1.11/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/bundle/gems/aws-sdk-core-2.1.11/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /app/app/models/ec_provider/aws_ecs_provider.rb:197:in `available_images'
	from /app/app/models/ecs_proxy.rb:16:in `method_missing'
	from (irb):10
	from /usr/local/bundle/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/bundle/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/bundle/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/bundle/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/bundle/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
```

The most strange thing is that I already set the region as ```cn-northwest-1```, but the describe method tries to connect to ```ec2.cn-northwest-1.amazonaws.com``` , this domain is not exist.

The region ```cn-north-1``` also located in China, but it works well ...

Is there something wrong with my usage please ?

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
```gem 'aws-sdk', '~> 2.1.8'```

### Version of Ruby, OS environment
```ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]```

### Code snippets / steps to reproduce
```
// some code to require Aws modules

credentials = Aws::Credentials.new('aws_key_id', 'aws_key_secret')
client = Aws::EC2::Client.new region: 'cn-northwest-1', credentials: credentials
client.describe_images {:owners => 'self'}
```

**Comment by awood45** [comment]
Try updating your version of the SDK, the latest versions will have that region's endpoint scheme.

If you do not wish to upgrade, you'll need to manually set the `:endpoint` of `ec2.cn-northwest-1.amazonaws.com.cn` as well as the region.
