### ISSUE TITLE
Insufficient error handling for dynamo responses

### ISSUE THREAD

**Issue by toaster** [aws/aws-sdk-ruby#1713]
Please fill out the sections below to help us address your issue

### Issue description

Sometimes the dynamos service returns an error in HTML format (like `<html><body><b>Http/1.1 Service Unavailable</b></body> </html>`).
We then get a JSON parsing exception like
```
JSON::ParserError: Empty input at line 1, column 1 [parse.c:926] in '<html><body><b>Http/1.1 Service Unavailable</b></body> </html>
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/json.rb:25 :in `load`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/json.rb:25 :in `load`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/json/error_handler.rb:17 :in `extract_error`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/xml/error_handler.rb:22 :in `error`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/json/error_handler.rb:9 :in `block in call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/seahorse/client/response.rb:45 :in `block in on`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/seahorse/client/http/response.rb:139 :in `block in on_success`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/seahorse/client/http/response.rb:166 :in `block in listener`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/seahorse/client/http/response.rb:130 :in `on_done`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/seahorse/client/http/response.rb:137 :in `on_success`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/seahorse/client/response.rb:44 :in `on`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/json/error_handler.rb:8 :in `call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/plugins/signature_v4.rb:66 :in `call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10 :in `call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/plugins/retry_errors.rb:92 :in `call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/json/handler.rb:11 :in `call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/plugins/user_agent.rb:13 :in `call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/seahorse/client/plugins/endpoint.rb:45 :in `call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/plugins/param_validator.rb:24 :in `call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/seahorse/client/plugins/raise_response_errors.rb:14 :in `call`
    [GEM_ROOT]/gems/aws-sdk-dynamodb-1.3.0/lib/aws-sdk-dynamodb/plugins/simple_attributes.rb:117 :in `call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20 :in `call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17 :in `call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/plugins/param_converter.rb:24 :in `call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/plugins/response_paging.rb:10 :in `call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/seahorse/client/plugins/response_target.rb:23 :in `call`
    [GEM_ROOT]/gems/aws-sdk-core-3.15.0/lib/seahorse/client/request.rb:70 :in `send_request`
    [GEM_ROOT]/gems/aws-sdk-dynamodb-1.3.0/lib/aws-sdk-dynamodb/client.rb:2315 :in `get_item`
    [GEM_ROOT]/gems/aws-sdk-dynamodb-1.3.0/lib/aws-sdk-dynamodb/table.rb:754 :in `get_item`
    …
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-dynamodb-1.3.0
aws-sdk-core-3.15.0

### Version of Ruby, OS environment

Ruby 2.4.2 on Alpine 3.7 in a docker container running on Amazon Linux 2017.09.

### Code snippets / steps to reproduce

Performing a `Aws::DynamoDB::Client#get_item` while the dynamo service returns HTML errors.

**Comment by awood45** [comment]
Just to check, but I think it's implied, is this an occasional/transient error? Is there a set of inputs which consistently produces this error?

**Comment by toaster** [comment]
This is an occasional error. The request runs fine several hundred times a day with the same input.

**Comment by awood45** [comment]
Thanks, this looks then like it's likely a service issue, so I'll be opening a report with them internally. Some things that could help, if able:

* If you can show me the inputs you're using, like a code snippet of what is causing this (feel free to remove any identifying info).

It will be difficult to try and get a request ID here, so I'll forward any questions the service team has back here.

**Comment by awood45** [comment]
The service team is repeating the request for your inputs. Can you share the call you're using that occasionally creates this error?

**Comment by toaster** [comment]
The error occurred while doing a simple `table.get_item` like
```
table = Aws::DynamoDB::Table.new(<our_table_name>)
table.get_item(key: {hash_key: "tenant", range_key: "<short_alnum_only_identifier>"}, consistent_read: true)
```

I agree that this is a service issue. But I reported here because I think it would be great if the SDK could handle unexpected service output better, e.g. with an own error including the full body and HTTP status.

**Comment by toaster** [comment]
And regarding `repeating the request`: We repeat this exact request many hundred times a day. We do this request with a different range key several thousand times a day. It works most of the time for years now.
The last time it didn't work was today (2018-02-20) at 5:35am UTC for two consecutive calls.
The table is in the eu-west-1 region.
It is accessed by a unicorn process in a docker container on a recent Amazon Linux. The auth stuff is done via IAM instance role.

Over a private channel I could share details on account, table and the item's keys.

**Comment by awood45** [comment]
Understood - it's a little difficult to determine what the "right" approach would be for handling a generic malformed response from the service, which is essentially what this is. We potentially could, for example, add `Aws::WHICHEVERSERVICE::Errors::ServiceError` to the ancestry of the JSON::ParserError we raise, but past that, there are other ways that a response can be malformed and distinguishing between those generically is a difficult problem. Even adding that error would at least require some plumbing, since not all cases of a malformed response are associated with service errors.

**Comment by awood45** [comment]
Given how rare this is (haven't seen this type of issue before for any service), I'm thinking the best path forward is still to get the service to behave properly.

**Comment by toaster** [comment]
From a client's view I at least would like to have the HTTP response code.
As it is now, I cannot see if it is a 5xx or a 4xx.

**Comment by pfleeter** [comment]
I saw these errors in my logs about an hour ago and checked the AWS status page, but everything is reported as nominal.  I'm using the .NET SDK and the call stack is below:

> System.AggregateException: One or more errors occurred. (Error unmarshalling response back from AWS. Response Body: <html><body><b>Http/1.1 Service Unavailable</b></body> </html>) ---> Amazon.Runtime.AmazonUnmarshallingException: Error unmarshalling response back from AWS. Response Body: <html><body><b>Http/1.1 Service Unavailable</b></body> </html> ---> System.Xml.XmlException: Root element is missing.
> at System.Xml.XmlTextReaderImpl.Throw(Exception e)
> at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
> at System.Xml.XmlTextReaderImpl.Read()
> at Amazon.Runtime.Internal.Transform.XmlUnmarshallerContext.Read()
> at Amazon.Runtime.Internal.Transform.ErrorResponseUnmarshaller.Unmarshall(XmlUnmarshallerContext context)
> at Amazon.Runtime.Internal.Transform.JsonErrorResponseUnmarshaller.Unmarshall(JsonUnmarshallerContext context)
> at Amazon.DynamoDBv2.Model.Internal.MarshallTransformations.GetItemResponseUnmarshaller.UnmarshallException(JsonUnmarshallerContext context, Exception innerException, HttpStatusCode statusCode)
> at Amazon.Runtime.Internal.Transform.JsonResponseUnmarshaller.UnmarshallException(UnmarshallerContext input, Exception innerException, HttpStatusCode statusCode)
> at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
> --- End of inner exception stack trace ---
> at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
> at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
> at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
> --- End of inner exception stack trace ---
> at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
> at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
> at System.Threading.Tasks.Task.Wait()
