### ISSUE TITLE
run_instances with tag_specifications field with resource_type: spot-instances-request not supported!

### ISSUE THREAD

**Issue by alexispetalas** [aws/aws-sdk-ruby#1718]
Hi, 

Calling Aws::EC2::Client  run_instances method with tag_specification resource type "spot-instances-request" 

stack the following:

```
[type:error] [error_type:Aws::EC2::Errors::InvalidParameterValue][message:"'spot-instances-request' is not a valid taggable resource type for this operation."] 
 /app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.125/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.125/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.125/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.125/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.125/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.125/lib/seahorse/client/request.rb:70:in `send_request'
	/app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.125/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
```

but in the [documentation](https://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html) the support type are: "accepts customer-gateway, dhcp-options, image, instance, internet-gateway, network-acl, network-interface, reserved-instances, route-table, snapshot, **spot-instances-request**, subnet, security-group, volume, vpc, vpn-connection, vpn-gateway".

aws-sdk-core (= 2.11.4)
ruby:2.3
ubuntu 16.04

example call:
```
client.run_instances(
        ...
        tag_specifications: [{
          resource_type: 'spot-instances-request',
          tags: {
                name: name
          }
        }],
        instance_market_options: {
          market_type: "spot",
          spot_options: {
            spot_instance_type: "one-time",
            instance_interruption_behavior: "terminate",
          },
        }
      )
```

**Comment by cjyclaire** [comment]
Apologies for the late response.

I reached out to service team about this, will wait for their comments.
Meanwhile, feel free to contact AWS support directly since this is an error emit from Server side. And AWS support can help open the conversation with service team directly.
