### ISSUE TITLE
failed to allocate memory - NoMemoryError - Installing aws-sdk gem using Chef and Packer

### ISSUE THREAD

**Issue by jtstrohl** [aws/aws-sdk-ruby#1768]
Please fill out the sections below to help us address your issue

### Issue description
I am using packer and chef to build a custom AMI on Windows 2012 R2.  We've been using this mechanism successfully for 2 years.  I made some minor changes to one of our recipes (not the recipe that is currently failing) and wanted to create a new AMI containing those changes.  All of the sudden, my recipe is failing on the part that installs the aws-sdk gem, with a NoMemoryError error:
```
2018/04/24 15:58:02 packer: 2018/04/24 15:58:02 [INFO] command 'c:/opscode/chef/bin/chef-client.bat --no-color -c c:/chef/client.rb -E packer -j C:/Windows/Temp/packer-chef-client/first-boot.json' exited with code: 1
2018/04/24 15:58:02 packer: 2018/04/24 15:58:02 [INFO] RPC endpoint: Communicator ended with: 1
2018/04/24 15:58:02 [INFO] 0 bytes written for 'stderr'
2018/04/24 15:58:02 [INFO] 12871 bytes written for 'stdout'
2018/04/24 15:58:02 [INFO] RPC client: Communicator ended with: 1
2018/04/24 15:58:02 [INFO] RPC endpoint: Communicator ended with: 1
2018/04/24 15:58:02 packer: 2018/04/24 15:58:02 [INFO] 0 bytes written for 'stderr'
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs: ================================================================================[0m
[0;32m    amazon-ebs: ================================================================================[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs: Error executing action `install` on resource 'chef_gem[aws-sdk]'[0m
[0;32m    amazon-ebs: Error executing action `install` on resource 'chef_gem[aws-sdk]'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs: ================================================================================[0m
[0;32m    amazon-ebs: ================================================================================[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:[0m
[0;32m    amazon-ebs:[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs: Mixlib::ShellOut::ShellCommandFailed[0m
[0;32m    amazon-ebs: Mixlib::ShellOut::ShellCommandFailed[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs: ------------------------------------[0m
[0;32m    amazon-ebs: ------------------------------------[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs: Expected process to exit with [0], but received '1'[0m
[0;32m    amazon-ebs: Expected process to exit with [0], but received '1'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs: ---- Begin output of c:/opscode/chef/embedded/bin/gem install aws-sdk -q --no-rdoc --no-ri -v "3.0.1" ----[0m
[0;32m    amazon-ebs: ---- Begin output of c:/opscode/chef/embedded/bin/gem install aws-sdk -q --no-rdoc --no-ri -v "3.0.1" ----[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs: STDOUT:[0m
[0;32m    amazon-ebs: STDOUT:[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs: STDERR: c:/opscode/chef/embedded/lib/ruby/2.3.0/net/http.rb:1482:in `wait_readable': failed to allocate memory (NoMemoryError)[0m
[0;32m    amazon-ebs: STDERR: c:/opscode/chef/embedded/lib/ruby/2.3.0/net/http.rb:1482:in `wait_readable': failed to allocate memory (NoMemoryError)[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/2.3.0/net/http.rb:1482:in `begin_transport'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/2.3.0/net/http.rb:1433:in `transport_request'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/2.3.0/net/http.rb:1407:in `request'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/request.rb:221:in `perform_request'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/request.rb:156:in `fetch'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/remote_fetcher.rb:368:in `request'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/remote_fetcher.rb:251:in `fetch_http'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/remote_fetcher.rb:292:in `fetch_path'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/source.rb:153:in `fetch_spec'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/index_specification.rb:65:in `spec'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/specification.rb:104:in `installable_platform?'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/platform.rb:35:in `installable?'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:224:in `block in select_local_platforms'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:223:in `select'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:223:in `select_local_platforms'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:214:in `find_possible'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:229:in `search_for'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:10:in `block in search_for'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:9:in `search_for'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:449:in `push_state_for_requirements'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:438:in `require_nested_dependencies_for'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:422:in `activate_spec'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:388:in `attempt_to_activate_new_spec'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/2.3.0/net/http.rb:1482:in `begin_transport'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/2.3.0/net/http.rb:1433:in `transport_request'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/2.3.0/net/http.rb:1407:in `request'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/request.rb:221:in `perform_request'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/request.rb:156:in `fetch'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/remote_fetcher.rb:368:in `request'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/remote_fetcher.rb:251:in `fetch_http'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/remote_fetcher.rb:292:in `fetch_path'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/source.rb:153:in `fetch_spec'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/index_specification.rb:65:in `spec'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/specification.rb:104:in `installable_platform?'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/platform.rb:35:in `installable?'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:224:in `block in select_local_platforms'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:223:in `select'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:223:in `select_local_platforms'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:214:in `find_possible'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:229:in `search_for'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:10:in `block in search_for'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:9:in `search_for'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:449:in `push_state_for_requirements'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:438:in `require_nested_dependencies_for'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:422:in `activate_spec'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:388:in `attempt_to_activate_new_spec'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:319:in `attempt_to_activate'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:319:in `attempt_to_activate'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:137:in `process_topmost_state'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:137:in `process_topmost_state'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:78:in `resolve'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:191:in `resolve'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/request_set.rb:368:in `resolve'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency_installer.rb:484:in `resolve_dependencies'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:194:in `install_gem'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:78:in `resolve'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:191:in `resolve'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/request_set.rb:368:in `resolve'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency_installer.rb:484:in `resolve_dependencies'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:194:in `install_gem'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:255:in `block in install_gems'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:255:in `block in install_gems'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:251:in `each'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:251:in `each'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:251:in `install_gems'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:251:in `install_gems'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:158:in `execute'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:158:in `execute'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/command.rb:310:in `invoke_with_build_args'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/command.rb:310:in `invoke_with_build_args'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/command_manager.rb:139:in `run'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/command_manager.rb:139:in `run'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs:  from c:/opscode/chef/embedded/bin/gem:21:in `<main>'[0m
[0;32m    amazon-ebs:  from c:/opscode/chef/embedded/bin/gem:21:in `<main>'[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs: ---- End output of c:/opscode/chef/embedded/bin/gem install aws-sdk -q --no-rdoc --no-ri -v "3.0.1" ----[0m
[0;32m    amazon-ebs: ---- End output of c:/opscode/chef/embedded/bin/gem install aws-sdk -q --no-rdoc --no-ri -v "3.0.1" ----[0m
2018/04/24 15:58:02 ui: [0;32m    amazon-ebs: Ran c:/opscode/chef/embedded/bin/gem install aws-sdk -q --no-rdoc --no-ri -v "3.0.1" returned 1[0m
[0;32m    amazon-ebs: Ran c:/opscode/chef/embedded/bin/gem install aws-sdk -q --no-rdoc --no-ri -v "3.0.1" returned 1
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk version 3.0.1

### Version of Ruby, OS environment
Ruby 2.3.0, Windows 2012 R2

**Comment by jtstrohl** [comment]
Figured out the problem.  WinRM has it's own memory cap.  I realized that we had hard-coded the WinRM MaxMemoryPerShellMB parameter to 1024MB (apparently too restrictive) in the powershell script we used to set up WinRM for Packer remote execution (See example here: http://blog.petegoo.com/2016/05/10/packer-aws-windows/).  Once we increased from 1024 to 4096 MB in the WinRM bootstrap script, it started working.
