### ISSUE TITLE
 cannot load such file -- aws-partitions

### ISSUE THREAD

**Issue by NoSkillGuy** [aws/aws-sdk-ruby#1769]
### Issue description
`aws-partitions` is not loaded when loading `rails`

`carrierwave-aws` requires `aws-sdk-s3`
`aws-sdk-s3` requires `aws-sdk-kms`
`aws-sdk-kms` requires `aws-sdk-core`
`aws-sdk-core` requires `aws-partitions`, which is not loaded.

```ruby
bin/rails c
Traceback (most recent call last):
  28: from bin/rails:4:in `<main>'
  27: from bin/rails:4:in `require'
  26: from my_app/shared/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
  25: from my_app/shared/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
  24: from my_app/shared/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
  23: from my_app/shared/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  22: from my_app/shared/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  21: from my_app/shared/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  20: from my_app/shared/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/commands/console/console_command.rb:96:in `perform'
  19: from my_app/shared/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
  18: from my_app/shared/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/command/actions.rb:15:in `require'
  17: from my_app/shared/s/20180424170145/config/application.rb:7:in `<top (required)>'
  16: from /var/lib/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
  15: from /var/lib/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
  14: from /var/lib/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
  13: from /var/lib/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
  12: from /var/lib/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
  11: from /var/lib/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
  10: from /var/lib/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
   9: from my_app/shared/bundle/ruby/2.5.0/gems/carrierwave-aws-1.3.0/lib/carrierwave-aws.rb:5:in `<top (required)>'
   8: from my_app/shared/bundle/ruby/2.5.0/gems/carrierwave-aws-1.3.0/lib/carrierwave-aws.rb:5:in `require'
   7: from my_app/shared/bundle/ruby/2.5.0/gems/carrierwave-aws-1.3.0/lib/carrierwave/storage/aws.rb:3:in `<top (required)>'
   6: from my_app/shared/bundle/ruby/2.5.0/gems/carrierwave-aws-1.3.0/lib/carrierwave/storage/aws.rb:3:in `require'
   5: from my_app/shared/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.8.2/lib/aws-sdk-s3.rb:8:in `<top (required)>'
   4: from my_app/shared/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.8.2/lib/aws-sdk-s3.rb:8:in `require'
   3: from my_app/shared/bundle/ruby/2.5.0/gems/aws-sdk-kms-1.5.0/lib/aws-sdk-kms.rb:8:in `<top (required)>'
   2: from my_app/shared/bundle/ruby/2.5.0/gems/aws-sdk-kms-1.5.0/lib/aws-sdk-kms.rb:8:in `require'
   1: from my_app/shared/bundle/ruby/2.5.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core.rb:1:in `<top (required)>'
my_app/shared/bundle/ruby/2.5.0/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core.rb:1:in `require': cannot load such file -- aws-partitions (LoadError)
```
However in `irb`

```ruby
irb(main):001:0> require 'aws-partitions'
=> true
irb(main):002:0> require 'carrierwave-aws'
=> true
```
In gems.locked 
```ruby
    aws-partitions (1.70.0)
    aws-sdk-core (3.17.0)
    aws-sdk-kms (1.5.0)
      aws-sdk-core (~> 3)
      aws-sigv4 (~> 1.0)
    aws-sdk-s3 (1.8.2)
      aws-sdk-core (~> 3)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.0)
    aws-sigv4 (1.0.2)
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
'aws-partitions' 1.70.0
### Version of Ruby, OS environment
Ruby - 2.5.0 
Ubuntu - 16.04

**Comment by awood45** [comment]
Just to check, is this still an issue? If so, I'd like to see your Gemfile specifically, and how the AWS SDK is being loaded in your Rails app.

**Comment by cjyclaire** [comment]
Closing due to inactivity, feel free to reopen if the issue persist and you can provide further info, :D

**Comment by ulisescarreonalvarez** [comment]
I have the same problem on ruby 2.5.1

My Gemfile is:

```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.3'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby
gem 'devise'
gem 'rest-client'
gem 'pg'
gem 'aws-partitions', '~> 1.70.0'
gem 'aws-sdk', '~> 3'
gem 'command'
gem 'pdf-forms'
gem 'fileutils'
gem 'chilkat', '9.5.0.76'
gem 'bootstrap', '~> 4.2.1'
gem 'jquery-rails'
gem 'ejs'
gem 'bootstrap-sass', '~> 3.4.0'
gem 'sassc-rails', '>= 2.0.0'
gem 'rest-client'
gem 'active_model_otp'
gem 'rqrcode'
gem 'rotp'
gem 'simple_form'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'wkhtmltopdf-binary-edge'
gem 'prawn'
gem 'recaptcha', git: "https://github.com/ambethia/recaptcha.git"
gem 'bullet'
gem 'ruby-growl'
gem 'paper_trail'
gem 'paper_trail-association_tracking'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

And my error is:

**Could not spawn process for application /var/www/merci-admin: The application encountered the following error: Could not find aws-partitions-1.70.0 in any of the sources (Bundler::GemNotFound)**
