### ISSUE TITLE
How to handle AWS::SQS::Errors::InternalError when polling a queue?

### ISSUE THREAD

**Issue by luccasmaso** [aws/aws-sdk-ruby#185]
Sometimes my poll fails because aws throws 500 internal error. So my code will have to handle this and keep retrying.

Inside my poll block, I already have a rescue for any exception, but the script stopped and exited when AWS returned a server internal error. 

What should I do?  Thanksss

Script:

```
    queue = AWS::SQS::Queue.new(my_queue)
    queue.poll do |msg|
      begin
        log "Receiving message from queue #{msg.body}"
        received_message = parse_message(msg.body)

        rescue Exception => e
          exception = e.message
          log "Exception: #{exception}"
        end
    end

```

The exception:

```
/var/lib/gems/1.9.1/gems/aws-sdk-1.6.6/lib/aws/core/client.rb:318:in `return_or_raise': We encountered an internal error. Please try again. (AWS::SQS::Errors::InternalError)
    from /var/lib/gems/1.9.1/gems/aws-sdk-1.6.6/lib/aws/core/client.rb:419:in `client_request'
    from (eval):3:in `receive_message'
    from /var/lib/gems/1.9.1/gems/aws-sdk-1.6.6/lib/aws/sqs/queue.rb:173:in `receive_message'
    from /var/lib/gems/1.9.1/gems/aws-sdk-1.6.6/lib/aws/sqs/queue.rb:260:in `block in poll'
    from /var/lib/gems/1.9.1/gems/aws-sdk-1.6.6/lib/aws/sqs/queue.rb:258:in `loop'
    from /var/lib/gems/1.9.1/gems/aws-sdk-1.6.6/lib/aws/sqs/queue.rb:258:in `poll'
    from /home/ubuntu/exorcist/listen_incoming.rb:6:in `listen_incoming'
    from /home/ubuntu/exorcist/document_converter.rb:173:in `block in <main>'
    from /home/ubuntu/exorcist/document_converter.rb:173:in `fork'
    from /home/ubuntu/exorcist/document_converter.rb:173:in `<main>'
```

**Comment by trevorrowe** [comment]
@luccasmaso I've recently pushed a branch for the v2 SDK that has a significantly updated SQS polling abstraction. I would be interested if you could take a look at this and provide any feedback you might have before this makes it into the public SDK.

https://github.com/aws/aws-sdk-ruby/pull/740
