### ISSUE TITLE
SQS client ArgumentError: invalid :priority `nil', must be between 0 and 99

### ISSUE THREAD

**Issue by vbalazs** [aws/aws-sdk-ruby#1861]
### Issue description

Occasionally we receive an error into our Sentry which comes from `aws-sdk-core`. I checked it briefly and nor we, nor `shoryuken`, nor `aws-sdk-sqs` gems are manipulating this `priority` value. Not sure what edge case we hit, I could not find any similar closed or open issue. Since we use shoryuken in a multi-threaded environment, it can be a race condition but this is just a wild guess.

<details>
<summary>Stacktrace</summary>
```
ArgumentError: invalid :priority `nil', must be between 0 and 99
  from seahorse/client/handler_list_entry.rb:81:in `option'
  from seahorse/client/handler_list_entry.rb:29:in `initialize'
  from seahorse/client/handler_list_entry.rb:71:in `new'
  from seahorse/client/handler_list_entry.rb:71:in `copy'
  from seahorse/client/handler_list.rb:179:in `block in filter'
  from seahorse/client/handler_list.rb:177:in `each'
  from seahorse/client/handler_list.rb:177:in `inject'
  from seahorse/client/handler_list.rb:177:in `filter'
  from seahorse/client/handler_list.rb:145:in `for'
  from aws-sdk-sqs/client.rb:2063:in `build_request'
  from aws-sdk-sqs/client.rb:1677:in `send_message'
  from shoryuken/queue.rb:34:in `block in send_message'
  from shoryuken/middleware/chain.rb:98:in `block in invoke'
  from shoryuken/middleware/chain.rb:103:in `invoke'
  from shoryuken/queue.rb:33:in `send_message'
  from shoryuken/worker/default_executor.rb:16:in `perform_async'
  from shoryuken/worker.rb:10:in `perform_async'
  from shoryuken/worker/default_executor.rb:28:in `perform_in'
  from shoryuken/worker.rb:14:in `perform_in'
  from app/workers/events_worker.rb:16:in `queue_up'
```
</details>

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

- `aws-sdk-core`
- `aws-sdk-sqs`

### Version of Ruby, OS environment

- ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
- Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-1050-aws x86_64)

### Code snippets / steps to reproduce

I cannot reproduce it but it happens several times a week.

**Comment by cjyclaire** [comment]
Hmmm I'm guessing at multithread envs, [here](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/seahorse/client/handler_list.rb#L106) might bring in some transit issue that make `:handler_class` is not set when passed to `HandlerListEntry`, which cause the error to raise up. 

I'll try to reproduce the issue first.

**Comment by srchase** [comment]
@vbalazs 

What version of Shoryuken are you using?

Do you ever get this error where Shoryuken is not used?

**Comment by vbalazs** [comment]
What version of Shoryuken are you using?

@srchase sorry, I forgot to share that detail, we are using the latest one, `3.2.3`

> Do you ever get this error where Shoryuken is not used?

so far no, only experiencing the issue within the worker, looks like this:

```ruby
class EventsWorker
  include Shoryuken::Worker

  shoryuken_options queue: "production_events", body_parser: :json

  DEFAULT_SHORT_DELAY = 1.second

  def self.queue_up(data)
    data[:data] = Oj.dump(data[:data]) if data[:data].is_a?(Hash)
    perform_in(DEFAULT_SHORT_DELAY, data.merge(action: :process))
  end

  def perform(sqs_msg, data)
    case data.delete("action")
    # when ".." ....
    when "process"
      _process(data)
    end
    sqs_msg.delete
  end

  def _process(event_data)
    # ... heavy db operations, 3rd party service connection, etc
  end
end
```

We use the following shoryuken configuration in production:
```
concurrency: 25
delay: 10
```

Let me know if you need more information.

**Comment by srchase** [comment]
@vbalazs 

Have you continued to see this error?  I've spent a bit of time trying to reproduce the issue, but have not had any luck.

Has anything happened recently that would help me understand what specifically is causing this issue?

Thanks!

**Comment by zeroed** [comment]
Hi everyone,

I would like to reopen this issue and I hope to being able to add some
useful detail here because I'm debugging the same error with the S3
service; I have many occurrencies of this error with a very similar
stacktrace.

### Error

```
ArgumentError:
  invalid :priority `nil', must be between 0 and 99.
```

### Stacktrace

```
ArgumentError: invalid :priority `nil', must be between 0 and 99
  from seahorse/client/handler_list_entry.rb:81:in `option'
  from seahorse/client/handler_list_entry.rb:28:in `initialize'
  from seahorse/client/handler_list_entry.rb:71:in `new'
  from seahorse/client/handler_list_entry.rb:71:in `copy'

  from seahorse/client/handler_list.rb:179:in `block in filter'
  from seahorse/client/handler_list.rb:177:in `each'
  from seahorse/client/handler_list.rb:177:in `inject'
  from seahorse/client/handler_list.rb:177:in `filter'
  from seahorse/client/handler_list.rb:145:in `for'

  from seahorse/client/base.rb:36:in `build_request'
  from seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
```

### Gem Name

```
aws-sdk (2.10.24)
aws-sdk-resources (2.10.24)
aws-sdk-core (2.10.24)
```

### Ruby and OS version

```
{
  os: {
    build: 4.9.76-3.78.amzn1.x86_64, 
    kernel_version: Linux befc5c8ca460 4.9.76-3.78.amzn1.x86_64 #1 SMP Fri Jan 12 19:51:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux, 
    name: Linux, 
  }, 
  runtime: {
    name: ruby, 
    version: ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
  }
}
```

Following the stacktrace, unfortunately it seems that the error message
is a bit misleading:

[handler_list_entry.rb#L76-L83](https://github.com/aws/aws-sdk-ruby/blob/v2.10.24/aws-sdk-core/lib/seahorse/client/handler_list_entry.rb#L76-L83)

```ruby
      def option(name, options)
        if options.key?(name)
          options[name]
        else
          msg = "invalid :priority `%s', must be between 0 and 99"
          raise ArgumentError, msg % priority.inspect
        end
      end
```

where it refers to the `invalid :priority`, it's actually complaining
about a missing `@handler_class = option(:handler_class, options)` in the 
initialisation of the `Seahorse::Client`:

[handler_list_entry.rb#L28](https://github.com/aws/aws-sdk-ruby/blob/v2.10.24/aws-sdk-core/lib/seahorse/client/handler_list_entry.rb#L28)

```ruby
@handler_class = option(:handler_class, options)
```

I'm using the `Aws::S3::Client` in a fairly straightforward way.

Any tips/hints to debug deeper? Thanks in advance.

**Comment by zeroed** [comment]
_very humbly and politely PINGing @srchase (thank you in advance)_

**Comment by cjyclaire** [comment]
@zeroed Quick follow up question, are you also using SDK with `shoryuken` or some other gems? Are you able to reproduce the issue with SDK only? If so, could you share the code snippet that can reproduce the issue for you?

**Comment by zeroed** [comment]
Hey @cjyclaire, thanks for your message.

While the first question is easy (nope, we are not using `shoryuken`) the second is not _that_ simple; I have just a wrapper around few `Aws::S3::Client` calls (`put_object`, `delete_object` and `copy_object`) but I need to work a bit more to distill a minimal example from the business logic to consistently reproduce the error.

I'll try to do that as soon as possible; in the meantime, if there is some known workaround (or hint) it will be appreciated (`^_^`).

**Comment by cjyclaire** [comment]
@zeroed Sure, thanks! As I cannot reproduce locally with regular S3 usage (or in current SDK test suits), we are interested to see your environment(multi-threading?) or your use case to see of I can reproduce the issue
