### ISSUE TITLE
SQS receive_message failing with xml parsing error

### ISSUE THREAD

**Issue by jemmyw** [aws/aws-sdk-ruby#1870]
Please fill out the sections below to help us address your issue

### Issue description

XML parsing error when calling receive_message but only sometimes.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core
aws-sdk-sqs

### Version of Ruby, OS environment

Ruby 2.4, official docker version on ECS

### Code snippets / steps to reproduce

Message contents:
```
{&quot;response_id&quot;:428455}
```

Error:

Aws::Xml::Parser::ParsingError
Extra content at the end of the document

Backtrace:

```
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/aws-sdk-core/xml/parser/stack.rb:45:in `error'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/aws-sdk-core/xml/parser/engines/nokogiri.rb:39:in `error'"
 "/app/.bundle/gems/ruby/2.4.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/sax/parser.rb:110:in `parse_with'"
 "/app/.bundle/gems/ruby/2.4.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/sax/parser.rb:110:in `parse_memory'"
 "/app/.bundle/gems/ruby/2.4.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/sax/parser.rb:83:in `parse'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/aws-sdk-core/xml/parser/engines/nokogiri.rb:13:in `parse'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/aws-sdk-core/xml/parser.rb:34:in `parse'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/aws-sdk-core/query/handler.rb:53:in `parse_xml'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/aws-sdk-core/query/handler.rb:30:in `block in call'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/seahorse/client/response.rb:45:in `block in on'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/seahorse/client/http/response.rb:139:in `block in on_success'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/seahorse/client/http/response.rb:166:in `block in listener'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/seahorse/client/http/response.rb:130:in `on_done'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/seahorse/client/http/response.rb:137:in `on_success'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/seahorse/client/response.rb:44:in `on'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/seahorse/client/response.rb:53:in `on_success'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/aws-sdk-core/query/handler.rb:28:in `call'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/seahorse/client/plugins/endpoint.rb:45:in `call'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-xray-sdk-0.10.2/lib/aws-xray-sdk/facets/aws_sdk.rb:31:in `block in call'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-xray-sdk-0.10.2/lib/aws-xray-sdk/recorder.rb:120:in `capture'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-xray-sdk-0.10.2/lib/aws-xray-sdk/facets/aws_sdk.rb:28:in `call'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/seahorse/client/plugins/response_target.rb:23:in `call'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.24.1/lib/seahorse/client/request.rb:70:in `send_request'"
 "/app/.bundle/gems/ruby/2.4.0/gems/aws-sdk-sqs-1.4.0/lib/aws-sdk-sqs/client.rb:1456:in `receive_message'"
```

**Comment by jemmyw** [comment]
I put a trace in Aws::Query::Handler#parse_xml and the xml it is passing on to get parsed does indeed look corrupted:

```
<?xml version="1.0"?>
<ReceiveMessageResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
  <ReceiveMessageResult/>
  <ResponseMetadata>
  <RequestId>6dc5f341-60f4-5633-a086-a744f1bfd211</RequestId>
  </ResponseMetadata>
  </ReceiveMessageResponse>
R3mlSuIll7xSXzbbuYkLsmFSa/x2RyKv+m3w5dytEXHbbZ4gbIf+WIaz6yskq2R2IkQFIzSSp4yl3bQsOjvVNuL6N7lZxE56ksDiPgKB8VlY1EmwiejoyztkHYhFq4qKD65gwJSpxLMjXWywIY4wQ4n3c4E6DIWGD2Wh9+wlMXzmh+Cb3WkmdvhlKzcQcz4pABg8LVOFGkEcDz/998Px4KufcqN/dHLuD6j1ushB4kpqFkPVJGFu78+JDBVvNLwtRdDCCuyVO2MTPUviit+ijOQunX4BO5+NLcpliMH1a37WYQ2RXF1yQA7XqucHrOxQ/wpomUztqexRpWopyEo++lCEnF4L1+VktFRK4HwYoNttqOhGN1JDnoOAnCt935+TmDEdhY7Y=</ReceiptHandle>
<MD5OfBody>6b6914ef16eb16c397db1b2395ba4836</MD5OfBody>
<MD5OfMessageAttributes>98375091b2eb5cb729b45eb0ff7104e4</MD5OfMessageAttributes>
<Body>{&quot;response_id&quot;:428455}</Body>
<Attribute><Name>SenderId</Name><Value>AROAIFG2WFJF2EOK2CAN4:e9555382-abb4-40f5-aea5-ecd393ca9151</Value></Attribute>
<Attribute><Name>ApproximateFirstReceiveTimestamp</Name><Value>1535872479743</Value></Attribute>
<Attribute><Name>ApproximateReceiveCount</Name><Value>2</Value></Attribute>
<Attribute><Name>SentTimestamp</Name><Value>1535872479736</Value></Attribute>
<MessageAttribute><Name>shoryuken_class</Name><Value><StringValue>LoadResponseCampaignData</StringValue><DataType>String</DataType></Value></MessageAttribute>
<MessageAttribute><Name>trace_id</Name><Value><StringValue>1-5b8b8ddf-32759796d9ceb2905b210b98</StringValue><DataType>String</DataType></Value></MessageAttribute>
</Message>
</ReceiveMessageResult>
<ResponseMetadata>
<RequestId>dd6d4b2c-e3d8-56b5-8004-1f2972e53d26</RequestId>
</ResponseMetadata>
</ReceiveMessageResponse>
```

**Comment by srchase** [comment]
@jemmyw 

Are there any other details you can provide that might help us narrow down what is causing this to happen?

Is the xml always malformed in the same spot?

**Comment by jemmyw** [comment]
Hi, it looks like it. Here is a second example that I collected:

```
<?xml version="1.0"?>
<ReceiveMessageResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
<ReceiveMessageResult/>
<ResponseMetadata>
<RequestId>
9f08d265-0b58-5486-a2de-866f9d529f77</RequestId>
</ResponseMetadata>
</ReceiveMessageResponse>
8lZbowRVFBN96GWFllu9iJ8odbck23rd1X5P6+PFOBtLIuNvBFhif8k4heYk0cKor8FLIf1GDPIMK2JrOWtZT1gNoo/uqma1rTEoFdlGeyjTNEcZiVTzdVxt+vWfvrtvh7oEIEC6JVpm9XNists7kpoiJUD6kzVXIlTK0AjIOREP2ojreyDXFJ2kn7dWf47ndKXgecAR0ZOhoFix3uZ/G1Z7JV8MIdHoIf2HKVKpVWOHcfcgnSv76CjrjjMOk/LbwS4p+MSKIw3mYsz2YWr+drfwLHrLXdpsGo5su3LHZs4LiMjzND/UEtDeL/WKhDT4FRhO+mqSf7EiqGJQVnQSw5sRwd0v369qMSr0M+E10hzu0mpxudg==</ReceiptHandle>
<MD5OfBody>
f0fcfdae9a6585cff532263197b72fdb</MD5OfBody>
<MD5OfMessageAttributes>
a992083f4729a2c0164ac19f7cebfc35</MD5OfMessageAttributes>
<Body>
{&quot;record_import_id&quot;:626}</Body>
<Attribute>
<Name>
SenderId</Name>
<Value>
AROAIFG2WFJF2EOK2CAN4:fcabd2d6-7ad3-48e6-a4ac-9c1011fd1959</Value>
</Attribute>
<Attribute>
<Name>
ApproximateFirstReceiveTimestamp</Name>
<Value>
1536201674087</Value>
</Attribute>
<Attribute>
<Name>
ApproximateReceiveCount</Name>
<Value>
1</Value>
</Attribute>
<Attribute>
<Name>
SentTimestamp</Name>
<Value>
1536201674067</Value>
</Attribute>
<MessageAttribute>
<Name>
shoryuken_class</Name>
<Value>
<StringValue>
ImportRecords</StringValue>
<DataType>
String</DataType>
</Value>
</MessageAttribute>
<MessageAttribute>
<Name>
trace_id</Name>
<Value>
<StringValue>
1-5b9093c9-a1ab8e6c1e1d65a6df82ec8a</StringValue>
<DataType>
String</DataType>
</Value>
</MessageAttribute>
</Message>
</ReceiveMessageResult>
<ResponseMetadata>
<RequestId>
7990238a-7876-5d61-8593-7780ed8de711</RequestId>
</ResponseMetadata>
</ReceiveMessageResponse>
```

Compare with the next pickup which worked correctly:

```

**Comment by jemmyw** [comment]
Hi,

I put a trace on Seahorse::Client::Http::Response#signal_data and here I start seeing something more interesting. The data going through that method looks like this:

```
<?xml version=\"1.0\"?><ReceiveMessageResponse xmlns=\"http://queue.amazonaws.com/doc/2012-11-05/\"><ReceiveMessageResult/><ResponseMetadata><RequestId>144e51a4-20dc-5bda-8c5f-05a841ed728e</RequestId></ResponseMetadata></ReceiveMessageResponse>
```

And then parse_xml gets this:

```
<?xml version=\"1.0\"?><ReceiveMessageResponse xmlns=\"http://queue.amazonaws.com/doc/2012-11-05/\"><ReceiveMessageResult/><ResponseMetadata><RequestId>144e51a4-20dc-5bda-8c5f-05a841ed728e</RequestId></ResponseMetadata></ReceiveMessageResponse>UFU/X5mM5/WCw0y5AQ/bDPxp6moq/gBd1rurIvNKOXYz/BKsUk7vBa82CjVgg6TfCZmuqHWQD7aXpXAQOvkMk8BUWEHr5+YLo6T80MHdiClno38mVr01jjEQZniuwtHfQEkLFJUZMewMZ2yPmkp2V6283D6QKA0tFJ6lBTJsjWL+JHBOYoKqocLTiY6b4nuqslqm6fAEnw+Uv0tpSTxklZYY7uK1S69XOT7Trh6YP6d3qyTjcl7YZ0zgkWfZtH1Ei3UBnDfvrH77sqpAeFxeqIze/x9e0YM6NCKmxVIHqIUOlMHFY7IB/uS/yXTuhRfKvepZpL8wniawvS7KbwxvsjBye0clSjTs7GmJcAgEoMRwgfS7PoA==</ReceiptHandle><MD5OfBody>3ef3a34c1e1bae7c6e67bf4473ecc4ce</MD5OfBody><MD5OfMessageAttributes>717f4cd2c0d7a6ad97c7bc924b8763e4</MD5OfMessageAttributes><Body>{&quot;record_import_id&quot;:659}</Body><Attribute><Name>SenderId</Name><Value>AROAIFG2WFJF2EOK2CAN4:d8373589-c19d-48a0-b34b-dc10466a6be5</Value></Attribute><Attribute><Name>ApproximateFirstReceiveTimestamp</Name><Value>1536319217194</Value></Attribute><Attribute><Name>ApproximateReceiveCount</Name><Value>1</Value></Attribute><Attribute><Name>SentTimestamp</Name><Value>1536319217183</Value></Attribute><MessageAttribute><Name>shoryuken_class</Name><Value><StringValue>ImportRecords</StringValue><DataType>String</DataType></Value></MessageAttribute><MessageAttribute><Name>trace_id</Name><Value><StringValue>1-5b925ef1-d2e540d0cf3d28547236384a</StringValue><DataType>String</DataType></Value></MessageAttribute></Message></ReceiveMessageResult><ResponseMetadata><RequestId>db3dc3ed-b57e-5352-8f01-97e1d451ca06</RequestId></ResponseMetadata></ReceiveMessageResponse>
```

Note they have the same RequestId at the beginning, and then another RequestId in parse_xml. 

I can then trace that other RequestId and find signal_data was called with the correct XML another time.

So it seems like 2 requests are stomping on each other. This is running under shoyuken which is multithreaded, but with concurrency set to 1 so there should only be 1 thread performing these calls.

**Comment by mullermp** [comment]
Are you still seeing this issue? Are you able to reproduce this issue without shoryuken?
