### ISSUE TITLE
#copy_object is returning false negative exception Aws::S3::Errors::NoSuchKey

### ISSUE THREAD

**Issue by waldyr** [aws/aws-sdk-ruby#1916]
### Issue description
I'm using `#copy_object` for a existent object and it's returning `Aws::S3::Errors::NoSuchKey`. The problem might reside in the object's name because it has a really crazy name:

`VS+RS+200ml+0965068+++0965058+#+902217800,+102306682+Deutsche+SiSi`.

Checkout the steps down below.

I would be glad if you could point me out a solution or where to look for it in this gem. Feel free to ping me for more info.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

Mainly S3. But here is the stuff being used.
```
    aws-sdk (2.10.30)
      aws-sdk-resources (= 2.10.30)
    aws-sdk-core (2.10.30)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-resources (2.10.30)
      aws-sdk-core (= 2.10.30)
    aws-sigv4 (1.0.1)
```

### Version of Ruby, OS environment
```
ruby 2.4.1p111

Darwin MacBook-Pro.fritz.box 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct 5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

Darwin mac.fritz.box 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

### Code snippets / steps to reproduce
Check if the file is in S3:
```
irb(main):075:0> S3_CLIENT.head_object(bucket: S3_BUCKET.name, key: s3_key)
=> #<struct Aws::S3::Types::HeadObjectOutput delete_marker=nil, accept_ranges="bytes", expiration=nil, restore=nil, last_modified=2018-11-13 15:17:54 +0000, content_length=48327, etag="\"fcc1caa0776588939c6a4fb79f1602ce\"", missing_meta=nil, version_id=nil, cache_control=nil, content_disposition=nil, content_encoding=nil, content_language=nil, content_type="binary/octet-stream", expires=nil, expires_string=nil, website_redirect_location=nil, server_side_encryption=nil, metadata={}, sse_customer_algorithm=nil, sse_customer_key_md5=nil, ssekms_key_id=nil, storage_class=nil, request_charged=nil, replication_status=nil, parts_count=nil>
```

Try to copy object (tried with and without `acl` key and with and without the initial backslash. All of them raise the exception)
```
irb(main):076:0> S3_CLIENT.copy_object(acl: 'public-read', bucket: S3_BUCKET.name, key: 'z2', copy_source: File.join(S3_BUCKET.name, s3_key))
Aws::S3::Errors::NoSuchKey: The specified key does not exist.
	from (irb):76
```

Here's the filename if relevant.
```
irb(main):077:0> s3_key
=> "multi_uploads/090c1720-a7a3-4723-9dde-a883e1f99879/VS+RS+200ml+0965068+++0965058+#+902217800,+102306682+Deutsche+SiSi.pdf"
```

Here's the bucket name if relevant
```
irb(main):078:0> S3_BUCKET.name
=> "new-ecratum-staging-files"
```

Here's the backtrace if relevant
```
irb(main):032:0> begin
irb(main):033:1* S3_CLIENT.copy_object(bucket: S3_BUCKET.name, key: 'z4', copy_source: File.join(S3_BUCKET.name, s3_key))
irb(main):034:1> rescue => e
irb(main):035:1> puts e.backtrace
irb(main):036:1> end
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.30/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.30/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.30/lib/aws-sdk-core/plugins/s3_dualstack.rb:24:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.30/lib/aws-sdk-core/plugins/s3_accelerate.rb:34:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.30/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.30/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.30/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.30/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.30/lib/seahorse/client/request.rb:70:in `send_request'
/app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.10.30/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
(irb):33:in `irb_binding'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb/workspace.rb:87:in `eval'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb/workspace.rb:87:in `evaluate'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb/context.rb:381:in `evaluate'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:493:in `block (2 levels) in eval_input'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:627:in `signal_status'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:490:in `block in eval_input'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `loop'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `catch'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:489:in `eval_input'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:430:in `block in run'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:429:in `catch'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:429:in `run'
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:385:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/console/console_command.rb:62:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/console/console_command.rb:17:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands/console/console_command.rb:85:in `perform'
/app/vendor/bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/command/base.rb:63:in `perform'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/command.rb:44:in `invoke'
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
/app/bin/rails:4:in `require'
/app/bin/rails:4:in `<main>'
=> nil
```

**Comment by srchase** [comment]
@waldyr 

Thanks for opening this issue.

I am able to reproduce the issue.

If you enable http_wire_trace on the S3 client to debug (see [Getting Wire Trace Information from a Client ](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/debugging.html)), you can see that copy_object is not url encoding the X-Amz-Copy-Source header.

We'll work on getting this resolved.

**Comment by waldyr** [comment]
Really grateful for your reply @srchase. Thank you very much.

It's kind of crazy that `#head_object` and friends don't need it but `#copy_object` does. As your reply solves my issue I'm satisfied but (I saw you adding and removing the bug tag) if you want to normalize the behavior across methods I could make a PR for that.

**Comment by srchase** [comment]
I appreciate the offer for a PR, but the other SDKs have the same behavior and we wouldn't be able to change the functionality that might break other customers with existing implementations.

**Comment by srchase** [comment]
I'll go ahead and close this issue for now.  Let us know if you have any further questions.

**Comment by abepetrillo** [comment]
Just ran into this same problem. As an "other customer" I would rather a consistent behavior. An example of why this is confusing:

```ruby
...
files = bucket.objects(prefix: prefix).collect

      file = files.sort_by(&:last_modified).last
      if file.present?
        begin
          client.copy_object(bucket: ENV['S3_BUCKET_PRIVATE'], copy_source: ENV['S3_BUCKET_NAME'] + '/' + file.key, key: file.key)
...
```

The code crashes using the key that the sdk _gave me_. There are similar bugs on other sdks that have been fixed such as android: https://github.com/aws-amplify/aws-sdk-android/issues/526
