### ISSUE TITLE
uninitialized constant Seahorse::Client::NetHttp::Handler::SocketError

### ISSUE THREAD

**Issue by brandoncc** [aws/aws-sdk-ruby#1939]
Please fill out the sections below to help us address your issue

### Issue description
uninitialized constant Seahorse::Client::NetHttp::Handler::SocketError

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-core v2

### Version of Ruby, OS environment
Ruby 2.5.3, Heroku heroku-18 stack (ubuntu 18.04 LTS)

### Code snippets / steps to reproduce
We upgraded to the latest security patch for Rails and we started getting this error when we try to deploy:

```
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'carrierwave-aws'. (Bundler::GemRequireError)
remote:        Gem Load Error is: uninitialized constant Seahorse::Client::NetHttp::Handler::SocketError
remote:        Backtrace for gem load error is:
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/seahorse/client/net_http/handler.rb:21:in `<class:Handler>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/seahorse/client/net_http/handler.rb:9:in `<module:NetHttp>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/seahorse/client/net_http/handler.rb:5:in `<module:Client>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/seahorse/client/net_http/handler.rb:4:in `<module:Seahorse>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/seahorse/client/net_http/handler.rb:3:in `<top (required)>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:21:in `require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:21:in `block in load'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:18:in `each'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:18:in `load'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:23:in `block in load'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:18:in `each'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:18:in `load'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:23:in `block in load'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:18:in `each'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:18:in `load'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core.rb:521:in `eager_autoload!'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/carrierwave-aws-1.2.0/lib/carrierwave/storage/aws.rb:5:in `<top (required)>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/carrierwave-aws-1.2.0/lib/carrierwave-aws.rb:5:in `require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/carrierwave-aws-1.2.0/lib/carrierwave-aws.rb:5:in `<top (required)>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:82:in `require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:77:in `each'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:77:in `block in require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:66:in `each'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:66:in `require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler.rb:108:in `require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/config/application.rb:5:in `<top (required)>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/command/actions.rb:15:in `require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/commands/runner/runner_command.rb:27:in `perform'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/command/base.rb:63:in `perform'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/command.rb:44:in `invoke'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/commands.rb:16:in `<top (required)>'
remote:        bin/rails:9:in `require'
remote:        bin/rails:9:in `<main>'
```

**Comment by srchase** [comment]
@brandoncc 

That trace points towards an issue with carrierwave.

Are you using aws-sdk directly?  Or only via carrierwave?  Did your gem version of carrierwave get changed with your Rails upgrade?

**Comment by brandoncc** [comment]
@srchase The actual error is being raised [here](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/seahorse/client/net_http/handler.rb#L23), although you are right that we are using carrierwave-aws which is where the aws-sdk require is coming from.

Carrierwave was not changed during the rails upgrade, but I have since tried upgrading aws-sdk, carrierwave, and carrierwave-aws. It didn't help.

Are you saying that the problem can't be in the aws-sdk-ruby gem even though the error is being raised from it?

**Comment by awood45** [comment]
For background, the issue you're seeing tends to happen in multi-threaded environments due to autoloading, and was an issue fixed in major version 3 of the SDK. If you're required to use major version 2, you may want to require the `aws-sdk` or `aws-sdk-core` gem up front and call `Aws.eager_autoload!` to get around this.

**Comment by brandoncc** [comment]
Thank you for the help @awood45, I will look into whether we can use aws v3 or not. If we can't, I'll try your solution. Thanks again!
