### ISSUE TITLE
A service stub config via Aws.config is blocking other service.

### ISSUE THREAD

**Issue by umanoda** [aws/aws-sdk-ruby#1940]
### Issue description

I make default stub settings via `Aws.config` for `spec/rails_helper.rb` and try to use it in each tests.However, one service stub is block other service's client methods.
How can I set multiple stubs? 

### Gem name

* aws-sdk 3.0.1
* aws-sdk-resources 3.21.0
*  aws-sdk-s3 1.16.0
* aws-sdk-sqs 1.4.0

### Version of Ruby, OS environment

* ruby 2.4.2
* Occurred at High Sierra and Debian GNU/Linux 8

### Code snippets / steps to reproduce

It does not work well.

```rb
Aws.config.update :stub_responses => true
Aws.config[:s3] = {
  stub_responses: {
    get_object: [Errno::ECONNREFUSED, "xxxxxxxx"]
  }
}
Aws.config[:sqs] = {
  stub_responses: {
    get_queue_url: {
      queue_url: "http://example.com"
    }
  }
}

Aws::S3::Resource.new
#=> /gems/aws-sdk-core-3.43.0/lib/seahorse/client/configuration.rb:166:in `rescue in block in apply_options': invalid configuration option `:sqs' (ArgumentError)                   
#    from /gems/2.4.0/gems/aws-sdk-core-3.43.0/lib/seahorse/client/configuration.rb:162:in `block in apply_options'                                                                    
#    from /gems/2.4.0/gems/aws-sdk-core-3.43.0/lib/seahorse/client/configuration.rb:161:in `each'                                                                                      
#    from /gems/2.4.0/gems/aws-sdk-core-3.43.0/lib/seahorse/client/configuration.rb:161:in `apply_options'                                                                             
#    from /gems/2.4.0/gems/aws-sdk-core-3.43.0/lib/seahorse/client/configuration.rb:149:in `build!'                                                                                    
#    from /gems/2.4.0/gems/aws-sdk-core-3.43.0/lib/seahorse/client/base.rb:62:in `build_config'                                                                                        
#    from /gems/2.4.0/gems/aws-sdk-core-3.43.0/lib/seahorse/client/base.rb:19:in `initialize'                                                                                          
#    from /gems/2.4.0/gems/aws-sdk-sqs-1.10.0/lib/aws-sdk-sqs/client.rb:213:in `initialize'                                                                                            
#    from /gems/2.4.0/gems/aws-sdk-core-3.43.0/lib/seahorse/client/base.rb:99:in `new'                                                                                                 
#    from /gems/2.4.0/gems/aws-sdk-sqs-1.10.0/lib/aws-sdk-sqs/resource.rb:14:in `initialize'                                                                                           
```

Strangely, once I call a service set in the stub, I can call another service.

```rb
Aws.config.update :stub_responses => true
Aws.config[:s3] = {
  stub_responses: {
    get_object: [Errno::ECONNREFUSED, "xxxxxxxx"]
  }
}
Aws::S3::Resource.new #=> work

Aws.config[:sqs] = {
  stub_responses: {
    get_queue_url: {
      queue_url: "http://example.com"
    }
  }
}
Aws::SQS::Resource.new #=> work. S3 stub setting do not block.
Aws::S3::Resource.new #=> work. SQS stub setting do not too.
```

If possible, I do not want to use this strange way of calling the service at the same time as seting Aws.config.

**Comment by umanoda** [comment]
@srchase
Thanks for the helpful blog post!

Is the default stub setting deprecated? I'd like to prepare a stub for feature testing.

**Comment by srchase** [comment]
@umanoda 

Which 'default stub stetting' are you referring to?

**Comment by umanoda** [comment]
@srchase 

I referenced https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ClientStubs.html (see `Basic usage`)

> Lastly, default stubs can be configured via Aws.config:...

**Comment by umanoda** [comment]
Immediately after setting `Aws.config` stubbing to `config/rails_helper.rb`, we responded by calling a dummy client.
This will prevent errors when the S3 client is called before the SQS client during the test.

```
# config/rails_helper
Aws.config[:sqs] = {
  stub_responses: {
    get_queue_url: {
      queue_url: "http://example.com"
    }
  }
}

#  To activate the stub
Aws::SQS::Resource.new
```
