### ISSUE TITLE
aws-sigv4 raises deprecation warnings for secret_access_key, etc.

### ISSUE THREAD

**Issue by johncox00** [aws/aws-sdk-ruby#2072]
Please fill out the sections below to help us address your issue

### Issue description
When making use of `aws-sigv4` to sign requests to elasticsearch I'm given a deprecation warning and the request does not make it to ES when using `Searchkick`.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

```
gem 'rails', '~> 5.2.3'
gem 'searchkick', '~> 3'
gem 'aws-sdk', '~> 3'
gem 'faraday_middleware-aws-sigv4'
```

### Version of Ruby, OS environment
Ruby: 2.4.0

### Code snippets / steps to reproduce

```
# config/initializers/elasticsearch.rb
if Rails.env.production?

  Searchkick.aws_credentials = {
    credentials: Aws::InstanceProfileCredentials.new,
    region: ENV["AWS_REGION"]
  }

else
  Searchkick.client = Elasticsearch::Client.new(hosts: ['localhost:9200'], retry_on_failure: true, transport_options: {request: {timeout: 250}})
end
```

Then running in Rails console:

```
irb(main):013:0> User.reindex
DEPRECATION WARNING: called deprecated method `access_key_id' of an Aws::CredentialProvider, use #credentials instead
/usr/local/bundle/gems/aws-sigv4-1.1.0/lib/aws-sigv4/signer.rb:670:in `credentials_set?'
/usr/local/bundle/gems/aws-sigv4-1.1.0/lib/aws-sigv4/signer.rb:661:in `get_credentials'
/usr/local/bundle/gems/aws-sigv4-1.1.0/lib/aws-sigv4/signer.rb:205:in `sign_request'
/usr/local/bundle/gems/faraday_middleware-aws-sigv4-0.2.4/lib/faraday_middleware/request/aws_sigv4.rb:22:in `sign!'
/usr/local/bundle/gems/faraday_middleware-aws-sigv4-0.2.4/lib/faraday_middleware/request/aws_sigv4.rb:14:in `call'
/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
/usr/local/bundle/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:40:in `block in perform_request'
/usr/local/bundle/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/base.rb:279:in `perform_request'
/usr/local/bundle/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
/usr/local/bundle/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/client.rb:160:in `perform_request'
/usr/local/bundle/gems/elasticsearch-api-7.1.0/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
/usr/local/bundle/gems/elasticsearch-api-7.1.0/lib/elasticsearch/api/actions/indices/get_alias.rb:49:in `get_alias'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/index.rb:106:in `all_indices'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/index.rb:119:in `clean_indices'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/index.rb:270:in `reindex_scope'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/index.rb:200:in `reindex'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/model.rb:59:in `searchkick_reindex'
(irb):13:in `irb_binding'
/usr/local/lib/ruby/2.4.0/irb/workspace.rb:87:in `eval'
/usr/local/lib/ruby/2.4.0/irb/workspace.rb:87:in `evaluate'
/usr/local/lib/ruby/2.4.0/irb/context.rb:381:in `evaluate'
/usr/local/lib/ruby/2.4.0/irb.rb:493:in `block (2 levels) in eval_input'
/usr/local/lib/ruby/2.4.0/irb.rb:627:in `signal_status'
/usr/local/lib/ruby/2.4.0/irb.rb:490:in `block in eval_input'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `loop'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `catch'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/usr/local/lib/ruby/2.4.0/irb.rb:489:in `eval_input'
/usr/local/lib/ruby/2.4.0/irb.rb:430:in `block in run'
/usr/local/lib/ruby/2.4.0/irb.rb:429:in `catch'
/usr/local/lib/ruby/2.4.0/irb.rb:429:in `run'
/usr/local/lib/ruby/2.4.0/irb.rb:385:in `start'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/console/console_command.rb:64:in `start'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/console/console_command.rb:19:in `start'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/console/console_command.rb:96:in `perform'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
DEPRECATION WARNING: called deprecated method `secret_access_key' of an Aws::CredentialProvider, use #credentials instead
/usr/local/bundle/gems/aws-sigv4-1.1.0/lib/aws-sigv4/signer.rb:670:in `credentials_set?'
/usr/local/bundle/gems/aws-sigv4-1.1.0/lib/aws-sigv4/signer.rb:661:in `get_credentials'
/usr/local/bundle/gems/aws-sigv4-1.1.0/lib/aws-sigv4/signer.rb:205:in `sign_request'
/usr/local/bundle/gems/faraday_middleware-aws-sigv4-0.2.4/lib/faraday_middleware/request/aws_sigv4.rb:22:in `sign!'
/usr/local/bundle/gems/faraday_middleware-aws-sigv4-0.2.4/lib/faraday_middleware/request/aws_sigv4.rb:14:in `call'
/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
/usr/local/bundle/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:40:in `block in perform_request'
/usr/local/bundle/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/base.rb:279:in `perform_request'
/usr/local/bundle/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
/usr/local/bundle/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/client.rb:160:in `perform_request'
/usr/local/bundle/gems/elasticsearch-api-7.1.0/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
/usr/local/bundle/gems/elasticsearch-api-7.1.0/lib/elasticsearch/api/actions/indices/get_alias.rb:49:in `get_alias'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/index.rb:106:in `all_indices'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/index.rb:119:in `clean_indices'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/index.rb:270:in `reindex_scope'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/index.rb:200:in `reindex'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/model.rb:59:in `searchkick_reindex'
(irb):13:in `irb_binding'
/usr/local/lib/ruby/2.4.0/irb/workspace.rb:87:in `eval'
/usr/local/lib/ruby/2.4.0/irb/workspace.rb:87:in `evaluate'
/usr/local/lib/ruby/2.4.0/irb/context.rb:381:in `evaluate'
/usr/local/lib/ruby/2.4.0/irb.rb:493:in `block (2 levels) in eval_input'
/usr/local/lib/ruby/2.4.0/irb.rb:627:in `signal_status'
/usr/local/lib/ruby/2.4.0/irb.rb:490:in `block in eval_input'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `loop'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `catch'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/usr/local/lib/ruby/2.4.0/irb.rb:489:in `eval_input'
/usr/local/lib/ruby/2.4.0/irb.rb:430:in `block in run'
/usr/local/lib/ruby/2.4.0/irb.rb:429:in `catch'
/usr/local/lib/ruby/2.4.0/irb.rb:429:in `run'
/usr/local/lib/ruby/2.4.0/irb.rb:385:in `start'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/console/console_command.rb:64:in `start'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/console/console_command.rb:19:in `start'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/console/console_command.rb:96:in `perform'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
DEPRECATION WARNING: called deprecated method `session_token' of an Aws::CredentialProvider, use #credentials instead
/usr/local/bundle/gems/aws-sigv4-1.1.0/lib/aws-sigv4/signer.rb:221:in `sign_request'
/usr/local/bundle/gems/faraday_middleware-aws-sigv4-0.2.4/lib/faraday_middleware/request/aws_sigv4.rb:22:in `sign!'
/usr/local/bundle/gems/faraday_middleware-aws-sigv4-0.2.4/lib/faraday_middleware/request/aws_sigv4.rb:14:in `call'
/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
/usr/local/bundle/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:40:in `block in perform_request'
/usr/local/bundle/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/base.rb:279:in `perform_request'
/usr/local/bundle/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
/usr/local/bundle/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/client.rb:160:in `perform_request'
/usr/local/bundle/gems/elasticsearch-api-7.1.0/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
/usr/local/bundle/gems/elasticsearch-api-7.1.0/lib/elasticsearch/api/actions/indices/get_alias.rb:49:in `get_alias'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/index.rb:106:in `all_indices'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/index.rb:119:in `clean_indices'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/index.rb:270:in `reindex_scope'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/index.rb:200:in `reindex'
/usr/local/bundle/gems/searchkick-3.1.3/lib/searchkick/model.rb:59:in `searchkick_reindex'
(irb):13:in `irb_binding'
/usr/local/lib/ruby/2.4.0/irb/workspace.rb:87:in `eval'
/usr/local/lib/ruby/2.4.0/irb/workspace.rb:87:in `evaluate'
/usr/local/lib/ruby/2.4.0/irb/context.rb:381:in `evaluate'
/usr/local/lib/ruby/2.4.0/irb.rb:493:in `block (2 levels) in eval_input'
/usr/local/lib/ruby/2.4.0/irb.rb:627:in `signal_status'
/usr/local/lib/ruby/2.4.0/irb.rb:490:in `block in eval_input'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `loop'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `catch'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/usr/local/lib/ruby/2.4.0/irb.rb:489:in `eval_input'
/usr/local/lib/ruby/2.4.0/irb.rb:430:in `block in run'
/usr/local/lib/ruby/2.4.0/irb.rb:429:in `catch'
/usr/local/lib/ruby/2.4.0/irb.rb:429:in `run'
/usr/local/lib/ruby/2.4.0/irb.rb:385:in `start'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/console/console_command.rb:64:in `start'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/console/console_command.rb:19:in `start'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands/console/console_command.rb:96:in `perform'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
^CIRB::Abort: abort then interrupt!
	from (irb):13
irb(main):014:0> exit
```

**Comment by cjyclaire** [comment]
I'm not sure how `searchkick` handles `:credentials` for `.aws_credentials`, my guess is 
```
Searchkick.aws_credentials = {
    credentials: Aws::InstanceProfileCredentials.new**.credentials**,
...
  }
```
should avoid those warnings

**Comment by cjyclaire** [comment]
closing as it's causing by 3rd party usage of SDKs, solutions has been provided.
Feel free to reopen with further questions :)

**Comment by jacobtani** [comment]
whats the solution to this issue?

**Comment by cjyclaire** [comment]
@jacobtani Did my above code snippet works for you? If you are also using a 3rd party library, then the library need to update the code.
