### ISSUE TITLE
NoMethodError in aws-sdk-core/endpoint_cache.rb

### ISSUE THREAD

**Issue by kalpitad** [aws/aws-sdk-ruby#2210]
Please fill out the sections below to help us address your issue

### Issue description
We got a random `NoMethodError` from **aws-sdk-core/endpoint_cache.rb** in our production app during a DynamoDB query request through the Ruby SDK. We have never seen this before and saw it only once yesterday. I'm opening this issue as an FYI to you; if it's not useful, feel free to close it. I can re-open the issue if I start to see this more often.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
`gem 'aws-sdk', '~> 3'`

Here is what is installed in my Gemfile.lock: `aws-sdk-core (~> 3, >= 3.53.0)`

### Version of Ruby, OS environment
Ruby 2.6
Amazon Linux 2018.03
EC2 instance managed by Opsworks

### Code snippets / steps to reproduce
````
Aws::DynamoDB::Client.new.query(
  table_name: table_name,
  index_name: index_name,
  key_condition_expression: "id = :id",
  expression_attribute_values: {":id": {"s": "#{id}"}},
  projection_expression: "#d",
  expression_attribute_names: {"#d" => "details"}
)
````

### Stack trace
[2020-01-16 02:09:55 UTC] Exception: #<NoMethodError: undefined method `credentials' for nil:NilClass>. Details: ["/home/deploy/.bundler/my_app/ruby/2.6.0/gems/aws-sdk-core-3.53.1/lib/aws-sdk-core/endpoint_cache.rb:108:in `extract_key'", "/home/deploy/.bundler/my_app/ruby/2.6.0/gems/aws-sdk-core-3.53.1/lib/aws-sdk-core/plugins/endpoint_discovery.rb:102:in `_discover_endpoint'", "/home/deploy/.bundler/my_app/ruby/2.6.0/gems/aws-sdk-core-3.53.1/lib/aws-sdk-core/plugins/endpoint_discovery.rb:69:in `call'", "/home/deploy/.bundler/my_app/ruby/2.6.0/gems/aws-sdk-core-3.53.1/lib/seahorse/client/plugins/endpoint.rb:45:in `call'", "/home/deploy/.bundler/my_app/ruby/2.6.0/gems/aws-sdk-core-3.53.1/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'", "/home/deploy/.bundler/my_app/ruby/2.6.0/gems/aws-sdk-core-3.53.1/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'", "/home/deploy/.bundler/my_app/ruby/2.6.0/gems/aws-sdk-core-3.53.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'", "/home/deploy/.bundler/my_app/ruby/2.6.0/gems/aws-sdk-core-3.53.1/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'", "/home/deploy/.bundler/my_app/ruby/2.6.0/gems/aws-sdk-core-3.53.1/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'", "/home/deploy/.bundler/my_app/ruby/2.6.0/gems/aws-sdk-core-3.53.1/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'", "/home/deploy/.bundler/my_app/ruby/2.6.0/gems/aws-sdk-core-3.53.1/lib/seahorse/client/plugins/response_target.rb:23:in `call'", "/home/deploy/.bundler/my_app/ruby/2.6.0/gems/aws-sdk-core-3.53.1/lib/seahorse/client/request.rb:70:in `send_request'", "/home/deploy/.bundler/my_app/ruby/2.6.0/gems/

**Comment by mullermp** [comment]
Thanks for the issue. It see that you're creating a new client and relying on the credential provider chain. It looks like you have a `nil` credentials provider (and trying to call `credentials` method on that). I see that you're on an older version of core, too, so it's specifically [referring to this line](https://github.com/aws/aws-sdk-ruby/blob/7c9584bc6473100df9aec9333ab491ad4faeeca8/gems/aws-sdk-core/lib/aws-sdk-core/endpoint_cache.rb#L108).

**Comment by mullermp** [comment]
Are you still seeing this error? Double check that your credentials are loaded and working. I'm assuming you are using `endpoint_cache` discovery options? https://github.com/aws/aws-sdk-ruby/blob/7c9584bc6473100df9aec9333ab491ad4faeeca8/gems/aws-sdk-core/lib/aws-sdk-core/plugins/endpoint_discovery.rb#L43

**Comment by rajulgarg** [comment]
@mullermp this is the exact issue we are also getting while running our application in Fargate.
We are using `aws-sdk` Version3

**Comment by mullermp** [comment]
@rajulgarg If you are seeing the `'credentials' for nil:NilClass` error, double check that the credentials you are passing into the client (or the credentials loaded by the credential provider chain automatically) are correct.

**Comment by thomaswitt** [comment]
FYI, I just ran into the same bug.

The SDK's endpoint cache assumes credentials are always explicitly set. On ECS/Fargate with IAM roles, credentials are loaded lazily from instance metadata, but the endpoint cache tries to access them before resolution completes.

When `AWS_EXECUTION_ENV` is present (on ECS), no credentials are set. The AWS SDK SHOULD automatically use the credential provider chain, but there might be a timing issue where the endpoint cache tries to access credentials before they're resolved.

I am trying to fix this by explicitly set the credential provider.

**Comment by richardwang1124** [comment]
Hey @thomaswitt, did explicitly setting the credentials provider resolve your issue? I can try looking into this issue again.

**Comment by thomaswitt** [comment]
@richardwang1124 We solved it this way:

```ruby
# Credentials configuration
# See: https://github.com/aws/aws-sdk-ruby/issues/2210
if ENV['AWS_CONTAINER_CREDENTIALS_RELATIVE_URI'].present? || ENV['AWS_CONTAINER_CREDENTIALS_FULL_URI'].present?
  # ECS: Explicitly set credential provider to avoid endpoint_cache.rb nil crash
  aws_config[:credentials] = Aws::ECSCredentials.new(retries: 3)
elsif ENV['AWS_EXECUTION_ENV'].blank?
  # Local dev: Use static credentials from Rails credentials file
  access_key = Rails.application.credentials.dig(:aws, :access_key_id)
  secret_key = Rails.application.credentials.dig(:aws, :secret_access_key)
  if access_key.present? && secret_key.present?
    aws_config[:credentials] = Aws::Credentials.new(access_key, secret_key)
  end
end
```

Let me know if that helps you.
