### ISSUE TITLE
NameError: uninitialized constant Aws::Structure

### ISSUE THREAD

**Issue by saks** [aws/aws-sdk-ruby#2276]
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
We've noticed that after recent upgrade for `aws-sdk-core` (from `3.91.1` -> `3.92.0`) we started getting the error: `NameError: uninitialized constant Aws::Structure`.
Error happens at this line:
```ruby
require 'aws-sdk-secretsmanager'
```
Adding `require 'aws-sdk-core/structure'` does not fix the issue.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
```
    aws-eventstream (1.0.3)
    aws-partitions (1.287.0)
    aws-sdk-autoscaling (1.33.0)
      aws-sdk-core (~> 3, >= 3.71.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-core (3.92.0)
      aws-eventstream (~> 1.0, >= 1.0.2)
      aws-partitions (~> 1, >= 1.239.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1.0)
    aws-sdk-ec2 (1.151.0)
      aws-sdk-core (~> 3, >= 3.71.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-kms (1.30.0)
      aws-sdk-core (~> 3, >= 3.71.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.61.1)
      aws-sdk-core (~> 3, >= 3.83.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.1)
    aws-sdk-secretsmanager (1.34.0)
      aws-sdk-core (~> 3, >= 3.71.0)
      aws-sigv4 (~> 1.1)
    aws-sigv4 (1.1.1)
      aws-eventstream (~> 1.0, >= 1.0.2)
```

**Version of Ruby, OS environment**
`ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-linux]`

**To Reproduce (observed behavior)**
It's a little hard to provide minimal example since it only happens when you run rails command under production env. If absolutely necessary I'll see how to prepare a repo.

**Expected behavior**
No exception.

**Screenshots**
```
Caused by:
NameError: uninitialized constant Aws::Structure
/.../bundle/ruby/2.4.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
/.../bundle/ruby/2.4.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
/.../bundle/ruby/2.4.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
/.../bundle/ruby/2.4.0/gems/aws-sdk-secretsmanager-1.34.0/lib/aws-sdk-secretsmanager/types.rb:44:in `<class:CancelRotateSecretRequest>'
/.../bundle/ruby/2.4.0/gems/aws-sdk-secretsmanager-1.34.0/lib/aws-sdk-secretsmanager/types.rb:43:in `<module:Types>'
/.../bundle/ruby/2.4.0/gems/aws-sdk-secretsmanager-1.34.0/lib/aws-sdk-secretsmanager/types.rb:9:in `<module:SecretsManager>'
/.../bundle/ruby/2.4.0/gems/aws-sdk-secretsmanager-1.34.0/lib/aws-sdk-secretsmanager/types.rb:8:in `<main>'
/.../bundle/ruby/2.4.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/.../bundle/ruby/2.4.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/.../bundle/ruby/2.4.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/.../bundle/ruby/2.4.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/.../bundle/ruby/2.4.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/.../bundle/ruby/2.4.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:49:in `require_relative'
/.../bundle/ruby/2.4.0/gems/aws-sdk-secretsmanager-1.34.0/lib/aws-sdk-secretsmanager.rb:11:in `<main>'
/.../bundle/ruby/2.4.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/.../bundle/ruby/2.4.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/.../bundle/ruby/2.4.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/.../bundle/ruby/2.4.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/.../bundle/ruby/2.4.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/.../20200325183139/config/application.rb:6:in `<top (required)>'
/.../20200325183139/Rakefile:4:in `require_relative'
/.../20200325183139/Rakefile:4:in `<top (required)>'
/.../shared/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

**Comment by mullermp** [comment]
A production repo would be helpful. We've seen a similar error with bootsnap around `to_json` usage.

**Comment by mullermp** [comment]
A path forward would be to remove bootsnap. You may also want to check with them - it loads correctly without that dependency.

**Comment by saks** [comment]
Thanks! Makes sense, will check how it works without bootsnap first.

**Comment by saks** [comment]
same without bootsnap:
```
NameError: uninitialized constant Aws::Structure
Did you mean?  Struct
/.../shared/bundle/ruby/2.4.0/gems/aws-sdk-secretsmanager-1.34.0/lib/aws-sdk-secretsmanager/types.rb:44:in `<class:CancelRotateSecretRequest>'
/.../shared/bundle/ruby/2.4.0/gems/aws-sdk-secretsmanager-1.34.0/lib/aws-sdk-secretsmanager/types.rb:43:in `<module:Types>'
/.../shared/bundle/ruby/2.4.0/gems/aws-sdk-secretsmanager-1.34.0/lib/aws-sdk-secretsmanager/types.rb:9:in `<module:SecretsManager>'
/.../shared/bundle/ruby/2.4.0/gems/aws-sdk-secretsmanager-1.34.0/lib/aws-sdk-secretsmanager/types.rb:8:in `<top (required)>'
/.../shared/bundle/ruby/2.4.0/gems/aws-sdk-secretsmanager-1.34.0/lib/aws-sdk-secretsmanager.rb:11:in `require_relative'
/.../shared/bundle/ruby/2.4.0/gems/aws-sdk-secretsmanager-1.34.0/lib/aws-sdk-secretsmanager.rb:11:in `<top (required)>'
/.../releases/20200325220917/config/application.rb:5:in `require'
/.../releases/20200325220917/config/application.rb:5:in `<top (required)>'
/.../releases/20200325220917/Rakefile:4:in `require_relative'
/.../releases/20200325220917/Rakefile:4:in `<top (required)>'
/.../shared/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

**Comment by mullermp** [comment]
Installing and requiring `aws-sdk-secretsmanager` works fine for me. I created a new rails app (using `rails new`) and added `aws-sdk-secretsmanager` to the Gemfile, ran `bundle update` and then `rails console` and it also appears to have loaded. A reproduction repo would be extremely helpful; @ajredniwja could take a look at that.
