### ISSUE TITLE
NameError: no member 'message' in struct when trying to untag EFS filesystem

### ISSUE THREAD

**Issue by ivoanjo** [aws/aws-sdk-ruby#2363]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

Hello colleagues! I'm from the Amazon CodeGuru Profiler team and I was playing around with EFS and the Ruby SDK and found an issue handling the response from untagging an EFS filesystem. More details below.

Thanks for making Ruby awesome, and let me know if I can provide any more info :D

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
`aws-sdk-efs-1.33.0`

**Version of Ruby, OS environment**
`ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]`

**To Reproduce (observed behavior)**
```ruby
$ pry
[1] pry(main)> require 'aws-sdk-efs'
=> true
[2] pry(main)> client = Aws::EFS::Client.new(region: "ap-southeast-2")=> #<Aws::EFS::Client>
[3] pry(main)> resp = client.create_file_system({
[3] pry(main)*     creation_token: "tokenstring",   
[3] pry(main)*     performance_mode: "generalPurpose",   
[3] pry(main)*     tags: [  
[3] pry(main)*       {    
[3] pry(main)*         key: "Name",       
[3] pry(main)*         value: "MyFileSystem",       
[3] pry(main)*       },       
[3] pry(main)*     ],     
[3] pry(main)* })    
=> #<struct Aws::EFS::Types::FileSystemDescription
 owner_id="REDACTED",
 creation_token="tokenstring",
 file_system_id="fs-991feaa1",
 file_system_arn="arn:aws:elasticfilesystem:ap-southeast-2:REDACTED:file-system/REDACTED",
 creation_time=2020-07-17 10:33:35 +0100,
 life_cycle_state="creating",
 name="MyFileSystem",
 number_of_mount_targets=0,
 size_in_bytes=#<struct Aws::EFS::Types::FileSystemSize value=0, timestamp=nil, value_in_ia=0, value_in_standard=0>,
 performance_mode="generalPurpose",
 encrypted=false,
 kms_key_id=nil,
 throughput_mode="bursting",
 provisioned_throughput_in_mibps=nil,
 tags=[#<struct Aws::EFS::Types::Tag key="Name", value="MyFileSystem">]>
[5] pry(main)> client.untag_resource(resource_id: "arn:aws:elasticfilesystem:ap-southeast-2:REDACTED:file-system/REDACTED", tag_keys: ["hello", "this", "is", "a", "test"])
(pry) output error: #<NameError: no member 'message' in struct>
.rvm/gems/ruby-2.5.3/gems/aws-sdk-efs-1.33.0/lib/aws-sdk-efs/errors.rb:145:in `[]'
.rvm/gems/ruby-2.5.3/gems/aws-sdk-efs-1.33.0/lib/aws-sdk-efs/errors.rb:145:in `message'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry.rb:45:in `block in <class:Pry>'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/pry_instance.rb:397:in `show_result'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/pry_instance.rb:368:in `block in 
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/pry_class.rb:401:in `critical_section'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/pry_instance.rb:367:in `handle_line'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/pry_instance.rb:274:in `block (2 levels) in 
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `catch'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `block in eval'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `catch'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `eval'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/repl.rb:77:in `block in repl'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/lib/pry/cli.rb:111:in `start'
.rvm/gems/ruby-2.5.3/gems/pry-0.12.2/bin/pry:8:in `<top (required)>'
.rvm/gems/ruby-2.5.3/bin/pry:23:in `load'
.rvm/gems/ruby-2.5.3/bin/pry:23:in `<main>'
.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
```

**Expected behavior**
Request should not result in a `NameError`

**Comment by mullermp** [comment]
For the `resource_id`, instead of using the ARN, pass in `file_system_id: fs-991feaa1`. We will make a change to raise a friendly error in cases where services throw errors without messages.
