### ISSUE TITLE
AWS SDK core >= 3.104.0 breaks with IO reading with ShrineRB

### ISSUE THREAD

**Issue by samstickland** [aws/aws-sdk-ruby#2371]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
On versions below 3.104.0 I can call `to_io` on a `ApplicationShrine::UploadedFile` and read the bytes. But on 3.104.0 and above this returns `*** NoMethodError Exception: undefined method `bytesize' for #<Array:0x00007fd4f76ef950>`

This is with AWS SDK Core 3.103.0:

```
#<Down::ChunkedIO chunks=#<Enumerator: #<Enumerator::Generator:0x00007fd4f76ef798>:each> size=745 encoding=#<Encoding:ASCII-8BIT> data={} on_close=nil rewindable=true>

(byebug) invoice.invoice_pdf.to_io.read
*** NoMethodError Exception: undefined method `bytesize' for #<Array:0x00007fd4f76ef950>

(byebug) invoice.invoice_pdf.class.ancestors
[Invoice::Uploader::UploadedFile, ApplicationShrine::UploadedFile, Shrine::UploadedFile, Shrine::Plugins::RackResponse::FileMethods, Shrine::Plugins::AddMetadata::FileMethods, Shrine::UploadedFile::InstanceMethods, ActiveSupport::Dependencies::ZeitwerkIntegration::RequireDependency, ActiveSupport::ToJsonWithActiveSupportEncoder, Object, Support::WindowSizes, Nori::CoreExt::Object, Delayed::MessageSending, PP::ObjectMixin, JSON::Ext::Generator::GeneratorMethods::Object, ActiveSupport::Tryable, ActiveSupport::Dependencies::Loadable, Kernel, BasicObject]

(byebug) invoice.invoice_pdf.to_io.class
Down::ChunkedIO

(byebug) invoice.invoice_pdf.method(:to_io).source_location
["/Users/samuelstickland/.gem/ruby/2.6.6/gems/shrine-3.2.1/lib/shrine/uploaded_file.rb", 202]
```

This is with 3.103.0:

```
invoice.invoice_pdf.to_io
#<Down::ChunkedIO chunks=#<Enumerator: #<Enumerator::Generator:0x00007fa9e98f4810>:each> size=745 encoding=#<Encoding:ASCII-8BIT> data={} on_close=nil rewindable=true>

(byebug) invoice.invoice_pdf.to_io.read
[... PDF OUTPUT REMOVED ...]

(byebug) invoice.invoice_pdf.class
Invoice::Uploader::UploadedFile

(byebug) invoice.invoice_pdf.class.ancestors
[Invoice::Uploader::UploadedFile, ApplicationShrine::UploadedFile, Shrine::UploadedFile, Shrine::Plugins::RackResponse::FileMethods, Shrine::Plugins::AddMetadata::FileMethods, Shrine::UploadedFile::InstanceMethods, ActiveSupport::Dependencies::ZeitwerkIntegration::RequireDependency, ActiveSupport::ToJsonWithActiveSupportEncoder, Object, Support::WindowSizes, Nori::CoreExt::Object, Delayed::MessageSending, PP::ObjectMixin, JSON::Ext::Generator::GeneratorMethods::Object, ActiveSupport::Tryable, ActiveSupport::Dependencies::Loadable, Kernel, BasicObject]
```

The backtrace for the bug doesn't include any AWS gem, but the version of the aws-sdk-core is the only thing I need to vary to cause the exception:

```
     NoMethodError:
       undefined method `bytesize' for #<Array:0x00007f94f8185260>
     # /Users/samuelstickland/.gem/ruby/2.6.6/gems/down-5.1.1/lib/down/chunked_io.rb:173:in `readpartial'
     # /Users/samuelstickland/.gem/ruby/2.6.6/gems/down-5.1.1/lib/down/chunked_io.rb:72:in `read'
     # ./app/concepts/assignments/invoicing/invoice_types/supplier/mailer.rb:43:in `created'
```

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

When broken (with 3.104.0):

```
$ grep aws Gemfile.lock
    aws-eventstream (1.1.0)
    aws-partitions (1.345.0)
    aws-sdk-core (3.104.0)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.239.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-kms (1.36.0)
      aws-sdk-core (~> 3, >= 3.99.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.74.0)
      aws-sdk-core (~> 3, >= 3.102.1)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.1)
    aws-sigv4 (1.2.1)
      aws-eventstream (~> 1, >= 1.0.2)
    aws_cf_signer (0.1.3)
      aws_cf_signer
  aws-sdk-core (= 3.104.0)
  aws-sdk-s3
```

When working (with 3.103.0):

```
$ grep aws Gemfile.lock
    aws-eventstream (1.1.0)
    aws-partitions (1.345.0)
    aws-sdk-core (3.103.0)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.239.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-kms (1.36.0)
      aws-sdk-core (~> 3, >= 3.99.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.74.0)
      aws-sdk-core (~> 3, >= 3.102.1)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.1)
    aws-sigv4 (1.2.1)
      aws-eventstream (~> 1, >= 1.0.2)
    aws_cf_signer (0.1.3)
      aws_cf_signer
  aws-sdk-core (= 3.103.0)
  aws-sdk-s3
```

**Version of Ruby, OS environment**

ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]

**To Reproduce (observed behavior)**

With an available and configured S3 resource use this ShrineRb config:

```
class Uploader < ::ApplicationShrine
  include Uploader::Attachment(:attachment_column_name)
end
```

On a record with an attachment call `record.attachment_column_name.to_io.read`

**Expected behavior**

The bytes for the attached file will be retrieved.

**Comment by alextwoods** [comment]
I believe Shrine has a fix for this: https://github.com/shrinerb/shrine/commit/c039a250845c4df7cac7d9e6f5ca81f985c744eb

**Comment by samstickland** [comment]
Thanks! I'll try it out with shrinerb master and let you know.
