### ISSUE TITLE
Intermittent EOFError

### ISSUE THREAD

**Issue by mdub** [aws/aws-sdk-ruby#244]
I have a script that copies (a large number of) objects between buckets.  Every now and then it hits an EOFError, e.g.

```
/usr/local/lib/ruby/1.9.1/openssl/buffering.rb:174:in `sysread_nonblock': end of file reached (EOFError)
  from /usr/local/lib/ruby/1.9.1/openssl/buffering.rb:174:in `read_nonblock'
  from /usr/local/lib/ruby/1.9.1/net/protocol.rb:141:in `rbuf_fill'
  from /usr/local/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
  from /usr/local/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
  from /usr/local/lib/ruby/1.9.1/net/http.rb:2562:in `read_status_line'
  from /usr/local/lib/ruby/1.9.1/net/http.rb:2551:in `read_new'
  from /usr/local/lib/ruby/1.9.1/net/http.rb:1319:in `block in transport_request'
  from /usr/local/lib/ruby/1.9.1/net/http.rb:1316:in `catch'
  from /usr/local/lib/ruby/1.9.1/net/http.rb:1316:in `transport_request'
  from /usr/local/lib/ruby/1.9.1/net/http.rb:1293:in `request'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/aws-sdk-1.9.3/lib/aws/core/http/connection_pool.rb:330:in `request'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/aws-sdk-1.9.3/lib/aws/core/http/net_http_handler.rb:58:in `block in handle'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/aws-sdk-1.9.3/lib/aws/core/http/connection_pool.rb:129:in `session_for'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/aws-sdk-1.9.3/lib/aws/core/http/net_http_handler.rb:52:in `handle'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/aws-sdk-1.9.3/lib/aws/core/client.rb:238:in `block in make_sync_request'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/aws-sdk-1.9.3/lib/aws/core/client.rb:274:in `retry_server_errors'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/aws-sdk-1.9.3/lib/aws/core/client.rb:234:in `make_sync_request'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/aws-sdk-1.9.3/lib/aws/core/client.rb:496:in `block (2 levels) in client_request'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/aws-sdk-1.9.3/lib/aws/core/client.rb:376:in `log_client_request'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/aws-sdk-1.9.3/lib/aws/core/client.rb:462:in `block in client_request'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/aws-sdk-1.9.3/lib/aws/core/client.rb:358:in `return_or_raise'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/aws-sdk-1.9.3/lib/aws/core/client.rb:461:in `client_request'
  from (eval):3:in `copy_object'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/aws-sdk-1.9.3/lib/aws/s3/s3_object.rb:892:in `copy_from'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/aws-sdk-1.9.3/lib/aws/s3/s3_object.rb:977:in `copy_to'
  from /opt/rea/apps/attachment-sync/vendor/bundle/ruby/1.9.1/gems/s3mirror-0.5.2/bin/s3mirror:103:in `copy_object'
```

The code concerned is:

```
def copy_object(key)
  src_object = src_bucket.objects[key]
  dest_object = dest_bucket.objects[key]
  src_object.copy_to(dest_object, :acl => :public_read)
end
```

I have up to 20 Threads performing copies (of different objects) at the same time; could that be an issue?  I've heard that the aws-sdk has issues with multi-threading, but my understanding is that it's limited to autoloading of code.

Would increasing :max_retries help?

**Comment by leondmello** [comment]
@lsegal I'm trying to find an option [here](https://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html) where I can possibly change the `thread_count` used for multipart uploads.
Can't seem to find it 😞
