### ISSUE TITLE
Missing region even when it's provided

### ISSUE THREAD

**Issue by Shalashtein** [aws/aws-sdk-ruby#2473]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Recieving Aws::Errors::MissingRegionError when region is provided, this only happens on production enviroment event thought both development and production have the same settings

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-s3 1.88.0

**Version of Ruby, OS environment**
Ruby 2.6.6, Ubuntu 20.04

**To Reproduce (observed behavior)**
```
config.paperclip_defaults = {
  :storage => :s3,
  :preserve_files => false,
  :s3_region => 'eu-west-3',
  :s3_credentials => {
    :access_key_id => ENV["AWS_ACCESS_KEY_ID"],
    :secret_access_key => ENV["AWS_SECRET_KEY_ID"],
    },
  :bucket => ENV["BUCKET_NAME"]
  }
  ```
I tried it with .env :s3_region => ENV["S3_REGION_NAME"], tried it inside credentials, tried using :region instead of :s3_region

**Screenshots**

```
RAILS_ENV=production rake assets:precompile
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.88.0/lib/aws-sdk-s3/plugins/s3_signer.rb:23:in `block in <class:S3Signer>': No region was provided. Configure the `:region` option or export the region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.112.0/lib/seahorse/client/configuration.rb:72:in `call'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.112.0/lib/seahorse/client/configuration.rb:215:in `block in resolve_defaults'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.112.0/lib/seahorse/client/configuration.rb:59:in `each'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.112.0/lib/seahorse/client/configuration.rb:59:in `each'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.112.0/lib/seahorse/client/configuration.rb:214:in `resolve_defaults'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.112.0/lib/seahorse/client/configuration.rb:207:in `value_at'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.112.0/lib/seahorse/client/configuration.rb:191:in `block in resolve'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each_key'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.112.0/lib/seahorse/client/configuration.rb:191:in `resolve'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.112.0/lib/seahorse/client/configuration.rb:179:in `apply_defaults'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.112.0/lib/seahorse/client/configuration.rb:152:in `build!'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.112.0/lib/seahorse/client/base.rb:65:in `build_config'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.112.0/lib/seahorse/client/base.rb:22:in `initialize'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.88.0/lib/aws-sdk-s3/client.rb:406:in `initialize'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.112.0/lib/seahorse/client/base.rb:102:in `new'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.88.0/lib/aws-sdk-s3/resource.rb:28:in `initialize'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activestorage-6.1.1/lib/active_storage/service/s3_service.rb:16:in `new'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activestorage-6.1.1/lib/active_storage/service/s3_service.rb:16:in `initialize'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activestorage-6.1.1/lib/active_storage/service.rb:61:in `new'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activestorage-6.1.1/lib/active_storage/service.rb:61:in `build'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activestorage-6.1.1/lib/active_storage/service/configurator.rb:17:in `build'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activestorage-6.1.1/lib/active_storage/service/registry.rb:13:in `block in fetch'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activestorage-6.1.1/lib/active_storage/service/registry.rb:11:in `fetch'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activestorage-6.1.1/lib/active_storage/service/registry.rb:11:in `fetch'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activestorage-6.1.1/lib/active_storage/engine.rb:129:in `block (2 levels) in <class:Engine>'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
        from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activestorage-6.1.1/app/models/active_storage/blob.rb:346:in `<main>'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/skylight-core-4.3.2/lib/skylight/core/probes.rb:118:in `require'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:416:in `const_get'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:416:in `block (2 levels) in eager_load'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:733:in `block in ls'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `foreach'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `ls'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:404:in `block in eager_load'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `synchronize'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `eager_load'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `each'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `eager_load_all'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.1/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.1/lib/rails/initializable.rb:32:in `run'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `call'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.1/lib/rails/application.rb:384:in `initialize!'
	from /home/shalashtein/code/Shalashtein/labbesne/config/environment.rb:5:in `<main>'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/skylight-core-4.3.2/lib/skylight/core/probes.rb:118:in `require'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:106:in `preload'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by mullermp** [comment]
The SDK looks for the region on the Client (i.e. `Aws::S3::Client.new(region: 'us-west-2')`) or in `ENV['REGION'] = 'us-west-2'`. I'm not entirely sure what Paperclip is doing.

According to the [Paperclip docs](https://www.rubydoc.info/gems/paperclip/Paperclip/Storage/S3), your configuration looks correct. You mention that it works in development and not production - is it possible that your `config.paperclip_defaults` is nil in production? Perhaps Rails production is not loading the config you expect?

By the way, Paperclip is deprecated, you should make an effort to migrate to ActiveStorage.

**Comment by jcavalieri** [comment]
I'm getting this with active storage. And I definitely have region set: `  region: us-east-1`

**Comment by jcavalieri** [comment]
I think I may have solved this. At least on my case. I had changed the service name in storage.yml. Turns out you just can't do that because the blobs record the service name used in `storage.yml`.

So I had to update the `service_name` column for all blob records.

I hope this helps anyone else.

**Comment by OpakAlex** [comment]
Why it's inside initializer? Raise this error when service call s3, this is so strange behaviour for OOP language. initialize can not return raise of error, it must be instance!

**Comment by cpdohert** [comment]
>initialize can not return raise of error, it must be instance

This behaviour also breaks a number of 12factor best practices, among them the fact that a Rails app using the S3 SDK needs to be built separately for each different set of AWS configuration options.  It's not clear to me why Rails' asset precompilation state - which is supposed to be solely for packing JS, CSS, HTML and static images - has a dependency on an S3 SDK gem. Is it generating JS/CSS?  Why?
