### ISSUE TITLE
before_refresh on AssumeRoleWebIdentityCredentials considered invalid if no client provided

### ISSUE THREAD

**Issue by mpalmer** [aws/aws-sdk-ruby#2690]
### Describe the bug

Creating an instance of `AssumeRoleWebIdentityCredentials` with the `before_refresh` option, but without the `client` option, raises an exception.

### Expected Behavior

A working credentials provider.

### Current Behavior

```
Traceback (most recent call last):
       16: from /usr/local/bin/irb:23:in `<main>'
       15: from /usr/local/bin/irb:23:in `load'
       14: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
       13: from (irb):13
       12: from (irb):14:in `rescue in irb_binding'
       11: from (irb):14:in `new'
       10: from /usr/local/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/assume_role_web_identity_credentials.rb:64:in `initialize'
        9: from /usr/local/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/base.rb:102:in `new'
        8: from /usr/local/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-sts/client.rb:356:in `initialize'
        7: from /usr/local/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/base.rb:22:in `initialize'
        6: from /usr/local/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/base.rb:65:in `build_config'
        5: from /usr/local/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/configuration.rb:151:in `build!'
        4: from /usr/local/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/configuration.rb:163:in `apply_options'
        3: from /usr/local/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/configuration.rb:163:in `each'
        2: from /usr/local/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/configuration.rb:164:in `block in apply_options'
        1: from /usr/local/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/configuration.rb:168:in `rescue in block in apply_options'
ArgumentError (invalid configuration option `:before_refresh')
```

### Reproduction Steps

```
Aws::AssumeRoleWebIdentityCredentials.new(
  role_arn: "arn:aws:iam::<etc etc>",
  role_session_name: "test",
  web_identity_token_file: "/tmp/test_token", duration_seconds: 900,
  before_refresh: ->() { $stderr.puts "FREEEEEEEEEESH!" }
)
```

### Additional Information/Context

The problem appears to be that, if no `:client` option is provided, *all* of the options get passed to `STS::Client.new`, which has a massive sad panda about an option it doesn't understand.  If I pass a client, it works, so that's my workaround for now, but it seems less than ideal for an exception to be raised with a set of parameters which the documentation at least implies should work.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

3.130.1

### Environment details (Version of Ruby, OS environment)

Ruby 2.7.4, Linux.

**Comment by alextwoods** [comment]
Thanks for submitting this - that is a bug!  I'm working on a fix now.
