### ISSUE TITLE
Region and endpoint options appear to conflict in AWS clients

### ISSUE THREAD

**Issue by stouset** [aws/aws-sdk-ruby#2724]
### Describe the bug

We are unable to successfully invoke the SecretsManager client with both an explicit region and endpoint (for instance, when using a VPC endpoint).

```ruby
>> client = Aws::SecretsManager::Client.new(region: 'us-west-2', endpoint: endpoint)
opening connection to :...
opening connection to :...
opening connection to :...
opening connection to :...
Seahorse::Client::NetworkingError: Failed to open TCP connection to : (getaddrinfo: Name or service not known)
from /path/to/ruby/lib/ruby/3.0.0/net/http.rb:987:in `initialize'
```

Passing the region appears to be necessary to some degree. Without it, the client STS credential is scoped to the wrong region:

```ruby
>> client = Aws::SecretsManager::Client.new(endpoint: endpoint) 
opening connection to sts.us-east-1.amazonaws.com:443...
opened
…
=> #<Aws::SecretsManager::Client>

>> secret = client.get_secret_value(secret_id: 'foo')
opening connection to vpce-xxxxxxxxxxxxxxxxx-xxxxxxxx.secretsmanager.us-west-2.vpce.amazonaws.com:443...
opened
…
Aws::SecretsManager::Errors::InvalidSignatureException: Credential should be scoped to a valid region. 
from /path/to/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
```

As a workaround, we can pass `sigv4_region` instead of `region` which appears undocumented.

```ruby
>> client = Aws::SecretsManager::Client.new(endpoint: endpoint, sigv4_region: 'us-west-2')
opening connection to sts.us-east-1.amazonaws.com:443...
opened
…
=> #<Aws::SecretsManager::Client>

>> client.config.region
=> "us-east-1"

>> client.config.sigv4_region
=> "us-west-2"

>> secret = client.get_secret_value(secret_id: some_secret)
opening connection to vpce-xxxxxxxxxxxxxxxxx-xxxxxxxx.secretsmanager.us-west-2.vpce.amazonaws.com:443...
opened
…
=> #<struct Aws::SecretsManager::Types::GetSecretValueResponse …>
```

### Expected Behavior

Providing an `endpoint` and `region` should set the region for signing credentials and allow clients to call into AWS services.

### Current Behavior

When providing both options, It appears that the client fails to compute an STS endpoint correctly. This eventually results in an exception being raised.

### Reproduction Steps

Provided above. Pass both an `endpoint` and a `region` into the client.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core

### Environment details (Version of Ruby, OS environment)

Ruby 3.0

**Comment by alextwoods** [comment]
What credentials are you using? 

I wasn't able to reproduce with: `client = Aws::SecretsManager::Client.new(region: 'us-west-2', endpoint: endpoint)`, assuming that I am using a us-west-2 endpoint, it correctly connects and signs.    One general workaround would be to create your credentials explicitly:

```
credentials = ... # construct your credentials, maybe: AssumeRoleCredentials.new
client = Aws::SecretsManager::Client.new(region: 'us-west-2', endpoint: endpoint, credentials: credentials)
```

In your output, what is the "..." in `opening connection to :...`?

**Comment by stouset** [comment]
I'm not 100% certain what the source of my credentials is. I *believe* it's coming from `$AWS_WEB_IDENTITY_TOKEN_FILE` but if that's not it I can look further.

> In your output, what is the "..." in `opening connection to :...`?

That is the raw, unmodified output. I have not elided anything for privacy. This comes from

```ruby
begin
  TCPSocket.open(conn_addr, conn_port, @local_host, @local_port)
rescue => e
  raise e, "Failed to open TCP connection to " +
    "#{conn_addr}:#{conn_port} (#{e.message})"
end
```

In the debugger, `conn_addr` and `conn_port` are both `nil`.

**Comment by alextwoods** [comment]
Interesting - so it looks like in the first case (region/endpoint set), constructing the credentials is what is failing, though I'm not clear on why.  Do you have a larger stack trace for that failure (around `Seahorse::Client::NetworkingError: Failed to open TCP connection to : (getaddrinfo: Name or service not known)
from /path/to/ruby/lib/ruby/3.0.0/net/http.rb:987:in initialize`)?

Whats the output of:
```
client = Aws::SecretsManager::Client.new(endpoint: endpoint, sigv4_region: 'us-west-2')
client.config.credentials
```

**Comment by stouset** [comment]
Credentials:

```ruby
=> #<Aws::AssumeRoleWebIdentityCredentials:0x00007f799a49d7a0
 @assume_role_web_identity_params=
  {:role_arn=>"arn:aws:iam::REDACTED",
   :role_session_name=>"REDACTED",,
   :web_identity_token=> "REDACTED"},
 @async_refresh=true,
 @before_refresh=nil,
 @client=#<Aws::STS::Client>,
 @credentials=#<Aws::Credentials access_key_id="REDACTED">,
 @expiration=2022-07-05 19:13:12 UTC,
 @mutex=#<Thread::Mutex:0x00007f799a2ddc30>,
 @token_file="/var/run/secrets/eks.amazonaws.com/serviceaccount/token">
```

Full stack trace:

```
./ruby/lib/ruby/3.0.0/net/http.rb:987:in `initialize'
./ruby/lib/ruby/3.0.0/net/http.rb:987:in `open'
./ruby/lib/ruby/3.0.0/net/http.rb:987:in `block in connect'
./ruby/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
./ruby/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
./ruby/lib/ruby/3.0.0/net/http.rb:985:in `connect'
./ruby/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
./ruby/lib/ruby/3.0.0/net/http.rb:965:in `start'
./ruby/lib/ruby/3.0.0/delegate.rb:87:in `method_missing'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/net_http/connection_pool.rb:307:in `start_session'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/net_http/connection_pool.rb:100:in `session_for'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/net_http/handler.rb:128:in `session'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/net_http/handler.rb:76:in `transmit'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/net_http/handler.rb:50:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/plugins/content_length.rb:24:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/plugins/request_callback.rb:85:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/xml/error_handler.rb:10:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/transfer_encoding.rb:26:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:12:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/retry_errors.rb:360:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/retry_errors.rb:394:in `retry_request'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/retry_errors.rb:382:in `retry_if_possible'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/retry_errors.rb:394:in `retry_request'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/retry_errors.rb:382:in `retry_if_possible'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/retry_errors.rb:394:in `retry_request'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/retry_errors.rb:382:in `retry_if_possible'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/http_checksum.rb:19:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/endpoint_pattern.rb:30:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/checksum_algorithm.rb:136:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/query/handler.rb:30:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/recursion_detection.rb:18:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/endpoint_discovery.rb:80:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/plugins/endpoint.rb:47:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/param_validator.rb:26:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/plugins/raise_response_errors.rb:16:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/plugins/response_target.rb:24:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/request.rb:72:in `send_request'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-sts/client.rb:1558:in `assume_role_with_web_identity'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/assume_role_web_identity_credentials.rb:76:in `refresh'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/refreshing_credentials.rb:30:in `initialize'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/assume_role_web_identity_credentials.rb:64:in `initialize'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/credential_provider_chain.rb:152:in `new'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/credential_provider_chain.rb:152:in `assume_role_web_identity_credentials'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/credential_provider_chain.rb:13:in `block in resolve'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/credential_provider_chain.rb:12:in `each'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/credential_provider_chain.rb:12:in `resolve'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/credentials_configuration.rb:72:in `block in <class:CredentialsConfiguration>'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/configuration.rb:72:in `call'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/configuration.rb:219:in `block in resolve_defaults'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/configuration.rb:59:in `each'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/configuration.rb:59:in `each'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/configuration.rb:218:in `resolve_defaults'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/configuration.rb:211:in `value_at'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/configuration.rb:191:in `block in resolve'
./ruby/lib/ruby/3.0.0/set.rb:344:in `each_key'
./ruby/lib/ruby/3.0.0/set.rb:344:in `each'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/configuration.rb:191:in `resolve'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/configuration.rb:179:in `apply_defaults'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/configuration.rb:152:in `build!'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/base.rb:65:in `build_config'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/base.rb:22:in `initialize'
./bundle/ruby/3.0.0/gems/aws-sdk-secretsmanager-1.64.0/lib/aws-sdk-secretsmanager/client.rb:359:in `initialize'
./bundle/ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/seahorse/client/base.rb:102:in `new'
```

**Comment by alextwoods** [comment]
So it does look like you are using AssumeRoleWebIdentityCredentials, resolved by the provider chain from ENV (eg, you have AWS_ROLE_ARN/AWS_WEB_IDENTITY_TOKEN_FILE set) and the  AssumeRoleWebIdentityCredentials fetching of credentials is what is failing.  Setting `endpoint` on the top level client, shouldn't break creating the credentials, only region is passed through in the [CredentialProviderChain](https://github.com/aws/aws-sdk-ruby/blob/8f40db9a1888324446d3da64642dcec06c975b21/gems/aws-sdk-core/lib/aws-sdk-core/credential_provider_chain.rb#L146).  

Do you have the ability to debug/step into any of the sdk code?  If so, can you start with: 
```
client = Aws::SecretsManager::Client.new(region: 'us-west-2', endpoint: endpoint)
```

And then on line #63 of [assume_role_webidentity_credentials.rb](https://github.com/aws/aws-sdk-ruby/blob/8f40db9a1888324446d3da64642dcec06c975b21/gems/aws-sdk-core/lib/aws-sdk-core/assume_role_web_identity_credentials.rb#L63) print out the `@client` and `@client.config`?

**Comment by stouset** [comment]
```ruby
#<struct 
 access_key_id=nil,
 active_endpoint_cache=false,
 adaptive_retry_wait_to_fill=true,
 api=#<Seahorse::Model::Api>,
 client_rate_limiter=
  #<Aws::Plugins::Retries::ClientRateLimiter:0x00007f799a0bfd68
   @calculated_rate=nil,
   @current_capacity=0,
   @enabled=false,
   @fill_rate=nil,
   @last_max_rate=0,
   @last_throttle_time=86361.568,
   @last_timestamp=nil,
   @last_tx_rate_bucket=86361.568,
   @max_capacity=nil,
   @measured_tx_rate=0,
   @mutex=#<Thread::Mutex:0x00007f799a0bfd40>,
   @request_count=0>,
 client_side_monitoring=false,
 client_side_monitoring_client_id="",
 client_side_monitoring_host="127.0.0.1",
 client_side_monitoring_port=31000,
 client_side_monitoring_publisher=
  #<Aws::ClientSideMonitoring::Publisher:0x00007f799a0bf818
   @agent_host="127.0.0.1",
   @agent_port=nil,
   @mutex=#<Thread::Mutex:0x00007f799a0bf7c8>>,
 clock_skew=
  #<Aws::Plugins::Retries::ClockSkew:0x00007f799a0bf6d8
   @endpoint_clock_corrections={},
   @endpoint_estimated_skews={},
   @mutex=#<Thread::Mutex:0x00007f799a0bf6b0>>,
 convert_params=true,
 correct_clock_skew=true,
 credentials=false,
 defaults_mode="legacy",
 defaults_mode_config_resolver=
  #<Aws::DefaultsModeConfigResolver:0x00007f799a0bf2f0
   @cfg=
    #<Seahorse::Client::Configuration::DefaultResolver:0x00007f799a0c4368
     @members=
      #<Set: {:access_key_id,
       :active_endpoint_cache,
       :adaptive_retry_wait_to_fill,
       :api,
       :client_rate_limiter,
       :client_side_monitoring,
       :client_side_monitoring_client_id,
       :client_side_monitoring_host,
       :client_side_monitoring_port,
       :client_side_monitoring_publisher,
       :clock_skew,
       :convert_params,
       :correct_clock_skew,
       :credentials,
       :defaults_mode,
       :defaults_mode_config_resolver,
       :disable_host_prefix_injection,
       :endpoint,
       :endpoint_cache,
       :endpoint_cache_max_entries,
       :endpoint_cache_max_threads,
       :endpoint_cache_poll_interval,
       :endpoint_discovery,
       :http_continue_timeout,
       :http_idle_timeout,
       :http_open_timeout,
       :http_proxy,
       :http_read_timeout,
       :http_wire_trace,
       :instance_profile_credentials_retries,
       :instance_profile_credentials_timeout,
       :log_formatter,
       :log_level,
       :logger,
       :max_attempts,
       :on_chunk_sent,
       :profile,
       :raise_response_errors,
       :region,
       :regional_endpoint,
       :retry_backoff,
       :retry_base_delay,
       :retry_jitter,
       :retry_limit,
       :retry_max_delay,
       :retry_mode,
       :retry_quota,
       :secret_access_key,
       :session_token,
       :sigv4_name,
       :sigv4_region,
       :sigv4_signer,
       :ssl_ca_bundle,
       :ssl_ca_directory,
       :ssl_ca_store,
       :ssl_timeout,
       :ssl_verify_peer,
       :sts_regional_endpoints,
       :stub_responses,
       :unsigned_operations,
       :use_dualstack_endpoint,
       :use_fips_endpoint,
       :user_agent_suffix,
       :validate_params}>,
     @struct=#<struct :...>>,
   @mutex=#<Thread::Mutex:0x00007f799a0bf2c8>,
   @resolved_mode="legacy",
   @sdk_defaults=
    {"version"=>1,
     "base"=>
      {"retryMode"=>"standard",
       "stsRegionalEndpoints"=>"regional",
       "s3UsEast1RegionalEndpoints"=>"regional",
       "connectTimeoutInMillis"=>1100,
       "tlsNegotiationTimeoutInMillis"=>1100},
     "modes"=>
      {"standard"=>
        {"connectTimeoutInMillis"=>{"override"=>3100},
         "tlsNegotiationTimeoutInMillis"=>{"override"=>3100}},
       "in-region"=>{},
       "cross-region"=>
        {"connectTimeoutInMillis"=>{"override"=>3100},
         "tlsNegotiationTimeoutInMillis"=>{"override"=>3100}},
       "mobile"=>
        {"connectTimeoutInMillis"=>{"override"=>30000},
         "tlsNegotiationTimeoutInMillis"=>{"override"=>30000}}}}>,
 disable_host_prefix_injection=false,
 endpoint=#<URI::HTTPS https://sts.us-west-2.amazonaws.com>,
 endpoint_cache=
  #<Aws::EndpointCache:0x00007f799a0be4e0
   @entries={},
   @max_entries=1000,
   @max_threads=10,
   @mutex=#<Thread::Mutex:0x00007f799a0be440>,
   @pool={},
   @require_identifier=nil>,
 endpoint_cache_max_entries=1000,
 endpoint_cache_max_threads=10,
 endpoint_cache_poll_interval=60,
 endpoint_discovery=false,
 http_continue_timeout=1,
 http_idle_timeout=5,
 http_open_timeout=15,
 http_proxy=nil,
 http_read_timeout=60,
 http_wire_trace=false,
 instance_profile_credentials_retries=0,
 instance_profile_credentials_timeout=1,
 log_formatter=nil,
 log_level=:info,
 logger=nil,
 max_attempts=3,
 on_chunk_sent=nil,
 profile=nil,
 raise_response_errors=true,
 region="us-west-2",
 regional_endpoint=true,
 retry_backoff=
  #<Proc:0x00007f79a334b830 ./ruby/3.0.0/gems/aws-sdk-core-3.131.2/lib/aws-sdk-core/plugins/retry_errors.rb:29 (lambda)>,
 retry_base_delay=0.3,
 retry_jitter=:none,
 retry_limit=3,
 retry_max_delay=0,
 retry_mode="legacy",
 retry_quota=
  #<Aws::Plugins::Retries::RetryQuota:0x00007f799a0bd478
   @available_capacity=500,
   @max_capacity=500,
   @mutex=#<Thread::Mutex:0x00007f799a0bd428>>,
 secret_access_key=nil,
 session_token=nil,
 sigv4_name="sts",
 sigv4_region="us-west-2",
 sigv4_signer=
  #<Aws::Plugins::SignatureV4::MissingCredentialsSigner:0x00007f799a0bc2a8>,
 ssl_ca_bundle=nil,
 ssl_ca_directory=nil,
 ssl_ca_store=nil,
 ssl_timeout=nil,
 ssl_verify_peer=true,
 sts_regional_endpoints="regional",
 stub_responses=false,
 unsigned_operations=[:assume_role_with_saml, :assume_role_with_web_identity],
 use_dualstack_endpoint=false,
 use_fips_endpoint=false,
 user_agent_suffix=nil,
 validate_params=true>
```

**Comment by stouset** [comment]
The `@client` had no interesting debug output.

**Comment by alextwoods** [comment]
Thanks!  Sorry for all the back and forth, I'm a bit stumped on this.

Thats interesting, that config looks correct and shouldn't have produced `Failed to open TCP connection to : `.  I was expecting an invalid endpoint of some sort in the STS client config.  

Lets see if we can create the credentials independently.  Whats the output of:
```
CredentialProviderChain.new.send(:assume_role_web_identity_credentials, {region: 'us-west-2'})

CredentialProviderChain.new.send(:assume_role_web_identity_credentials, {region: 'us-west-2', endpoint: endpoint})

```

**Comment by stouset** [comment]
No worries! I'm happy to be here to assist.

Both succeed.

```ruby
=> #<Aws::AssumeRoleWebIdentityCredentials:0x00007f799b9c7018
 @assume_role_web_identity_params=
  {:role_arn=>"arn:aws:iam::REDACTED",
   :role_session_name=>"REDACTED",
   :web_identity_token=> "REDACTED"},
 @async_refresh=true,
 @before_refresh=nil,
 @client=#<Aws::STS::Client>,
 @credentials=#<Aws::Credentials access_key_id="REDACTED">,
 @expiration=2022-07-05 19:59:27 UTC,
 @mutex=#<Thread::Mutex:0x00007f7999b1d6a8>,
 @token_file="/var/run/secrets/eks.amazonaws.com/serviceaccount/token">
```

**Comment by mullermp** [comment]
By chance do you have networking/routing settings on your EKS instance that's blocking STS `us-west-2` (you're in a container it seems)?? It looks like you were able to fetch credentials using us-east-1 but then that region was passed through to both STS and Secrets Manager.

What happens if you create AssumeRoleWebIdentityCredentials manually using us-east-1, and pass it into your SecretsManager client using us-west-2?

**Comment by stouset** [comment]
> By chance do you have networking/routing settings on your EKS instance that's blocking STS us-west-2 (you're in a container it seems)?

I think we're on to something here. Give me a bit to investigate.

> What happens if you create AssumeRoleWebIdentityCredentials manually using us-east-1, and pass it into your SecretsManager client using us-west-2?

Success.

**Comment by stouset** [comment]
```
bash-4.2$ curl -vv https://sts.us-west-2.amazonaws.com/
* Uses proxy env variable no_proxy == '.sts.us-west-2.amazonaws.com,172.20.0.0/16,localhost,127.0.0.1,localaddress,localdomain.com,square,vip,10.0.0.0/8'
*   Trying 54.240.250.235:443...

**Comment by stouset** [comment]
```
bash-4.2$ curl -vv https://sts.us-west-2.amazonaws.com/
* Uses proxy env variable no_proxy == '.sts.us-west-2.amazonaws.com,172.20.0.0/16,localhost,127.0.0.1,localaddress,localdomain.com,10.0.0.0/8'
*   Trying 54.240.250.235:443...
```

**Comment by mullermp** [comment]
>.sts.us-west-2.amazonaws.com

Is the dot (.) in front of this intentional or expected? I'm glad us-east-1 worked for you! But it seems like you have some host/env level settings that are causing problems.

**Comment by stouset** [comment]
So, setting aside your question (I don't have an answer just yet), there definitely does seem to be something here related to proxy configuration.

Forcing a request to go through the proxy to reach STS, we succeed.

```
bash-4.2$ env no_proxy= curl -v https://sts.us-west-2.amazonaws.com/
* Uses proxy env variable https_proxy == '{{username }}:{{ password }}@{{ proxyhost }}:{{ proxyport }}'
*   Trying 10.163.238.44:{{ proxyport }}...
* Connected to {{ proxyhost }} (10.163.238.44) port {{ proxyport }} (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to sts.us-west-2.amazonaws.com:443
* Proxy auth using Basic with user '{{ username }}'
> CONNECT sts.us-west-2.amazonaws.com:443 HTTP/1.1
> Host: sts.us-west-2.amazonaws.com:443
> Proxy-Authorization: REDACTED
> User-Agent: curl/7.71.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 OK
< date: Tue, 05 Jul 2022 21:18:18 GMT
< 
> GET / HTTP/1.1
> Host: sts.us-west-2.amazonaws.com
> User-Agent: curl/7.71.1
> Accept: */*
> 
< HTTP/1.1 302 Found
< Location: https://aws.amazon.com/iam
< Content-Length: 0
< Date: Tue, 05 Jul 2022 21:18:18 GMT
< 
```

Doing the same from within Ruby does not.

```ruby
contentful-agent:staging [4] pry(main)> ENV.delete('no_proxy')
=> nil
contentful-agent:staging [5] pry(main)> Aws::SecretsManager::Client.new(endpoint: vpce, region: 'us-west-2')
opening connection to :...
opening connection to :...
opening connection to :...
```

Do you have offhand a snippet I can use to test the STS client directly for this, instead of indirectly through a `SecretsManager` client?

**Comment by mullermp** [comment]
You can use `Aws::STS::Client`

**Comment by stouset** [comment]
```ruby
>> ENV['AWS_REGION']
=> "us-east-1"

> Aws::STS::Client.new
=> #<Aws::STS::Client>

>> Aws::STS::Client.new(region: 'us-west-2')
opening connection to :...
opening connection to :...
opening connection to :...
opening connection to :...
Seahorse::Client::NetworkingError: Failed to open TCP connection to : (getaddrinfo: Name or service not known)
```

**Comment by stouset** [comment]
Seems like maybe this is the appropriate approach:

```
>> Aws::SecretsManager::Client.new(
  endpoint: vpce,
  region: 'us-west-2',
  credentials: Aws::CredentialProviderChain.new.resolve
)
=> #<Aws::SecretsManager::Client>
```

Otherwise we'd need to somehow provide our VPCE for STS to override `sts.us-west-2.amazonaws.com`. This way we look up the credentials in the current region and make a cross-region API request.

**Comment by mullermp** [comment]
You should be able to create an instance of AssumeRoleWebIdentityCredentials using the STS client created with us-east-1. But you shouldn't have to do that if you can figure out why us-west-2 calls are not working on your instance! Is cross-region somehow disabled? Or I suppose if you are rolling your own proxy, there be dragons.

**Comment by stouset** [comment]
Cross-region calls are disabled. The reason for the `.`-prefixed domain name for STS is that cross-region STS calls are apparently supposed to use VPC endpoints instead of the global ones.

Is there a way to provide options down into the instantiated STS client, to ensure *it* uses a VPC endpoint?

**Comment by mullermp** [comment]
Yes. You can do that similar to what I stated above. Create your own STS client with your region/vpc endpoint, then pass it as the :client option to AssumeRoleWebIdentityCredentials, then pass that as the :credentials option to your SecretsManager client.

**Comment by stouset** [comment]
Is there a reason to prefer making STS requests to the region you're making API requests to as opposed to your local region when doing a cross-region request? e.g., if I'm in `us-east-1` making a request to `us-west-2`, is there a reason to prefer talking to STS in either `us-west-2` over `us-east-1`?

**Comment by alextwoods** [comment]
Sigv4 credentials are region agnostic, so I dont think theres a reason to prefer making STS requests to the region you're using the credentials to make an API request with.  I think in general you'd prefer to stay in-region as much as possible.  In your example, in `us-east-1`, I'd prefer using STS in `us-east-1` even when using those credentials to make cross region calls to `us-west-2`.

**Comment by stouset** [comment]
In that case it seems the approach above (pasted again for reference) is probably the most straightforward.

```ruby
>> Aws::SecretsManager::Client.new(
  endpoint: vpce,
  region: 'us-west-2',
  credentials: Aws::CredentialProviderChain.new.resolve
)
```

I'll go ahead and close this out, since it's an issue with our own local configuration and not a bug in the AWS SDK. Thank you for your assistance!

**Comment by mullermp** [comment]
Sounds good. The credential provider chain is technically a private API. We recommend creating the assume role web identity credentials class instead.
