### ISSUE TITLE
aws-sdk-apigatewayv2 Internal Server Error

### ISSUE THREAD

**Issue by boris154** [aws/aws-sdk-ruby#2752]
### Describe the bug

The 'aws-sdk-apigatewayv2' SDK return `Aws::ApiGatewayV2::Errors::InternalServerErrorException (Internal server error)` when executing `.get_domain_names`

```ruby
2.7.0 :006 > Aws::ApiGatewayV2::Client.new(region: 'us-east-1').get_domain_names
Traceback (most recent call last):
       16: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/bin/ruby_executable_hooks:22:in `eval'
       15: from /Users/boris/.rvm/gems/ruby-2.7.6/bin/irb:23:in `<main>'
       14: from /Users/boris/.rvm/gems/ruby-2.7.6/bin/irb:23:in `load'
       13: from /Users/boris/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
       12: from (irb):5
       11: from (irb):6:in `rescue in irb_binding'
       10: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-apigatewayv2-1.42.0/lib/aws-sdk-apigatewayv2/client.rb:2389:in `get_domain_names'
        9: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/seahorse/client/request.rb:72:in `send_request'
        8: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
        7: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
        6: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
        5: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
        4: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
        3: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
        2: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
        1: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
Aws::ApiGatewayV2::Errors::InternalServerErrorException (Internal server error)
2.7.0 :007 > Aws::ApiGatewayV2::Client.new(region: 'eu-central-1').get_domain_names
Traceback (most recent call last):
       16: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/bin/ruby_executable_hooks:22:in `eval'
       15: from /Users/boris/.rvm/gems/ruby-2.7.6/bin/irb:23:in `<main>'
       14: from /Users/boris/.rvm/gems/ruby-2.7.6/bin/irb:23:in `load'
       13: from /Users/boris/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
       12: from (irb):6
       11: from (irb):7:in `rescue in irb_binding'
       10: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-apigatewayv2-1.42.0/lib/aws-sdk-apigatewayv2/client.rb:2389:in `get_domain_names'
        9: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/seahorse/client/request.rb:72:in `send_request'
        8: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
        7: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
        6: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
        5: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
        4: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
        3: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
        2: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
        1: from /private/tmp/aws-apgw-test/vendor/ruby/2.7.0/gems/aws-sdk-core-3.145.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
Aws::ApiGatewayV2::Errors::InternalServerErrorException (Internal server error)
```

Gemfile:
```text
source "https://rubygems.org"

gem  'aws-sdk-apigatewayv2'
```

Gemfile.lock:
```text
GEM
  remote: https://rubygems.org/
  specs:
    aws-eventstream (1.2.0)
    aws-partitions (1.628.0)
    aws-sdk-apigatewayv2 (1.42.0)
      aws-sdk-core (~> 3, >= 3.127.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-core (3.145.0)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.525.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1, >= 1.6.1)
    aws-sigv4 (1.5.1)
      aws-eventstream (~> 1, >= 1.0.2)
    jmespath (1.6.1)

PLATFORMS
  arm64-darwin-21

DEPENDENCIES
  aws-sdk-apigatewayv2

BUNDLED WITH
   2.2.30
```

### Expected Behavior

To get the domain names

### Current Behavior

raises `Aws::ApiGatewayV2::Errors::InternalServerErrorException (Internal server error)`

### Reproduction Steps

Create Gemfile with the SDK
```bash
cat > Gemfile << EOL
source "https://rubygems.org"

gem  'aws-sdk-apigatewayv2'
EOL
```

Use bundle to install all dependencies to local vendor
```bash
bundle install --path=vendor
```

Test with IRB
```bash
bundle exec irb
```
```ruby
require 'aws-sdk-apigatewayv2'

Aws::ApiGatewayV2::Client.new(region: 'us-east-1').get_domain_names()
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-apigatewayv2 == 1.42.0

### Environment details (Version of Ruby, OS environment)

MacOS and Linux, RVM with Ruby version 2.7.6

**Comment by mullermp** [comment]
I'm not able to reproduce this - I get back `struct Aws::ApiGatewayV2::Types::GetDomainNamesResponse`. Are you still seeing the issue? (Was the service down at the time, perhaps?) If so, can you enable wire logging with `http_wire_trace: true` so we can see what's going on?

**Comment by boris154** [comment]
@mullermp 
The issue is still there and I can reproduce it.
Here is the wire logging (removed some of the sensitive information):
```ruby
-> % bundle exec irb
2.7.0 :001 > require 'aws-sdk-apigatewayv2'
 => true
2.7.0 :002 > Aws::ApiGatewayV2::Client.new(region: 'us-east-1', http_wire_trace: true).get_domain_names()
opening connection to apigateway.us-east-1.amazonaws.com:443...
opened
starting SSL for apigateway.us-east-1.amazonaws.com:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "GET /v2/domainnames HTTP/1.1\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.145.0 ruby/2.7.6 arm64-darwin21 aws-sdk-apigatewayv2/1.42.0\r\nHost: apigateway.us-east-1.amazonaws.com\r\nX-Amz-Date: 20220913T143902Z\r\nX-Amz-Security-Token: XXX\r\nX-Amz-Content-Sha256: aaaaa\r\nAuthorization: AWS4-HMAC-SHA256 Credential=XXX/20220913/us-east-1/apigateway/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=bbbbb\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 502 Bad Gateway\r\n"
-> "Date: Tue, 13 Sep 2022 14:39:05 GMT\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 36\r\n"
-> "Connection: keep-alive\r\n"
-> "x-amzn-RequestId: a7ab996b-70ad-4d1f-8935-a14e80e842e7\r\n"
-> "Access-Control-Allow-Origin: *\r\n"
-> "x-amzn-ErrorType: InternalServerErrorException\r\n"
-> "x-amz-apigw-id: YZxhdHiRIAMF_ng=\r\n"
-> "X-Amzn-Trace-Id: Root=1-63209609-7b3dde5c250ceb6c7d7b6df3\r\n"
-> "\r\n"
reading 36 bytes...
-> "{\"message\": \"Internal server error\"}"
read 36 bytes
Conn keep-alive
```

I also tried this functionality with boto3 and it works with python.

Update:
On a different region, one that I don't have API GWs, I get a successful response:
```ruby
2.7.0 :004 > Aws::ApiGatewayV2::Client.new(region: 'eu-west-1', http_wire_trace: true).get_domain_names()
opening connection to apigateway.eu-west-1.amazonaws.com:443...
opened
starting SSL for apigateway.eu-west-1.amazonaws.com:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "GET /v2/domainnames HTTP/1.1\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.145.0 ruby/2.7.6 arm64-darwin21 aws-sdk-apigatewayv2/1.42.0\r\nHost: apigateway.eu-west-1.amazonaws.com\r\nX-Amz-Date: 20220913T145108Z\r\nX-Amz-Security-Token: XXX\r\nX-Amz-Content-Sha256: aaaa\r\nAuthorization: AWS4-HMAC-SHA256 Credential=XXX/20220913/eu-west-1/apigateway/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=bbbb\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "Date: Tue, 13 Sep 2022 14:51:11 GMT\r\n"
-> "Content-Type: application/hal+json\r\n"
-> "Content-Length: 12\r\n"
-> "Connection: keep-alive\r\n"
-> "x-amzn-RequestId: 1134b672-4407-4bdf-9711-8ccee0e2955b\r\n"
-> "x-amzn-Remapped-x-amzn-RequestId: 1134b672-4407-4bdf-9711-8ccee0e2955b\r\n"
-> "Access-Control-Allow-Origin: *\r\n"
-> "x-amzn-Remapped-Content-Length: 320\r\n"
-> "x-amzn-Remapped-Connection: keep-alive\r\n"
-> "x-amz-apigw-id: YZzS4EWnDoEFsqg=\r\n"
-> "Access-Control-Expose-Headers: x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date\r\n"
-> "X-Amzn-Trace-Id: Root=1-632098df-6c078d565888566a0e43ea4a\r\n"
-> "x-amzn-Remapped-Date: Tue, 13 Sep 2022 14:51:11 GMT\r\n"
-> "\r\n"
reading 12 bytes...
-> "{\"items\":[]}"
read 12 bytes
Conn keep-alive
 => #<struct Aws::ApiGatewayV2::Types::GetDomainNamesResponse items=[], next_token=nil>
```

**Comment by mullermp** [comment]
That is strange. I do not have an API gateway setup. For a region that does not work with Ruby, can you similarly gather debug information from Python so we can compare the request body and headers? For some reason, the service does not like the Ruby SDK's request in those regions where you have domain names.

**Comment by boris154** [comment]
Here are the logs with the python boto3:
```text
2022-09-14 09:31:18,426 botocore.hooks [DEBUG] Event before-parameter-build.apigatewayv2.GetDomainNames: calling handler <function generate_idempotent_uuid at 0x101b66430>
2022-09-14 09:31:18,427 botocore.hooks [DEBUG] Event before-call.apigatewayv2.GetDomainNames: calling handler <function add_recursion_detection_header at 0x101b660d0>
2022-09-14 09:31:18,427 botocore.hooks [DEBUG] Event before-call.apigatewayv2.GetDomainNames: calling handler <function inject_api_version_header_if_needed at 0x101b67ca0>
2022-09-14 09:31:18,427 botocore.endpoint [DEBUG] Making request for OperationModel(name=GetDomainNames) with params: {'url_path': '/v2/domainnames', 'query_string': {}, 'method': 'GET', 'headers': {'User-Agent': 'Boto3/1.24.53 Python/3.9.13 Darwin/21.5.0 Botocore/1.27.53'}, 'body': b'', 'url': 'https://apigateway.us-east-1.amazonaws.com/v2/domainnames', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x1023818e0>, 'has_streaming_input': False, 'auth_type': None}}
2022-09-14 09:31:18,428 botocore.hooks [DEBUG] Event request-created.apigatewayv2.GetDomainNames: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x102381730>>
2022-09-14 09:31:18,429 botocore.hooks [DEBUG] Event choose-signer.apigatewayv2.GetDomainNames: calling handler <function set_operation_specific_signer at 0x101b66310>
2022-09-14 09:31:18,429 botocore.auth [DEBUG] Calculating signature using v4 auth.
2022-09-14 09:31:18,429 botocore.auth [DEBUG] CanonicalRequest:
GET
/v2/domainnames

host:apigateway.us-east-1.amazonaws.com
x-amz-date:20220914T063118Z
x-amz-security-token:XXX

host;x-amz-date;x-amz-security-token
aaaa
2022-09-14 09:31:18,430 botocore.auth [DEBUG] StringToSign:
AWS4-HMAC-SHA256
20220914T063118Z
20220914/us-east-1/apigateway/aws4_request
bbbb
2022-09-14 09:31:18,430 botocore.auth [DEBUG] Signature:
aaaa
2022-09-14 09:31:18,430 botocore.hooks [DEBUG] Event request-created.apigatewayv2.GetDomainNames: calling handler <function add_retry_headers at 0x101b6c3a0>
2022-09-14 09:31:18,430 botocore.endpoint [DEBUG] Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=https://apigateway.us-east-1.amazonaws.com/v2/domainnames, headers={'User-Agent': b'Boto3/1.24.53 Python/3.9.13 Darwin/21.5.0 Botocore/1.27.53', 'X-Amz-Date': b'20220914T063118Z', 'X-Amz-Security-Token': b'XXX', 'Authorization': b'AWS4-HMAC-SHA256 Credential=XXX/20220914/us-east-1/apigateway/aws4_request, SignedHeaders=host;x-amz-date;x-amz-security-token, Signature=aaaa', 'amz-sdk-invocation-id': b'61554be7-4ce5-43b5-af46-a3c5dc8b35d7', 'amz-sdk-request': b'attempt=1'}>
2022-09-14 09:31:18,437 botocore.httpsession [DEBUG] Certificate path: /opt/homebrew/lib/python3.9/site-packages/certifi/cacert.pem
2022-09-14 09:31:19,631 botocore.parsers [DEBUG] Response headers: {'Date': 'Wed, 14 Sep 2022 06:31:19 GMT', 'Content-Type': 'application/json', 'Content-Length': '2998', 'Connection': 'keep-alive', 'x-amzn-RequestId': 'a6e102d2-c943-4880-89b9-1cdfc22414bc', 'x-amzn-Remapped-x-amzn-RequestId': 'a6e102d2-c943-4880-89b9-1cdfc22414bc', 'Access-Control-Allow-Origin': '*', 'x-amzn-Remapped-Content-Length': '2130', 'x-amzn-Remapped-Connection': 'keep-alive', 'x-amz-apigw-id': 'Yb9AsHfzIAMFsVQ=', 'Access-Control-Expose-Headers': 'x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date', 'X-Amzn-Trace-Id': 'Root=1-63217537-39284671041419a96f8fbd86', 'x-amzn-Remapped-Date': 'Wed, 14 Sep 2022 06:31:19 GMT'}
2022-09-14 09:31:19,631 botocore.parsers [DEBUG] Response body:
b'{"items":[...],"nextToken":null}'
2022-09-14 09:31:19,636 botocore.hooks [DEBUG] Event needs-retry.apigatewayv2.GetDomainNames: calling handler <botocore.retryhandler.RetryHandler object at 0x1023b72b0>
2022-09-14 09:31:19,636 botocore.retryhandler [DEBUG] No retry needed.
{'ResponseMetadata': {'RequestId': 'a6e102d2-c943-4880-89b9-1cdfc22414bc', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Wed, 14 Sep 2022 06:31:19 GMT', 'content-type': 'application/json', 'content-length': '2998', 'connection': 'keep-alive', 'x-amzn-requestid': 'a6e102d2-c943-4880-89b9-1cdfc22414bc', 'x-amzn-remapped-x-amzn-requestid': 'a6e102d2-c943-4880-89b9-1cdfc22414bc', 'access-control-allow-origin': '*', 'x-amzn-remapped-content-length': '2130', 'x-amzn-remapped-connection': 'keep-alive', 'x-amz-apigw-id': 'Yb9AsHfzIAMFsVQ=', 'access-control-expose-headers': 'x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date', 'x-amzn-trace-id': 'Root=1-63217537-39284671041419a96f8fbd86', 'x-amzn-remapped-date': 'Wed, 14 Sep 2022 06:31:19 GMT'}, 'RetryAttempts': 0}, 'Items': [...]}
```

Digging a bit more from my side, the first occurrence of this error started to show on Friday, Sep 9. Before that the tools we have that uses this API were working properly.

Should I open an AWS ticket as well ?

**Comment by mullermp** [comment]
You should probably open an AWS ticket, yes. If it was working for the Ruby SDK before, and it isn't currently, it's very likely a service or user error issue, and not SDK.

**Comment by mullermp** [comment]
The requests look similar. Ruby SDK uses a blank accept-encoding and also signs x-amz-content-sha256, but neither of those should break your API.

**Comment by mullermp** [comment]
Do you have any update on this?

**Comment by boris154** [comment]
Update: the issue was solved, it was something on AWS side with the API GW service.
