### ISSUE TITLE
presigned_url method not returning URL specified as an endpoint in Aws::S3::Client.new

### ISSUE THREAD

**Issue by majksner** [aws/aws-sdk-ruby#2776]
### Describe the bug

After upgrading `aws-sdk-s3` from `1.116.0` to `1.117.0`
`presigned_url` method returns different URL then specified endpoint in `Aws::S3::Client.new(endpoint: 'http://127.0.0.1:9000')`

### Expected Behavior

`presigned_url` method should return the same URL as specified in `Aws::S3::Client.new(endpoint: 'http://127.0.0.1:9000')`

### Current Behavior

```ruby
Loading development environment (Rails 7.0.4)
[1] pry(main)> s3_options = {
  access_key_id: 'omitted',
  secret_access_key: 'omitted',
  region: 'us-east-1',
  force_path_style: true,
  endpoint: 'http://127.0.0.1:9000'
[1] pry(main)> s3_options = {
  access_key_id: 'omitted',
  secret_access_key: 'omitted',
  region: 'us-east-1',
  force_path_style: true,
  endpoint: 'http://127.0.0.1:9000'
}
=> {:access_key_id=>"omitted", :secret_access_key=>"omitted", :region=>"us-east-1", :force_path_style=>true, :endpoint=>"http://127.0.0.1:9000"}
[2] pry(main)> client = Aws::S3::Client.new(**s3_options)
=> #<Aws::S3::Client>
[3] pry(main)> bucket = Aws::S3::Bucket.new(name: 'test', client: client)
=> #<Aws::S3::Bucket:0x000000010cfe4900 @client=#<Aws::S3::Client>, @data=nil, @name="test", @waiter_block_warned=false>
[4] pry(main)> bucket.object('dev/uploaded_files/2/1/file.txt').public_url
=> "http://127.0.0.1:9000/test/dev/uploaded_files/2/1/file.txt"
[5] pry(main)> puts Gem.loaded_specs["aws-sdk-s3"].version
1.117.0
=> nil
[6] pry(main)> bucket.object('dev/uploaded_files/2/1/file.txt').presigned_url(:get)
[Aws::S3::Client 0 0.003465 0 retries] get_object(bucket:"test",key:"dev/uploaded_files/2/1/file.txt")

=> "http://127.0.0.1:443/test/dev/uploaded_files/2/1/file.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=omitted%2F20221026%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221026T141728Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=3e7f44373b74f565086fc9dbe3717f7872e054d5ab554a238b4e12d977ed806b"
```

Notice that URL is `http://127.0.0.1:443/`

### Reproduction Steps

```ruby
Loading development environment (Rails 7.0.4)
[1] pry(main)> s3_options = {
  access_key_id: 'omitted',
  secret_access_key: 'omitted',
  region: 'us-east-1',
  force_path_style: true,
  endpoint: 'http://127.0.0.1:9000'
[1] pry(main)> s3_options = {
  access_key_id: 'omitted',
  secret_access_key: 'omitted',
  region: 'us-east-1',
  force_path_style: true,
  endpoint: 'http://127.0.0.1:9000'
}
=> {:access_key_id=>"omitted", :secret_access_key=>"omitted", :region=>"us-east-1", :force_path_style=>true, :endpoint=>"http://127.0.0.1:9000"}
[2] pry(main)> client = Aws::S3::Client.new(**s3_options)
=> #<Aws::S3::Client>
[3] pry(main)> bucket = Aws::S3::Bucket.new(name: 'test', client: client)
=> #<Aws::S3::Bucket:0x000000010cfe4900 @client=#<Aws::S3::Client>, @data=nil, @name="test", @waiter_block_warned=false>
[4] pry(main)> bucket.object('dev/uploaded_files/2/1/file.txt').public_url
=> "http://127.0.0.1:9000/test/dev/uploaded_files/2/1/file.txt"
[5] pry(main)> puts Gem.loaded_specs["aws-sdk-s3"].version
1.117.0
=> nil
[6] pry(main)> bucket.object('dev/uploaded_files/2/1/file.txt').presigned_url(:get)
[Aws::S3::Client 0 0.003465 0 retries] get_object(bucket:"test",key:"dev/uploaded_files/2/1/file.txt")

=> "http://127.0.0.1:443/test/dev/uploaded_files/2/1/file.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=omitted%2F20221026%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221026T141728Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=3e7f44373b74f565086fc9dbe3717f7872e054d5ab554a238b4e12d977ed806b"
```

### Additional Information/Context

Previous version of `aws-sdk-s3` 1.116.0 works as expected

```ruby
[1] pry(main)> s3_options = {
  access_key_id: 'omitted',
  secret_access_key: 'omitted',
  region: 'us-east-1',
  force_path_style: true,
  endpoint: 'http://127.0.0.1:9000'
[1] pry(main)> s3_options = {
  access_key_id: 'omitted',
  secret_access_key: 'omitted',
  region: 'us-east-1',
  force_path_style: true,
  endpoint: 'http://127.0.0.1:9000'
}
=> {:access_key_id=>"omitted", :secret_access_key=>"omitted", :region=>"us-east-1", :force_path_style=>true, :endpoint=>"http://127.0.0.1:9000"}
[2] pry(main)> client = Aws::S3::Client.new(**s3_options)
=> #<Aws::S3::Client>
[3] pry(main)> bucket = Aws::S3::Bucket.new(name: 'test', client: client)
=> #<Aws::S3::Bucket:0x000000010a7a63d0 @arn=nil, @client=#<Aws::S3::Client>, @data=nil, @name="test", @resolved_region="us-east-1", @waiter_block_warned=false>
[4] pry(main)> bucket.object('dev/uploaded_files/2/1/file.txt').presigned_url(:get)
[Aws::S3::Client 0 0.001746 0 retries] get_object(bucket:"test",key:"dev/uploaded_files/2/1/file.txt")

=> "http://127.0.0.1:9000/test/dev/uploaded_files/2/1/file.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=omitted%2F20221026%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221026T142705Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=3aa31157a05f8e7af15dcc867909c13fb954820d6a0e1d89583c403c8756ad44"
[5] pry(main)> puts Gem.loaded_specs["aws-sdk-s3"].version
1.116.0
=> nil
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3, 1.117.0

### Environment details (Version of Ruby, OS environment)

Ruby 3.1.2, MacOS Ventura

**Comment by mullermp** [comment]
We're very sorry about the regression. All AWS SDKs now resolve endpoints from a model file. We are investigating and will try to get a fix out as soon as we can.

**Comment by majksner** [comment]
Thanks for the quick response!

**Comment by mullermp** [comment]
It should be released around noon PST

**Comment by dylanfisher** [comment]
Was this fixed? I'm still running into a regression upgrading `aws-sdk-s3` from `1.116.0` to `1.117.1`

```
Started OPTIONS "/s3/multipart" for ::1 at 2022-10-28 14:06:17 -0400
Started POST "/s3/multipart" for ::1 at 2022-10-28 14:06:17 -0400
Started GET "/s3/multipart/2dgJXK_jwzLTopZAtAO4UldI3JUqvv_yARvv.ebEf1WDL8aUp0aYURAUAfPAF0VUR5zxXoJvFA1YrB48UNZSCF8bXCq1BIXSCVxVzfvI9IDYjmUnW_vZEdjAEMBi89SX/1?key=cache%2F1c37e3a8e2e184b211a9c11621522cc4.jpg" for ::1 at 2022-10-28 14:06:17 -0400
  
NameError (uninitialized constant #<Class:NilClass>::PARAM_MAP

        if parameters.class.singleton_class::PARAM_MAP.key?(@ref)
                                           ^^^^^^^^^^^):
  
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/reference.rb:14:in `resolve'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/function.rb:19:in `block in call'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/function.rb:17:in `each'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/function.rb:17:in `call'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/condition.rb:20:in `match?'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/tree_rule.rb:22:in `block in match'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/tree_rule.rb:21:in `all?'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/tree_rule.rb:21:in `match'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/tree_rule.rb:33:in `block in resolve_rules'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/tree_rule.rb:32:in `each'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/tree_rule.rb:32:in `resolve_rules'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/tree_rule.rb:26:in `match'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/rules_provider.rb:25:in `block in resolve_rules'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/rules_provider.rb:24:in `each'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/rules_provider.rb:24:in `resolve_rules'
aws-sdk-core (3.166.0) lib/aws-sdk-core/endpoints/rules_provider.rb:10:in `resolve_endpoint'
aws-sdk-s3 (1.117.1) lib/aws-sdk-s3/endpoint_provider.rb:26:in `resolve_endpoint'
aws-sdk-s3 (1.117.1) lib/aws-sdk-s3/plugins/endpoints.rb:31:in `call'
aws-sdk-core (3.166.0) lib/aws-sdk-core/plugins/endpoint_discovery.rb:84:in `call'
aws-sdk-core (3.166.0) lib/seahorse/client/plugins/endpoint.rb:47:in `call'
aws-sdk-core (3.166.0) lib/aws-sdk-core/plugins/param_validator.rb:26:in `call'
aws-sdk-core (3.166.0) lib/seahorse/client/plugins/raise_response_errors.rb:16:in `call'
aws-sdk-s3 (1.117.1) lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
aws-sdk-s3 (1.117.1) lib/aws-sdk-s3/plugins/dualstack.rb:21:in `call'
aws-sdk-s3 (1.117.1) lib/aws-sdk-s3/plugins/accelerate.rb:43:in `call'
aws-sdk-core (3.166.0) lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
aws-sdk-core (3.166.0) lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
aws-sdk-core (3.166.0) lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
aws-sdk-core (3.166.0) lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
aws-sdk-core (3.166.0) lib/seahorse/client/plugins/request_callback.rb:71:in `call'
aws-sdk-core (3.166.0) lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
aws-sdk-core (3.166.0) lib/seahorse/client/plugins/response_target.rb:24:in `call'
aws-sdk-s3 (1.117.1) lib/aws-sdk-s3/presigner.rb:185:in `block in handle_presigned_url_context'
aws-sdk-core (3.166.0) lib/seahorse/client/request.rb:72:in `send_request'
aws-sdk-s3 (1.117.1) lib/aws-sdk-s3/presigner.rb:146:in `_presigned_request'
aws-sdk-s3 (1.117.1) lib/aws-sdk-s3/presigner.rb:78:in `presigned_url'
uppy-s3_multipart (1.2.0) lib/uppy/s3_multipart/client.rb:28:in `prepare_upload_part'
uppy-s3_multipart (1.2.0) lib/uppy/s3_multipart/app.rb:145:in `client_call'
uppy-s3_multipart (1.2.0) lib/uppy/s3_multipart/app.rb:95:in `block (2 levels) in <class:Router>'
roda (3.61.0) lib/roda/request.rb:592:in `if_match'
roda (3.61.0) lib/roda/request.rb:521:in `_verb'
roda (3.61.0) lib/roda/request.rb:104:in `get'
uppy-s3_multipart (1.2.0) lib/uppy/s3_multipart/app.rb:92:in `block in <class:Router>'
roda (3.61.0) lib/roda.rb:518:in `_roda_run_main_route'
roda (3.61.0) lib/roda.rb:496:in `block in _roda_handle_main_route'
roda (3.61.0) lib/roda.rb:494:in `catch'
roda (3.61.0) lib/roda.rb:494:in `_roda_handle_main_route'
roda (3.61.0) lib/roda.rb:380:in `block in base_rack_app_callable'
roda (3.61.0) lib/roda.rb:53:in `call'
uppy-s3_multipart (1.2.0) lib/uppy/s3_multipart/app.rb:20:in `call'
actionpack (7.0.4) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (7.0.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:852:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.4) lib/rack/etag.rb:27:in `call'
rack (2.2.4) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.4) lib/rack/head.rb:12:in `call'
actionpack (7.0.4) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/cookies.rb:696:in `call'
activerecord (7.0.4) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.4) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.4) lib/rails/rack/logger.rb:40:in `call_app'
railties (7.0.4) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (7.0.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (7.0.4) lib/rails/rack/logger.rb:25:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.4) lib/rack/method_override.rb:24:in `call'
rack (2.2.4) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
rack (2.2.4) lib/rack/deflater.rb:44:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
railties (7.0.4) lib/rails/engine.rb:530:in `call'
puma (6.0.0) lib/puma/configuration.rb:268:in `call'
puma (6.0.0) lib/puma/request.rb:89:in `block in handle_request'
puma (6.0.0) lib/puma/thread_pool.rb:343:in `with_force_shutdown'
puma (6.0.0) lib/puma/request.rb:88:in `handle_request'
puma (6.0.0) lib/puma/server.rb:430:in `process_client'
puma (6.0.0) lib/puma/server.rb:233:in `block in run'
puma (6.0.0) lib/puma/thread_pool.rb:150:in `block in spawn_thread'
```

**Comment by mullermp** [comment]
That looks like a different issue/regression. Could you please open a new issue with reproduction steps?

**Comment by mullermp** [comment]
FWIW I found the issue, and it's with Uppy on this line: https://github.com/janko/uppy-s3_multipart/blob/master/lib/uppy/s3_multipart/client.rb#L28

The method parameter is documented to take a symbol, but Uppy passes a string:
```
      # @param [Symbol] method Symbolized method name of the operation you want
      #   to presign.
```
And so endpoint resolution fails because we have a case statement using method names (we are given a string in this case) - https://github.com/aws/aws-sdk-ruby/blob/64f46754071970df2dfaf1822ae82b228c1eddf8/gems/aws-sdk-s3/lib/aws-sdk-s3/plugins/endpoints.rb#L58

I will create an issue on that repo on your behalf.

**Comment by dylanfisher** [comment]
Thank you I appreciate it.
