### ISSUE TITLE
Broken Pipe when streaming upload to S3

### ISSUE THREAD

**Issue by normelton** [aws/aws-sdk-ruby#2793]
### Describe the bug

I'm doing a streaming upload to S3, and am consistently getting a "broken pipe" error after passing 52GB of upload. I've tried this from an on-premise client, and from an EC2 instance. Same problem.

### Expected Behavior

No crashing

### Current Behavior

```
/var/lib/gems/3.0.0/gems/aws-sdk-s3-1.117.0/lib/aws-sdk-s3/multipart_stream_uploader.rb:99:in `abort_upload': multipart upload failed: Broken pipe (Aws::S3::MultipartUploadError)
	from /var/lib/gems/3.0.0/gems/aws-sdk-s3-1.117.0/lib/aws-sdk-s3/multipart_stream_uploader.rb:88:in `upload_parts'
	from /var/lib/gems/3.0.0/gems/aws-sdk-s3-1.117.0/lib/aws-sdk-s3/multipart_stream_uploader.rb:49:in `upload'
	from /var/lib/gems/3.0.0/gems/aws-sdk-s3-1.117.0/lib/aws-sdk-s3/customizations/object.rb:371:in `upload_stream'
	from ./bin/db-backup:16:in `<main>'
```

### Reproduction Steps

```
bucket = Aws::S3::Bucket.new(:name => "my-bucket", :region => "us-east-1")
object = bucket.object("my-large-file")

object.upload_stream(:checksum_algorithm => "CRC32") do |s3_stream|
  Open3.popen3("/usr/bin/dd if=/dev/zero bs=1M count=60000") do |stdin, stdout, stderr, wait_thr|
    while s = stdout.read(1000000)
      s3_stream << s
    end
  end
end
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3 (1.117.0)

### Environment details (Version of Ruby, OS environment)

ruby 3.0.2p107, Ubuntu 22.04

**Comment by normelton** [comment]
Just realized this happens after the 10,000th upload part. Looking at the multipart upload limits (https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html), that's the max number of parts per upload. Problem is obviously due to my only reading/uploading 1M bytes at a time. I'll try increasing this bottleneck and share results here in case others run into the same problem.

**Comment by normelton** [comment]
Solution: Specify a larger `:part_size`:

```
object.upload_stream(:checksum_algorithm => "CRC32", :part_size => 50000000)
```

**Comment by alextwoods** [comment]
Thanks for submitting this and glad you were able to solve it yourself.  However, looks like our `MultipartStreamUploader` was suppressing all errors from upload threads, which makes understanding/debugging issues like this much harder.  I know you've already closed this - but I've got a PR for a fix which at least improves the error reporting: #2797 

With this change, you'd get an error message like: `Aws::S3::MultipartUploadError: multipart upload failed: Part number must be an integer between 1 and 10000, inclusive; Broken pipe` instead of just "Broken Pipe"

**Comment by normelton** [comment]
Right, it took a little while to uncover the true error. That PR would make
it easier. Thanks!!
