### ISSUE TITLE
AWS-SDK-SSM Compilation error during boot time

### ISSUE THREAD

**Issue by aovertus** [aws/aws-sdk-ruby#2826]
### Describe the bug

We are randomly getting this error while running our app in staging/production.

Note that we use `bootsnap` from `Shopify` - https://github.com/Shopify/bootsnap to `compile_cache_iseq` & `compile_cache_yaml`

This started when we upgraded `aws-sdk-ssm` from `1.147.0` to `1.148.0` 2 weeks ago.

Stacktrace from our log
```
  | 2023-02-14T15:04:39.085-05:00 | NoMethodError: undefined method `struct_class=' for #<Seahorse::Model::Shapes::StringShape:0x00007fe49a16d6c8 @metadata={}, @name="DocumentName">
-- | -- | --
  | 2023-02-14T15:04:39.085-05:00 | /usr/local/bundle/gems/aws-sdk-ssm-1.148.0/lib/aws-sdk-ssm/client_api.rb:2172:in `<module:ClientApi>'
  | 2023-02-14T15:04:39.085-05:00 | /usr/local/bundle/gems/aws-sdk-ssm-1.148.0/lib/aws-sdk-ssm/client_api.rb:12:in `<module:SSM>'
  | 2023-02-14T15:04:39.085-05:00 | /usr/local/bundle/gems/aws-sdk-ssm-1.148.0/lib/aws-sdk-ssm/client_api.rb:10:in `<main>'
  | 2023-02-14T15:04:39.085-05:00 | /usr/local/bundle/gems/aws-sdk-ssm-1.148.0/lib/aws-sdk-ssm.rb:15:in `require_relative'
  | 2023-02-14T15:04:39.085-05:00 | /usr/local/bundle/gems/aws-sdk-ssm-1.148.0/lib/aws-sdk-ssm.rb:15:in `<main>'
  | 2023-02-14T15:04:39.085-05:00 | /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  | 2023-02-14T15:04:39.085-05:00 | /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  | 2023-02-14T15:04:39.085-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/runtime.rb:66:in `block (2 levels) in require'
  | 2023-02-14T15:04:39.085-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/runtime.rb:61:in `each'
  | 2023-02-14T15:04:39.085-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/runtime.rb:61:in `block in require'
  | 2023-02-14T15:04:39.085-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/runtime.rb:50:in `each'
  | 2023-02-14T15:04:39.085-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/runtime.rb:50:in `require'
  | 2023-02-14T15:04:39.085-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler.rb:174:in `require'
  | 2023-02-14T15:04:39.085-05:00 | /kith-omas/config/application.rb:7:in `<top (required)>'
  | 2023-02-14T15:04:39.086-05:00 | /kith-omas/Rakefile:4:in `require'
  | 2023-02-14T15:04:39.086-05:00 | /kith-omas/Rakefile:4:in `<top (required)>'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:63:in `load'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:63:in `kernel_load'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/cli/exec.rb:28:in `run'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/cli.rb:474:in `exec'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/cli.rb:30:in `dispatch'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/cli.rb:24:in `start'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/gems/bundler-2.2.22/exe/bundle:49:in `block in <top (required)>'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/gems/bundler-2.2.22/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/gems/bundler-2.2.22/exe/bundle:37:in `<top (required)>'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/bin/bundle:25:in `load'
  | 2023-02-14T15:04:39.086-05:00 | /usr/local/bundle/bin/bundle:25:in `<main>'
```

### Expected Behavior

The app does not crash on boot (rails s/rails c/...)

### Current Behavior

The app randomly crash because of wrong reference to `StringShape` instead of `StructureShape`

### Reproduction Steps

Unable to reproduce consistently.

### Possible Solution

We've been trying to pin point the root cause issue but the diff from https://github.com/aws/aws-sdk-ruby/commit/421613e44c0a406d78e36729f40baaf749b75605 is quite tough to navigate.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-ssm

### Environment details (Version of Ruby, OS environment)

Base image "ruby:3.2.0-slim"

**Comment by alextwoods** [comment]
This is very weird.  The change in 1.148.0 of aws-sdk-ssm was only switching the `EndpointProvider` to a code generated rather than runtime ruleset (#2815 ) and did not change any of the API shapes.   The shape thats giving the error, `DescribeMaintenanceWindowTargetsRequest`, is definitely defined as a `StructShape` [here](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-ssm/lib/aws-sdk-ssm/client_api.rb#L300) and even weirder, the stack trace gives an error at line 2172 on the `struct_class=` method, rather than lines 2168-2171 which are calling `add_member`, which also doesn't exist on `StringShape`.  

I'm fairly certain there is something bootsnap related going on - my guess would be in the byte code caching, but I'm not an expert in bootsnap.  Have you cleared your bootsnap cache(s)?

**Comment by aovertus** [comment]
We did cleared the cache, we took a corrupted image, as soon as we touch the file the cache is regenerate and the issue is fixed so its a bit tricky to pry inside and dig.

The main reason I'm bringing this here and not bootsnap is because:
- This started as soon as we did the `aws-ssm-sdk` upgrade 
- There are closed issues on the bootsnap gem which exposed error from other library but only triggered through the bootsnap cache. 

I'm a bit confused as how to solve this so I would take any bit. I don't want to remove the bootsnap integration as its providing a good performance boot to us so far.

**Comment by alextwoods** [comment]
Yeah that makes sense - I know the SDK has had previous issues reveled by bootsnap.  

Did you upgrade any other gems at the same time?  Could you try pinning aws-sdk-ssm to 1.147.0 and see if it fixes the issue?  What other SDK gems/versions do you have?  I'm also a bit uncertain how to debug this - I haven't been able to reproduce locally yet and I dont see any potential/obvious issues in the code itself that might cause this behavior.  You mentioned it was occurring in staging/production - have you been able to reproducing locally/development?  Can you share any information on how you're deploying? Do you have a fixed Gemfile.lock?

**Comment by yenshirak** [comment]
We see the same issue in GitHub Actions when we are running CI. It started when we added the aws-sdk-ec2 gem a few days ago. It didn't happen with the aws-sdk-s3 gem which we have used for a long time.
Stack trace:
```
NoMethodError: undefined method `new' for #<Seahorse::Model::Shapes::StructureShape:0x00007f3e02ea90b0 @members={}, @members_by_location_name={}, @required=#<Set: {}>, @metadata={}, @name="SpotFleetLaunchSpecification", @struct_class=Seahorse::Model::Shapes::ShapeRef>
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/aws-sdk-ec2-1.366.0/lib/aws-sdk-ec2/client_api.rb:4844:in `<module:ClientApi>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/aws-sdk-ec2-1.366.0/lib/aws-sdk-ec2/client_api.rb:12:in `<module:EC2>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/aws-sdk-ec2-1.366.0/lib/aws-sdk-ec2/client_api.rb:10:in `<main>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/aws-sdk-ec2-1.366.0/lib/aws-sdk-ec2.rb:[15](https://github.com/swiftvee/angus/actions/runs/4255787088/jobs/7403844708#step:6:16):in `require_relative'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/aws-sdk-ec2-1.366.0/lib/aws-sdk-ec2.rb:15:in `<main>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.[16](https://github.com/swiftvee/angus/actions/runs/4255787088/jobs/7403844708#step:6:17).0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/home/runner/work/angus/angus/config/application.rb:19:in `<main>'
/home/runner/work/angus/angus/Rakefile:4:in `require_relative'
/home/runner/work/angus/angus/Rakefile:4:in `<main>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/commands/rake/rake_command.rb:[18](https://github.com/swiftvee/angus/actions/runs/4255787088/jobs/7403844708#step:6:19):in `perform'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/command.rb:51:in `invoke'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/commands.rb:18:in `<main>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
```

Sometimes a different error occurs:
```
NotImplementedError: ibf_dump_object_unsupported: 0x00007f9b0d09ffd8 [0      ] T_NONE 
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/compile_cache/iseq.rb:42:in `to_binary'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/compile_cache/iseq.rb:42:in `input_to_storage'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/compile_cache/iseq.rb:60:in `fetch'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/compile_cache/iseq.rb:60:in `fetch'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/compile_cache/iseq.rb:85:in `load_iseq'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/aws-sdk-ec2-1.366.0/lib/aws-sdk-ec2.rb:[15](https://github.com/swiftvee/angus/actions/runs/4255787088/jobs/7403844708#step:6:16):in `require_relative'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/aws-sdk-ec2-1.366.0/lib/aws-sdk-ec2.rb:15:in `<main>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.[16](https://github.com/swiftvee/angus/actions/runs/4255787088/jobs/7403844708#step:6:17).0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/home/runner/work/angus/angus/config/application.rb:19:in `<main>'
/home/runner/work/angus/angus/Rakefile:4:in `require_relative'
/home/runner/work/angus/angus/Rakefile:4:in `<main>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/commands/rake/rake_command.rb:[18](https://github.com/swiftvee/angus/actions/runs/4255787088/jobs/7403844708#step:6:19):in `perform'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/command.rb:51:in `invoke'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/commands.rb:18:in `<main>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
```

We haven't seen it in production or during local development.
Please let me know if I can help with debugging.

**Comment by alextwoods** [comment]
@yenshirak  - Sorry you're running into this as well - I still haven't been able to reproduce or debug the issue.

Does it happen on every run or only sometimes?  Anything else you can tell me about the environment?  Can you try pinning aws-sdk-ec2 to version 1.357.0 or earlier?

**Comment by yenshirak** [comment]
@alextwoods Only sometimes. Deleting the GitHub Actions bundler cache is fixing it. I will try to downgrade to 1.357.0.

**Comment by yenshirak** [comment]
@alextwoods Unfortunately downgrading to 1.357.0 doesn't help:

```
Run bin/rails db:create db:schema:load
rails aborted!
NotImplementedError: ibf_dump_object_unsupported: 0x00007fccc5e4ff68 [0      ] T_NONE 
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/compile_cache/iseq.rb:42:in `to_binary'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/compile_cache/iseq.rb:42:in `input_to_storage'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/compile_cache/iseq.rb:60:in `fetch'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/compile_cache/iseq.rb:60:in `fetch'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/compile_cache/iseq.rb:85:in `load_iseq'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/aws-sdk-ec2-1.357.0/lib/aws-sdk-ec2.rb:[15](https://github.com/swiftvee/angus/actions/runs/4311912434/jobs/7521828401#step:6:16):in `require_relative'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/aws-sdk-ec2-1.357.0/lib/aws-sdk-ec2.rb:15:in `<main>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.[16](https://github.com/swiftvee/angus/actions/runs/4311912434/jobs/7521828401#step:6:17).0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/home/runner/work/angus/angus/config/application.rb:19:in `<main>'
/home/runner/work/angus/angus/Rakefile:4:in `require_relative'
/home/runner/work/angus/angus/Rakefile:4:in `<main>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/commands/rake/rake_command.rb:[18](https://github.com/swiftvee/angus/actions/runs/4311912434/jobs/7521828401#step:6:19):in `perform'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/command.rb:51:in `invoke'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/commands.rb:18:in `<main>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
```

I didn't mention earlier that the error is thrown during the DB creation: `bin/rails db:create db:schema:load`

**Comment by yenshirak** [comment]
@alextwoods This is the AWS section of our current Gemfile.lock:
```
    aws-eventstream (1.2.0)
    aws-partitions (1.716.0)
    aws-sdk-core (3.170.0)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.651.0)
      aws-sigv4 (~> 1.5)
      jmespath (~> 1, >= 1.6.1)
    aws-sdk-ec2 (1.357.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-kms (1.62.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.119.1)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.4)
    aws-sigv4 (1.5.2)
      aws-eventstream (~> 1, >= 1.0.2)
    aws_cf_signer (0.1.3)
```
and
```
    jmespath (1.6.2)
```

**Comment by yenshirak** [comment]
@alextwoods The issue disappeared after we replaced the `webpacker` gem with `jsbundling-rails`.

**Comment by yenshirak** [comment]
@alextwoods Unfortunately it didn't disappear fully, but it occurs less frequently and the error is different:
```
Run bin/rails db:create db:schema:load
rails aborted!
NoMethodError: undefined method `add_member' for Seahorse::Model::Shapes::ShapeRef:Class
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/aws-sdk-ec2-1.368.0/lib/aws-sdk-ec2/client_api.rb:10937:in `<module:ClientApi>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/aws-sdk-ec2-1.368.0/lib/aws-sdk-ec2/client_api.rb:[12](https://github.com/swiftvee/angus/actions/runs/4362169048/jobs/7626753992#step:6:13):in `<module:EC2>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/aws-sdk-ec2-1.368.0/lib/aws-sdk-ec2/client_api.rb:10:in `<main>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/aws-sdk-ec2-1.368.0/lib/aws-sdk-ec2.rb:[15](https://github.com/swiftvee/angus/actions/runs/4362169048/jobs/7626753992#step:6:16):in `require_relative'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/aws-sdk-ec2-1.368.0/lib/aws-sdk-ec2.rb:15:in `<main>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.[16](https://github.com/swiftvee/angus/actions/runs/4362169048/jobs/7626753992#step:6:17).0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/home/runner/work/angus/angus/config/application.rb:19:in `<main>'
/home/runner/work/angus/angus/Rakefile:4:in `require_relative'
/home/runner/work/angus/angus/Rakefile:4:in `<main>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/commands/rake/rake_command.rb:[18](https://github.com/swiftvee/angus/actions/runs/4362169048/jobs/7626753992#step:6:19):in `perform'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/command.rb:51:in `invoke'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/commands.rb:18:in `<main>'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/runner/work/angus/angus/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
```

**Comment by mullermp** [comment]
Have you tried opening an issue on the bootsnap repo for this?

**Comment by mullermp** [comment]
Until there's a solid reproduction case, I'm going to close this. I think the issue lies in bootsnap, but I agree it was surfaced by a change in the SDK.

**Comment by yenshirak** [comment]
@mullermp No, but I will open a Bootsnap issue then. For now we disabled Bootsnap in CI as a workaround.
