### ISSUE TITLE
SDK fails to use SSO credentials configured via `aws configure sso`

### ISSUE THREAD

**Issue by guss77** [aws/aws-sdk-ruby#2894]
### Describe the bug

After configuring a profile using `aws configure sso --profile PROFILENAME`, the `aws` CLI tool can use the configured profile using `aws --profile PROFILENAME` without trouble (all commands that I've tried work), but the AWS SDK for Ruby fails with an error, when trying to configure it with that profile.

### Expected Behavior

Setting the named profile through the `Aws.config` options should work for SSO profile as well as it does for static profiles:

```
$ irb -r aws-sdk-ec2
irb(main):001:0> Aws::EC2::Client.new({profile: 'PROFILENAME'})
=> #<Aws::EC2::Client>
```

### Current Behavior

Trying to initialize an AWS client with an SSO profile, we get an error: ` sso-session My Profile must be defined in the config file. Referenced by profile PROFILENAME (ArgumentError)`

```
$ irb -r aws-sdk-ec2
irb(main):001:0> Aws::EC2::Client.new({profile: 'PROFILENAME'})
/home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/shared_config.rb:364:in `sso_credentials_from_profile': sso-session My Profile must be defined in the config file. Referenced by profile PROFILENAME (ArgumentError)                                                             
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/shared_config.rb:153:in `sso_credentials_from_config'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/credential_provider_chain.rb:64:in `static_profile_sso_credentials'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/credential_provider_chain.rb:13:in `block in resolve'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/credential_provider_chain.rb:12:in `each'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/credential_provider_chain.rb:12:in `resolve'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/credentials_configuration.rb:72:in `block in <class:CredentialsConfiguration>'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:72:in `call'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:215:in `block in resolve_defaults'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:59:in `each'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:59:in `each'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:214:in `resolve_defaults'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:207:in `value_at'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:191:in `block in resolve'
        from /usr/lib/ruby/3.1.0/set.rb:511:in `each_key'
        from /usr/lib/ruby/3.1.0/set.rb:511:in `each'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:191:in `resolve'
        ... 10 levels...
```

### Reproduction Steps

```
$ irb -r aws-sdk-ec2
irb(main):001:0> Aws::EC2::Client.new({profile: 'PROFILENAME'})
```

### Possible Solution

I have yet to find a fix for this. From reviewing the `lib/aws-sdk-core/shared_config.rb` file, I don't understand how SSO credentials are properly initialized, but it seems to be only when trying to "assume a role" (which I'm not sure when is that workflow triggered).

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core

### Environment details (Version of Ruby, OS environment)

Ruby 3.1.0 on Ubuntu Lunar

**Comment by guss77** [comment]
Thank you - that indeed solves the issue I'm having
