### ISSUE TITLE
getaddrinfo: nodename nor servname provided, or not known (SocketError)

### ISSUE THREAD

**Issue by jeffrabovsky** [aws/aws-sdk-ruby#532]
I'm getting this error with ruby-2.0.0-p247 and aws-sdk (1.40.0) when I try to run the following:

```
require 'aws-sdk'
AWS.config( :access_key_id => ENV['AWS_ACCESS_KEY_ID'], :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'])
puts AWS.s3.buckets.first.exists?
```

This seems to go away when I instead use aws-sdk (1.38.0). Any ideas what could be going on here? Here is the full stack trace for reference:

```
/Users/uraboje/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
    from /Users/uraboje/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `open'
    from /Users/uraboje/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
    from /Users/uraboje/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
    from /Users/uraboje/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:877:in `connect'
    from /Users/uraboje/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
    from /Users/uraboje/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:857:in `start'
    from /Users/uraboje/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-1.40.0/lib/aws/core/http/connection_pool.rb:321:in `start_session'
    from /Users/uraboje/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-1.40.0/lib/aws/core/http/connection_pool.rb:125:in `session_for'
    from /Users/uraboje/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-1.40.0/lib/aws/core/http/net_http_handler.rb:55:in `handle'
    from /Users/uraboje/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-1.40.0/lib/aws/core/client.rb:253:in `block in make_sync_request'
    from /Users/uraboje/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-1.40.0/lib/aws/core/client.rb:289:in `retry_server_errors'
    from /Users/uraboje/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-1.40.0/lib/aws/core/client.rb:249:in `make_sync_request'
    from /Users/uraboje/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-1.40.0/lib/aws/core/client.rb:511:in `block (2 levels) in client_request'
    from /Users/uraboje/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-1.40.0/lib/aws/core/client.rb:391:in `log_client_request'
    from /Users/uraboje/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-1.40.0/lib/aws/core/client.rb:477:in `block in client_request'
    from /Users/uraboje/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-1.40.0/lib/aws/core/client.rb:373:in `return_or_raise'
    from /Users/uraboje/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-1.40.0/lib/aws/core/client.rb:476:in `client_request'
    from (eval):3:in `list_buckets'
    from /Users/uraboje/.rvm/gems/ruby-2.0.0-p247/gems/aws-sdk-1.40.0/lib/aws/s3/bucket_collection.rb:140:in `each'
    from foo.rb:3:in `first'
    from foo.rb:3:in `<main>'
```

Thanks!

**Comment by erupenkman** [comment]
just for anyone else, when running the opsworks register command, DO NOT change the region from us-east-1 to match the region your instances run in.

 I got the same error message and came here from search engine, hope it helps someone.

**Comment by flippyhead** [comment]
@erupenkman well that's funny -- your comment got me unstuck from quite a bit of confusion. Apparently opsworks command and control is us-east-1 only
