### ISSUE TITLE
'AWS::EC2::Errors::InvalidBlockDeviceMapping: Invalid snapshot' intermittently from 'AWS::EC2::InstanceCollection#create'

### ISSUE THREAD

**Issue by jrab89** [aws/aws-sdk-ruby#615]
```ruby
options = 
   {:image_id=>"ami-4aa04e22",
    :security_group_ids=>["sg-e4834e8b"],
    :instance_type=>"t1.micro",
    :subnet=>"subnet-3e1cfb51",
    :key_name=>"foo",
    :block_device_mappings=>
      [{:device_name=>"/dev/xvdf", :virtual_name=>"ephemeral0"},
       {:device_name=>"/dev/xvdg", :virtual_name=>"ephemeral1"},
       {:device_name=>"/dev/xvdh", :virtual_name=>"ephemeral2"},
       {:device_name=>"/dev/xvdi", :virtual_name=>"ephemeral3"},
       {:device_name=>"/dev/sda", :ebs=>{:delete_on_termination=>false}}]}

# this usually works
AWS.ec2.instances.create options

# but about one in every 5 instances fails
10.times { AWS.ec2.instances.create options }
```

Here's a stack trace for reference:

```
/Users/uraboje/.rvm/gems/ruby-2.0.0-p451/gems/aws-sdk-v1-1.52.0/lib/aws/core/client.rb:375:in `return_or_raise': Invalid snapshot (AWS::EC2::Errors::InvalidBlockDeviceMapping)
	from /Users/uraboje/.rvm/gems/ruby-2.0.0-p451/gems/aws-sdk-v1-1.52.0/lib/aws/core/client.rb:476:in `client_request'
	from (eval):3:in `run_instances'
	from /Users/uraboje/.rvm/gems/ruby-2.0.0-p451/gems/aws-sdk-v1-1.52.0/lib/aws/ec2/instance_collection.rb:303:in `create'
```

Any ideas what could be going on here? Thanks!

**Comment by trevorrowe** [comment]
Closing this stale issue. Please re-open if you continue to have issues.
