### ISSUE TITLE
NoMethodError: undefined method `config' for AWS:Module

### ISSUE THREAD

**Issue by thewatts** [aws/aws-sdk-ruby#625]
For some reason, in Pry (or in the gem I'm building) - I can't config AWS?
It keeps telling me that `AWS` doesn't have a `::config` method... ?

```
> require 'aws/s3'
=> true
> AWS.config
NoMethodError: undefined method `config' for AWS:Module
```

Setup per: https://github.com/aws/aws-sdk-ruby#basic-configuration

**Comment by jgauna** [comment]
I'm getting this issue too. Changed that line as you said but the error persists

**Comment by trevorrowe** [comment]
@jgauna What gem are you using and how are your requiring it?

**Comment by jgauna** [comment]
This is my gemfile:

```javascript
source 'https://rubygems.org'

gem 'RedCloth', :require => 'redcloth'
gem 'ancestry'
gem 'aws-sdk'
gem 'aws-ses', :require => 'aws/ses'
gem 'backbone-on-rails', '~> 1.0.0'
gem 'backbone-support'
gem 'bourbon', '~> 2.0.0.rc1'
gem 'cancan'
gem 'covenant'
gem 'delayed_job', '~> 2.1.4'
gem 'doc_raptor'
gem 'dynamic_form'
gem 'ejs'
gem 'flutie'
gem 'formtastic', '~> 2.2.1'
gem 'haml-rails'
gem 'high_voltage'
gem 'jbuilder'
gem 'jquery-rails'
gem 'multi_json', '~> 1.3'
gem 'mysql2', '~> 0.3'
gem 'nokogiri'
gem 'oj'
gem 'paperclip'
gem 'rack'
gem 'rails', '~> 3.2.13'
gem 'rake'
gem 'rubyvis'
gem 'will_paginate'
gem 'grocer'
gem 'net-sftp'
gem 'thin'
gem 'urbanairship'
gem 'zipruby', :platforms => :mswin
gem 's3_direct_upload'
gem 'mime-types'
gem 'therubyracer', :platforms => :ruby
gem 'libv8', :platforms => :ruby
gem 'rails_config'
gem 'acts_as_list'
gem 'devise'
gem 'devise-encryptable'
gem 'doorkeeper'
gem 'oauth2'
gem 'faker', '1.2.0'
gem 'rack-cors', require: 'rack/cors'
gem 'bxslider-rails'
gem 'pagedown-rails', '~> 1.1.3'
gem "time_splitter"
gem 'american_date'
gem 'country_select'
gem 'jquery-fileupload-rails'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'compass-rails', '>= 1.0.3'
  gem 'haml_coffee_assets'
  gem 'sass-rails', '~> 3.2.3'
  gem 'select2-rails'
  gem 'turbo-sprockets-rails3'
  gem 'uglifier', '>= 1.0.3'
  gem 'jquery-ui-rails'
  gem 'jquery-modal-rails'
  gem 'jquery-validation-rails'
  gem 'jquery-timepicker-rails'
  gem 'chardinjs-rails'
end

group :development do
  gem 'parallel_tests', '0.15.4'
  gem 'sextant'
  gem 'pry'
  gem 'active_record_query_trace'
end

group :development, :test do
  gem 'factory_girl_rails', '~> 2.0.0.rc'
  gem 'guard-jasmine'
  gem 'jasminerice'
  gem 'pry-nav'
  gem 'pry-rails'
  gem 'pry-stack_explorer'
  gem 'rspec-rails', '~> 2.13'
  gem 'simplecov', :require => false
end

group :production, :staging do
  gem 'memcache-client'
  gem 'newrelic_rpm'
  gem 'rack-ssl', :require => 'rack/ssl'
end

group :test do
  gem 'bourne', '~> 1.4'
  gem 'capybara', '2.1.0'
  gem 'chronic'
  gem 'codeclimate-test-reporter', require: nil
  gem 'cucumber', '~> 1.3.1'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'email_spec', '~> 1.4.0'
  gem 'launchy'
  gem 'poltergeist', '1.4.1'
  gem 'selenium-webdriver', '2.35.1'
  gem 'sham_rack'
  gem 'shoulda-matchers', '~> 1.0'
  gem 'timecop'
  gem 'treetop'
  gem 'json_expressions'
end
```

The ful error log is:

```
C:\Users\Juancito\Desktop\CMS\vertical-server>rails s
=> Booting Thin
=> Rails 3.2.21 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
C:/Users/Juancito/Desktop/CMS/vertical-server/config/initializers/aws.rb:5:in `<top (required)>': undefined method `config' for AWS:Module (NoMethodError)
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `block in load'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/engine.rb:592:in `each'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/engine.rb:592:in `block in <class:Engine>'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/config/environment.rb:8:in `<top (required)>'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/config.ru:3:in `block in <main>'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/config.ru:in `new'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/config.ru:in `<main>'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:40:in `eval'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:40:in `parse_file'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/rack-1.4.5/lib/rack/server.rb:200:in `app'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/commands/server.rb:46:in `app'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/rack-1.4.5/lib/rack/server.rb:304:in `wrapped_app'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/rack-1.4.5/lib/rack/server.rb:254:in `start'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/commands/server.rb:70:in `start'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/commands.rb:55:in `block in <top (required)>'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/commands.rb:50:in `tap'
        from C:/Users/Juancito/Desktop/CMS/vertical-server/gems/ruby/1.9.1/gems/railties-3.2.21/lib/rails/commands.rb:50:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

As you may notice i'm using Windows. Last thing is i'm not a ruby dev. Just trying to run locally an enterprise project.

**Comment by trevorrowe** [comment]
@jgauna It appears that the error is caused by your dependency on the `aws-sdk` without specifying what version. Version 2 was recently released which uses a different namespace (`Aws`, instead of `AWS`). 

The simple fix is to add a version in your Gemfile, e.g.

```
gem 'aws-sdk', '< 2.0'
```

**Comment by trevorrowe** [comment]
@jgauna Alternatively, you can replace `aws-sdk` with `aws-sdk-v1`, but then you might need to replace a require statement in code from `require 'aws-sdk'` with `require 'aws-sdk-v1'.

This approach has the benefit of allowing you to add a gem dependency on version 2 of `aws-sdk` and use them in the same application.
