### ISSUE TITLE
Newly created bucket - 'undefined method rewind for nil:NilClass' error

### ISSUE THREAD

**Issue by ZipoKing** [aws/aws-sdk-ruby#665]
When I'm trying to copy object from one S3 bucket to newly created one (eu-central-1 endpoint), then using "standard" S3 endpoint I'm getting following error:
```
/opt/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/aws-sdk-v1-1.59.0/lib/aws/s3/region_detection.rb:36:in `updgrade_to_v4'
/opt/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/aws-sdk-v1-1.59.0/lib/aws/s3/region_detection.rb:26:in `detect_region_and_retry'
/opt/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/aws-sdk-v1-1.59.0/lib/aws/s3/region_detection.rb:13:in `retry_server_errors'
/opt/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/aws-sdk-v1-1.59.0/lib/aws/core/client.rb:249:in `make_sync_request'
/opt/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/aws-sdk-v1-1.59.0/lib/aws/core/client.rb:511:in `block (2 levels) in client_request'
/opt/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/aws-sdk-v1-1.59.0/lib/aws/core/client.rb:391:in `log_client_request'
/opt/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/aws-sdk-v1-1.59.0/lib/aws/core/client.rb:477:in `block in client_request'
/opt/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/aws-sdk-v1-1.59.0/lib/aws/core/client.rb:373:in `return_or_raise'
/opt/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/aws-sdk-v1-1.59.0/lib/aws/core/client.rb:476:in `client_request'
(eval):3:in `copy_object'
/opt/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/aws-sdk-v1-1.59.0/lib/aws/s3/s3_object.rb:918:in `copy_from'
/opt/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/aws-sdk-v1-1.59.0/lib/aws/s3/s3_object.rb:1004:in `copy_to'
```
I've found that if I'll try to make the same call using "localized endpoint" for this bucket, everything works fine. Previously code returned following exceptions: AWS::S3::Errors::TemporaryRedirect, AWS::S3::Errors::PermanentRedirect

**Comment by trevorrowe** [comment]
The v1 Ruby SDK requires that you configure the proper region for calls to eu-central-1. This is necessary because the eu-central-1 forces signature version 4 and the region name must be known to generate that signature.

For newly created buckets, you can work around this by configuring `:region => 'eu-central-1`.
