### ISSUE TITLE
Zlib error when running `bundle install --deployment`

### ISSUE THREAD

**Issue by JangoSteve** [aws/aws-sdk-ruby#674]
I'm not sure exactly what the issue is, but with versions >=1.52.0, when you run `bundle install --deployment` (at least with ruby 2.1.2 and Rails 4.1), you get a Zlib error when Bundler is trying to fetch info from Rubygems.org:

```
$ bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
Fetching gem metadata from https://rubygems.org/.Retrying dependency api due to error (2/3): Zlib::BufError buffer error
Retrying dependency api due to error (3/3): Zlib::BufError buffer error
Unfortunately, a fatal error has occurred. Please see the Bundler troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
/Users/steveschwartz/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:357:in `finish': buffer error (Zlib::BufError)
	from ~/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:357:in `finish'
	from ~/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:262:in `ensure in inflater'
	from ~/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:262:in `inflater'
	from ~/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:274:in `read_body_0'
	from ~/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:201:in `read_body'
	from ~/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:226:in `body'
	from ~/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:163:in `reading_body'
	from ~/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1414:in `block in transport_request'
	from ~/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
	from ~/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
	from ~/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1378:in `request'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/vendor/net/http/persistent.rb:999:in `request'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/fetcher.rb:285:in `request'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/fetcher.rb:257:in `fetch'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/fetcher.rb:303:in `fetch_dependency_remote_specs'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/fetcher.rb:216:in `block in fetch_remote_specs'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/retry.rb:38:in `call'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/retry.rb:38:in `run'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/retry.rb:28:in `attempt'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/fetcher.rb:215:in `fetch_remote_specs'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/fetcher.rb:171:in `specs'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/source/rubygems.rb:258:in `block in remote_specs'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/source/rubygems.rb:256:in `each'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/source/rubygems.rb:256:in `remote_specs'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/source/rubygems.rb:179:in `fetch_specs'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/source/rubygems.rb:64:in `specs'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/lazy_specification.rb:53:in `__materialize__'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/spec_set.rb:88:in `block in materialize'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/spec_set.rb:85:in `map!'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/spec_set.rb:85:in `materialize'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/definition.rb:133:in `specs'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/definition.rb:122:in `resolve_remotely!'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/installer.rb:76:in `run'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/installer.rb:15:in `install'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/cli/install.rb:78:in `run'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/cli.rb:146:in `install'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/vendor/thor/command.rb:27:in `run'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/vendor/thor.rb:363:in `dispatch'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/vendor/thor/base.rb:440:in `start'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/cli.rb:9:in `start'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/bin/bundle:20:in `block in <top (required)>'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
	from ~/gems/ruby-2.1.2@global/gems/bundler-1.6.2/bin/bundle:20:in `<top (required)>'
	from ~/gems/ruby-2.1.2@global/bin/bundle:23:in `load'
	from ~/gems/ruby-2.1.2@global/bin/bundle:23:in `<main>'
	from ~/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from ~/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

Just running `bundle install` without the deployment flag settings does not cause any issues. I tried this with v1.51.0 and it works, but then every version after that fails with the above issue.

**Comment by trevorrowe** [comment]
In version 1.52.0 the gem was refactored from `aws-sdk` to two gems:

* `aws-sdk`
* `aws-sdk-v1`

Where `aws-sdk` has a runtime dependency on `aws-sdk-v1`. The reason is so that for versions >= 2.0 the aws-sdk gem can pull in the latest version while allowing users to install the v1 SDK in the same process (via aws-sdk-v1).

That said, I don't know why this should affect your usage of `aws-sdk`.

**Comment by trevorrowe** [comment]
Might I also suggest that you replace your dependency from aws-sdk to aws-sdk-v1. This will avoid the need for your bundle install to pull in the depenency. The `aws-sdk` gem is now empty and is only there to load the v1 gem. I'm guessing this will help work around your issue. Just be certain to replace your require statements with:

```ruby
require 'aws-sdk-v1'
```
