### ISSUE TITLE
DynamoDB API broken with SDKv2 due to :table_name attribute key not being converted to 'TableName'

### ISSUE THREAD

**Issue by smeyfroi** [aws/aws-sdk-ruby#699]
I've ported some old code that has worked for ages using the v1 API, and still works with the latest dynamodb-local. Running it against the eu-west-1 endpoint gives this errors as below. The error message suggests that it wants a 'tableName' attribute, rather than 'table_name'. Even though dynamodb-local wants 'table_name', and the docs say 'table_name'. In fact using 'tableName' has no effect, see below.

I believe I see something similar with the put_items API. In this case the error complains about the requestItems attribute.

What funkiness is going on here?

I feel bad raising this, because it seems like the problem should be in my code. But as I say, I've had this stuff running for over a year on the old SDK against eu-west-1, and everything also works on the latest dynamodb-local as expected. For example this is a successful ```local``` query matching the bad ones below:
```
Good local query:

[Aws::DynamoDB::Client 200 0.004374 0 retries] query(table_name:"cc_metrics",select:"ALL_ATTRIBUTES",scan_index_forward:false,consistent_read:false,key_conditions:{"resource_id_interval"=>{attribute_value_list:[{s:"445:3600"}],comparison_operator:"EQ"},"timestamp"=>{attribute_value_list:[{n:"1423337386001"},{n:"1423430986001"}],comparison_operator:"BETWEEN"}})
```

```
Bad eu-west-1 query:

{:table_name=>"test_cc_group_metrics", :select=>"ALL_ATTRIBUTES", :scan_index_forward=>false, :consistent_read=>false, :limit=>1}
opening connection to dynamodb.eu-west-1.amazonaws.com:443...
opened
starting SSL for dynamodb.eu-west-1.amazonaws.com:443...
SSL established
<- "POST / HTTP/1.1\r\nContent-Type: application/x-amz-json-1.0\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.0.22 ruby/2.1.5 x86_64-linux\r\nX-Amz-Target: DynamoDB_20120810.Query\r\nX-Amz-Date: 20150209T211716Z\r\nHost: dynamodb.eu-west-1.amazonaws.com\r\nX-Amz-Content-Sha256: e20a7898edbb9f6b80d5d26548e4d3e8919b44e004a3f27ecd6f698fe9251407\r\nAuthorization: AWS4-HMAC-SHA256 Credential=REDACTED/20150209/eu-west-1/dynamodb/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=fcd203a4ee1b45499673ee74da8f1f2ac98918c04fc9e9363add9fb6ec53c02c\r\nContent-Length: 233\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 400 Bad Request\r\n"
-> "x-amzn-RequestId: UDVLG8SU93I7RDQDSDAESBPIE3VV4KQNSO5AEMVJF66Q9ASUAAJG\r\n"
-> "x-amz-crc32: 2331945813\r\n"
-> "Content-Type: application/x-amz-json-1.0\r\n"
-> "Content-Length: 179\r\n"
-> "Date: Mon, 09 Feb 2015 21:16:16 GMT\r\n"
-> "\r\n"
reading 179 bytes...
-> "{\"__type\":\"com.amazon.coral.validate#ValidationException\",\"message\":\"1 validation error detected: Value null at 'tableName' failed to satisfy constraint: Member must not be null\"}"
read 179 bytes
Conn keep-alive
[Aws::DynamoDB::Client 400 0.036745 0 retries] query(table_name:"test_cc_group_metrics",select:"ALL_ATTRIBUTES",scan_index_forward:false,consistent_read:false,limit:1,key_conditions:{"group_id_interval"=>{attribute_value_list:[{s:"16:900"}],comparison_operator:"EQ"}}) Aws::DynamoDB::Errors::ValidationException 1 validation error detected: Value null at 'tableName' failed to satisfy constraint: Member must not be null
```

Incidentally, changing the request param to ```tableName``` gives the same result:
```
Bad eu-west-1 query:

opening connection to dynamodb.eu-west-1.amazonaws.com:443...
opened
starting SSL for dynamodb.eu-west-1.amazonaws.com:443...
SSL established
<- "POST / HTTP/1.1\r\nContent-Type: application/x-amz-json-1.0\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.0.22 ruby/2.1.5 x86_64-linux\r\nX-Amz-Target: DynamoDB_20120810.Query\r\nX-Amz-Date: 20150209T212321Z\r\nHost: dynamodb.eu-west-1.amazonaws.com\r\nX-Amz-Content-Sha256: 9e54d9190f7eb1baceb7d4bdee43c2bc70802fc341578f08c40ad984a620be5e\r\nAuthorization: AWS4-HMAC-SHA256 Credential=REDACTED/20150209/eu-west-1/dynamodb/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=da422e76789cfe325212eccba156b1ed2f4e1287a40ae8ee064fc9f0c7edd01a\r\nContent-Length: 232\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 400 Bad Request\r\n"
-> "x-amzn-RequestId: 1J1EMRDTJTHDKDHKU63U7H5KARVV4KQNSO5AEMVJF66Q9ASUAAJG\r\n"
-> "x-amz-crc32: 2331945813\r\n"
-> "Content-Type: application/x-amz-json-1.0\r\n"
-> "Content-Length: 179\r\n"
-> "Date: Mon, 09 Feb 2015 21:22:20 GMT\r\n"
-> "\r\n"
reading 179 bytes...
-> "{\"__type\":\"com.amazon.coral.validate#ValidationException\",\"message\":\"1 validation error detected: Value null at 'tableName' failed to satisfy constraint: Member must not be null\"}"
read 179 bytes
Conn keep-alive
[Aws::DynamoDB::Client 400 0.036559 0 retries] query(tableName:"test_cc_group_metrics",select:"ALL_ATTRIBUTES",scan_index_forward:false,consistent_read:false,limit:1,key_conditions:{"group_id_interval"=>{attribute_value_list:[{s:"16:900"}],comparison_operator:"EQ"}}) Aws::DynamoDB::Errors::ValidationException 1 validation error detected: Value null at 'tableName' failed to satisfy constraint: Member must not be null
```

**Comment by smeyfroi** [comment]
I've got this down to a simple test case, which suggests that the DynamoDB API isn't available using the SDKv2?

```
irb(main):010:0> client.list_tables
opening connection to dynamodb.eu-west-1.amazonaws.com:443...
opened
starting SSL for dynamodb.eu-west-1.amazonaws.com:443...
SSL established
<- "POST / HTTP/1.1\r\nContent-Type: application/x-amz-json-1.0\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.0.22 ruby/2.1.5 x86_64-linux\r\nX-Amz-Target: DynamoDB_20120810.ListTables\r\nX-Amz-Date: 20150210T104811Z\r\nHost: dynamodb.eu-west-1.amazonaws.com\r\nX-Amz-Content-Sha256: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a\r\nAuthorization: AWS4-HMAC-SHA256 Credential=REDACTED/20150210/eu-west-1/dynamodb/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=d387e39fc11124a7c5788005437282573aafd22823528c521605b78afa19904a\r\nContent-Length: 2\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "x-amzn-RequestId: C6UL0NHNURSHN9L8C8QTPQV753VV4KQNSO5AEMVJF66Q9ASUAAJG\r\n"
-> "x-amz-crc32: 2003450131\r\n"
-> "Content-Type: application/x-amz-json-1.0\r\n"
-> "Content-Length: 98\r\n"
-> "Date: Tue, 10 Feb 2015 10:47:09 GMT\r\n"
-> "\r\n"
reading 98 bytes...
-> "{\"TableNames\":[\"test_cc_events\",\"test_cc_group_events\",\"test_cc_group_metrics\",\"test_cc_metrics\"]}"
read 98 bytes
Conn keep-alive
[Aws::DynamoDB::Client 200 0.042491 0 retries] list_tables()

=> {"TableNames"=>
  ["test_cc_events",
   "test_cc_group_events",
   "test_cc_group_metrics",
   "test_cc_metrics"]}
```

```
irb(main):011:0> client.describe_table(table_name:'test_cc_events')
opening connection to dynamodb.eu-west-1.amazonaws.com:443...
opened
starting SSL for dynamodb.eu-west-1.amazonaws.com:443...
SSL established
<- "POST / HTTP/1.1\r\nContent-Type: application/x-amz-json-1.0\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.0.22 ruby/2.1.5 x86_64-linux\r\nX-Amz-Target: DynamoDB_20120810.DescribeTable\r\nX-Amz-Date: 20150210T104843Z\r\nHost: dynamodb.eu-west-1.amazonaws.com\r\nX-Amz-Content-Sha256: 6ddbdfcc57cff70175d9c8a0c05e6634f326473df31f155bf7c1d1879cd07788\r\nAuthorization: AWS4-HMAC-SHA256 Credential=REDACTED/20150210/eu-west-1/dynamodb/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=e5803521326ebb453f1bc67d9837dabd1541629b92c55d34da9dfc83bc4d1cea\r\nContent-Length: 31\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 400 Bad Request\r\n"
-> "x-amzn-RequestId: LKQDT6ECNS1KE7UMFN5U66A82RVV4KQNSO5AEMVJF66Q9ASUAAJG\r\n"
-> "x-amz-crc32: 2965254985\r\n"
-> "Content-Type: application/x-amz-json-1.0\r\n"
-> "Content-Length: 143\r\n"
-> "Date: Tue, 10 Feb 2015 10:47:41 GMT\r\n"
-> "\r\n"
reading 143 bytes...
-> "{\"__type\":\"com.amazon.coral.validate#ValidationException\",\"message\":\"The paramater 'TableName' is required but was not present in the request\"}"
read 143 bytes
Conn keep-alive
[Aws::DynamoDB::Client 400 0.035712 0 retries] describe_table(table_name:"test_cc_events") Aws::DynamoDB::Errors::ValidationException The paramater 'TableName' is required but was not present in the request

Aws::DynamoDB::Errors::ValidationException: The paramater 'TableName' is required but was not present in the request
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.0.22/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.0.22/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.0.22/lib/seahorse/client/request.rb:70:in `send_request'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.0.22/lib/seahorse/client/base.rb:215:in `block (2 levels) in define_operation_methods'
	from (irb):11
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
irb(main):012:0>
```

```
irb(main):012:0> client.describe_table(tableName:'test_cc_events')
>>>>>> the same result as above
```

**Comment by smeyfroi** [comment]
And to eliminate the eu-west-1 endpoint, here's a result from us-east-1:

```
Loading production environment (Rails 4.2.0)
irb(main):001:0> DynamodbSchema.create_events_table
opening connection to dynamodb.us-east-1.amazonaws.com:443...
opened
starting SSL for dynamodb.us-east-1.amazonaws.com:443...
SSL established
<- "POST / HTTP/1.1\r\nContent-Type: application/x-amz-json-1.0\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.0.22 ruby/2.1.5 x86_64-linux\r\nX-Amz-Target: DynamoDB_20120810.CreateTable\r\nX-Amz-Date: 20150210T110216Z\r\nHost: dynamodb.us-east-1.amazonaws.com\r\nX-Amz-Content-Sha256: 06f89020d041495afe8ad5b8a35630d2229a7a378d6833c7903fb28a6194d76e\r\nAuthorization: AWS4-HMAC-SHA256 Credential=REDACTED/20150210/us-east-1/dynamodb/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=475ba875de4e6f35236c913738ee638af0aa3545b98866f89473adb06fcea682\r\nContent-Length: 762\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 400 Bad Request\r\n"
-> "x-amzn-RequestId: I9HPQ7ISHMHLDA5G31PU8JDIKBVV4KQNSO5AEMVJF66Q9ASUAAJG\r\n"
-> "x-amz-crc32: 2965254985\r\n"
-> "Content-Type: application/x-amz-json-1.0\r\n"
-> "Content-Length: 143\r\n"
-> "Date: Tue, 10 Feb 2015 11:01:15 GMT\r\n"
-> "\r\n"
reading 143 bytes...
-> "{\"__type\":\"com.amazon.coral.validate#ValidationException\",\"message\":\"The paramater 'TableName' is required but was not present in the request\"}"
read 143 bytes
Conn keep-alive
[Aws::DynamoDB::Client 400 0.348192 0 retries] create_table(table_name:"test_cc_events",attribute_definitions:[{attribute_name:"resource_id_event",attribute_type:"S"},{attribute_name:"timestamp",attribute_type:"N"},{attribute_name:"organisation_id",attribute_type:"N"}],key_schema:[{attribute_name:"resource_id_event",key_type:"HASH"},{attribute_name:"timestamp",key_type:"RANGE"}],provisioned_throughput:{read_capacity_units:1,write_capacity_units:1},global_secondary_indexes:[{index_name:"gsi_orgid_timestamp",key_schema:[{attribute_name:"organisation_id",key_type:"HASH"},{attribute_name:"timestamp",key_type:"RANGE"}],projection:{projection_type:"INCLUDE",non_key_attributes:["_class"]},provisioned_throughput:{read_capacity_units:1,write_capacity_units:1}}]) Aws::DynamoDB::Errors::ValidationException The paramater 'TableName' is required but was not present in the request

Aws::DynamoDB::Errors::ValidationException: The paramater 'TableName' is required but was not present in the request
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.0.22/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.0.22/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.0.22/lib/seahorse/client/request.rb:70:in `send_request'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.0.22/lib/seahorse/client/base.rb:215:in `block (2 levels) in define_operation_methods'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/lib/dynamodb/driver.rb:29:in `create_table'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/db/dynamodb_schema.rb:65:in `create_events_table'
	from (irb):1
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /geome/releases/d98388511cf5209a6d4e58bf34901899517bcd04/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
irb(main):002:0>
```

**Comment by smeyfroi** [comment]
Got it. If I call the API as follows then the error goes away. Are the param names not being converted correctly?

```
irb(main):004:0> client.describe_table('TableName'=>'test_cc_events')
opening connection to dynamodb.eu-west-1.amazonaws.com:443...
opened
starting SSL for dynamodb.eu-west-1.amazonaws.com:443...
SSL established
<- "POST / HTTP/1.1\r\nContent-Type: application/x-amz-json-1.0\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.0.22 ruby/2.1.5 x86_64-linux\r\nX-Amz-Target: DynamoDB_20120810.DescribeTable\r\nX-Amz-Date: 20150210T111440Z\r\nHost: dynamodb.eu-west-1.amazonaws.com\r\nX-Amz-Content-Sha256: 174fd624232807655698d4c1b836fa07df4a1283e012bc3491b87f9672382831\r\nAuthorization: AWS4-HMAC-SHA256 Credential=REDACTED/20150210/eu-west-1/dynamodb/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=796d4d5e44996ebd9b1fc571aa56ccc938a2f6856b0eb7ffcc0b3895f695bd9a\r\nContent-Length: 30\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "x-amzn-RequestId: 6R380JINGS5QBRF1C02KDPNAANVV4KQNSO5AEMVJF66Q9ASUAAJG\r\n"
-> "x-amz-crc32: 3831511604\r\n"
-> "Content-Type: application/x-amz-json-1.0\r\n"
-> "Content-Length: 1040\r\n"
-> "Date: Tue, 10 Feb 2015 11:13:38 GMT\r\n"
-> "\r\n"
reading 1040 bytes...
-> "{\"Table\":{\"AttributeDefinitions\":[{\"AttributeName\":\"organisation_id\",\"AttributeType\":\"N\"},{\"AttributeName\":\"resource_id_event\",\"AttributeType\":\"S\"},{\"AttributeName\":\"timestamp\",\"AttributeType\":\"N\"}],\"CreationDateTime\":1.421443377033E9,\"GlobalSecondaryIndexes\":[{\"IndexName\":\"gsi_orgid_timestamp\",\"IndexSizeBytes\":1055808,\"IndexStatus\":\"ACTIVE\",\"ItemCount\":10979,\"KeySchema\":[{\"AttributeName\":\"organisation_id\",\"KeyType\":\"HASH\"},{\"AttributeName\":\"timestamp\",\"KeyType\":\"RANGE\"}],\"Projection\":{\"NonKeyAttributes\":[\"_class\"],\"ProjectionType\":\"INCLUDE\"},\"ProvisionedThroughput\":{\"LastDecreaseDateTime\":1.422099472762E9,\"NumberOfDecreasesToday\":0,\"ReadCapacityUnits\":1,\"WriteCapacityUnits\":1}}],\"ItemCount\":10979,\"KeySchema\":[{\"AttributeName\":\"resource_id_event\",\"KeyType\":\"HASH\"},{\"AttributeName\":\"timestamp\",\"KeyType\":\"RANGE\"}],\"ProvisionedThroughput\":{\"LastDecreaseDateTime\":1.422099472713E9,\"NumberOfDecreasesToday\":0,\"ReadCapacityUnits\":1,\"WriteCapacityUnits\":1},\"TableName\":\"test_cc_events\",\"TableSizeBytes\":4262581,\"TableStatus\":\"ACTIVE\"}}"
read 1040 bytes
Conn keep-alive
[Aws::DynamoDB::Client 200 0.025969 0 retries] describe_table("TableName"=>"test_cc_events")

=> {"Table"=>
  {"AttributeDefinitions"=>
    [{"AttributeName"=>"organisation_id", "AttributeType"=>"N"},
```

**Comment by smeyfroi** [comment]
And to insult to injury, specifying ```simple_json: false``` in the dynamodb client config gives you this:
```
[6] cloudchief »  client.describe_table('TableName'=>'cc_events');
ArgumentError: parameter validator found 2 errors:
  - missing required parameter params[:table_name]
  - unexpected value at params["TableName"]
from /usr/local/ruby/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.22/lib/seahorse/client/param_validator.rb:24:in `validate!'
```

My workaround for now is to change ```table_name: 'blah'``` into ```'TableName' => 'blah'``` when hitting the API. Be nice to fix this inconsistency in the SDK though.

**Comment by smeyfroi** [comment]
I think this is the ```simple_json:``` parameter. It *must* be false if you want to adopt the parameter conventions in the docs.
