### ISSUE TITLE
Getting "Unexpected list element termination" when trying to run update_distribution method for CloudFront

### ISSUE THREAD

**Issue by mylesmegyesi** [aws/aws-sdk-ruby#774]
This is a duplicate of an old [Issue](https://github.com/aws/aws-sdk-core-ruby/issues/99). It appears as though there was a fix that pushed to address the issue, but I'm still seeing the problem. I'm using version 2.0.38.

**Comment by trevorrowe** [comment]
There are tests that should prevent regressions on that issue. Can you provide a code example that demonstrates the issue you are having?

**Comment by mylesmegyesi** [comment]
Yep.

```ruby
require 'aws-sdk'

Aws.config.update({
  region: 'us-west-1',
  access_key_id: 'key-goes-here',
  secret_access_key: 'key-goes-here'
})

cf = Aws::CloudFront::Client.new

resp = cf.get_distribution(id: 'id-goes-here')

cf.update_distribution({
  id: resp.distribution[:id],
  distribution_config: resp.distribution[:distribution_config].to_h,
})
```
results in...

```bash
$ ruby test.rb
~/.rvm/gems/ruby-2.1.5@default/gems/aws-sdk-core-2.0.38/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Unexpected list element termination (Aws::CloudFront::Errors::MalformedInput)
        from ~/.rvm/gems/ruby-2.1.5@default/gems/aws-sdk-core-2.0.38/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'
        from ~/.rvm/gems/ruby-2.1.5@default/gems/aws-sdk-core-2.0.38/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
        from ~/.rvm/gems/ruby-2.1.5@default/gems/aws-sdk-core-2.0.38/lib/seahorse/client/plugins/response_target.rb:18:in `call'
        from ~/.rvm/gems/ruby-2.1.5@default/gems/aws-sdk-core-2.0.38/lib/seahorse/client/request.rb:70:in `send_request'
        from ~/.rvm/gems/ruby-2.1.5@default/gems/aws-sdk-core-2.0.38/lib/seahorse/client/base.rb:216:in `block (2 levels) in define_operation_methods'
        from test.rb:13:in `<main>'
```

**Comment by trevorrowe** [comment]
Thank you for the example code. Can you try your example again after removing the `#to_h` call on the distribution config?

```ruby
cf.update_distribution({
  id: resp.distribution[:id],
  distribution_config: resp.distribution[:distribution_config,
})
```

Also, the response data is a set of structures, so you don't need to hash-index the values. You can use Ruby methods:

```ruby
cf.update_distribution({
  id: resp.distribution.id,
  distribution_config: resp.distribution.distribution_config,
})
```

By calling `#to_h` I got the same error as you. I'm pretty certain I know why. It has to do with the empty list values and if they should be serialized or not.

**Comment by mylesmegyesi** [comment]
I removed the `to_h` and everything works. That's so much!
