### ISSUE TITLE
pageable_response infinite recursion for ElasticTranscoder::Client#create_job

### ISSUE THREAD

**Issue by StaymanHou** [aws/aws-sdk-ruby#784]
I'm invoking Aws::ElasticTranscoder::Client#create_job. The job get created & proceeded successfully. However, the client raises error.

```
SystemStackError:
       stack level too deep
     # /home/vagrant/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.0.39/lib/aws-sdk-core/pageable_response.rb:77:in `each'
     # /home/vagrant/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.0.39/lib/aws-sdk-core/pageable_response.rb:77:in `each'
    ...
     # /home/vagrant/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.0.39/lib/aws-sdk-core/pageable_response.rb:77:in `each'
     # ./spec/jobs/videos_process_job_spec.rb:5:in `block (2 levels) in <top (required)>'
```

**Comment by trevorrowe** [comment]
Can you share a code example of how you are calling `#create_job` that triggers this behavior? This particular operation is not pageable and should not trigger page enumeration.

**Comment by StaymanHou** [comment]
Sure, here's my code:

```ruby
class VideosProcessJob < ActiveJob::Base
  queue_as :default

  def perform(video_id)
    @video_id = video_id
    elastictranscoder = Aws::ElasticTranscoder::Client.new

    job = elastictranscoder.create_job(
      # required
      pipeline_id: Settings.elastic_transcoder_job.pipeline_id,
      # required
      input: input_settings,
      outputs: [output_settings_mp4, output_settings_webm]
    )
  end

  private

  def input_settings
    {
      key: "videos/#{@video_id}/uploaded_video_file",
      frame_rate: 'auto',
      resolution: 'auto',
      aspect_ratio: 'auto',
      interlaced: 'auto',
      container: 'auto'
    }
  end

  def output_settings_mp4
    {
      key: "videos/#{@video_id}.mp4",
      thumbnail_pattern: "thumbnails/#{@video_id}-{count}",
      rotate: 'auto',
      preset_id: Settings.elastic_transcoder_job.mp4_preset_id
    }
  end

  def output_settings_webm
    {
      key: "videos/#{@video_id}.webm",
      rotate: 'auto',
      preset_id: Settings.elastic_transcoder_job.webm_preset_id
    }
  end
end
```

**Comment by StaymanHou** [comment]
looking into the source `pageable_response.rb`:
```ruby
    def each(&block)
      return enum_for(:each_page) unless block_given?
      response = self
      yield(response)
      until response.last_page?
        response = response.next_page
        yield(response)
      end
    end
    alias each_page each
```
The first `yield(response)` doesn't make sense to me.

**Comment by StaymanHou** [comment]
Never mind. It's related to rspec matcher. The code is working fine. However, when invoked in a rspec expectation, it results in the error.

Thank you very much, @trevorrowe.

**Comment by trevorrowe** [comment]
@StaymanHou The pageable response is a decorator of a vanilla response object. Many AWS services will truncate lists of results to limit response sizes.  A pageable response makes a response enumerable, allowing it to fetch the next page of results.  When enumerating all responses the page must yield itself first before fetching the next page.
