### ISSUE TITLE
Sometimes the PUT to write a small object takes 10-15 minutes

### ISSUE THREAD

**Issue by jonhyman** [aws/aws-sdk-ruby#847]
In our application, we frequently see extremely large S3 upload times even for small objects (up to a few hundred kb):

![image](https://cloud.githubusercontent.com/assets/832655/8263677/3d2ad88a-16ab-11e5-97fd-45e005f2a850.png)

In these cases, when we retry, they tend to upload quickly. It happens probably 1% of the time in our application, but we haven't been able to reproduce in a console. We host with Rackspace but have AWS Direct Connect in our data center.

Is there a good way to debug these? We're on aws-sdk 1.64.0

**Comment by trevorrowe** [comment]
Do these requests eventually succeed? Have you disable the default HTTP open or read time-outs? The table above implies that the time is spent with Net::HTTP which should have triggered default timeouts.

**Comment by jonhyman** [comment]
Yeah, they eventually succeed, though a few get killed by our process timeout checks and restart automatically and complete. We don't do anything other than this in one part of our code

```ruby
@s3 = AWS::S3.new(:access_key_id => @aws_access_key, :secret_access_key => @aws_access_secret)
bucket = @s3.buckets[@aws_bucket_name]
s3_object = @s3_bucket.objects[key_name]
s3_object.write(File.open(file_path, 'r'))
```

and another area where we see timeouts is uploading from the Paperclip gem. Is there a way to set the timeout myself?

**Comment by trevorrowe** [comment]
The SDK defaults the Net::HTTP read timeout to 60 seconds and the open timeout to 15 seconds. I'm surprised you haven't hit these. Also, Amazon S3 will often close stalled connections. If you stop sending bytes for ~ 30 seconds, they can close the connection.

Is that example you show above timing the network time or the fully SDK client call?

**Comment by jonhyman** [comment]
I believe it's the network time, I'm getting that from a New Relic transaction trace. For example, here's one that just happened 2 minutes ago in some code which performs png optimization and uploads to S3. Based on the extremely short image optimization time (optipng spent ~2.3 seconds and advpng spent 169ms) this image is likely very small. The upload to S3 took 782 seconds to succeed, though. 

![image](https://cloud.githubusercontent.com/assets/832655/8313912/ef0ef684-19b3-11e5-80a3-d526f23e66cc.png)

**Comment by jonhyman** [comment]
But as I said, not all uploads take a long time, it's just about 1% of the time.

**Comment by jonhyman** [comment]
Upon further inspection, the image from the 782 second upload looks looks like it was 21kb.

**Comment by trevorrowe** [comment]
The fact that it is taking so long, and yet succeeding suggests its time spent uploading, not opening an HTTP connection or waiting on the response.

```ruby
s3_object.write(File.open(file_path, 'r'))
```

Is it possible the `#read` calls on your file are slow? Also, I noticed in your example that you are not closing the file, and you should probably open them in binary mode. You can do this yourself, or you can use the `:file` option and the SDK will manage the file.

```ruby
# block mode auto-closes the file
File.open(file_path, 'rb') do |file|
  s3_object.write(file)
end

# or you can allow the SDK to manage the file
s3_object.write(file: file_path)
```

**Comment by jonhyman** [comment]
Hm. I doubt it's our reads. We're on SATADOM flash storage.

In the example there with the image processing, the upload is handled by the Paperclip gem. We're on the latest version but looking at [source](https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/s3.rb#L359) it seems like it is conceptually similar.

**Comment by jonhyman** [comment]
Though I will make that change, thanks for the heads up.

**Comment by jonhyman** [comment]
@trevorrowe do you have any other suggestions for how I may be able to troubleshoot and figure out what is going on?

**Comment by jonhyman** [comment]
I've been attempting to repro and then do a thread trace. It looks like it hangs in the request in connection pool. I'll keep digging, perhaps a timeout isn't getting set properly somewhere.

```
Jun 29 11:35:28 :worker production.log:  [ 3:35:28.476373370] (8344) [WARN] Thread TID-osussmirk 
Jun 29 11:35:28 :worker production.log:  [ 3:35:28.476620388] (8344) [WARN] /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `syswrite'
Jun 29 11:35:28 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `do_write'
Jun 29 11:35:28 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:344:in `write'
Jun 29 11:35:28 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `copy_stream'
Jun 29 11:35:28 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `send_request_with_body_stream'
Jun 29 11:35:28 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:122:in `exec'
Jun 29 11:35:28 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:27:in `block in new_transport_request'
Jun 29 11:35:28 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:26:in `catch'
Jun 29 11:35:28 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:26:in `new_transport_request'
Jun 29 11:35:28 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1384:in `request'


Jun 29 11:39:24 :worker production.log:  [ 3:39:24.716904843] (8344) [WARN] /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `syswrite'
Jun 29 11:39:24 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `do_write'
Jun 29 11:39:24 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:344:in `write'
Jun 29 11:39:24 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `copy_stream'
Jun 29 11:39:24 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `send_request_with_body_stream'
Jun 29 11:39:24 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:122:in `exec'
Jun 29 11:39:24 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:27:in `block in new_transport_request'
Jun 29 11:39:24 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:26:in `catch'
Jun 29 11:39:24 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:26:in `new_transport_request'
Jun 29 11:39:24 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1384:in `request'

Jun 29 11:40:22 :worker production.log:  [ 3:40:22.261013828] (8344) [WARN] /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `syswrite'
Jun 29 11:40:22 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `do_write'
Jun 29 11:40:22 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:344:in `write'
Jun 29 11:40:22 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `copy_stream'
Jun 29 11:40:22 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `send_request_with_body_stream'
Jun 29 11:40:22 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:122:in `exec'
Jun 29 11:40:22 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:27:in `block in new_transport_request'
Jun 29 11:40:22 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:26:in `catch'
Jun 29 11:40:22 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:26:in `new_transport_request'
Jun 29 11:40:22 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1384:in `request'

Jun 29 11:41:58 :worker production.log:  [ 3:41:58.549290483] (8344) [WARN] /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `syswrite'
Jun 29 11:41:58 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `do_write'
Jun 29 11:41:58 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:344:in `write'
Jun 29 11:41:58 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `copy_stream'
Jun 29 11:41:58 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `send_request_with_body_stream'
Jun 29 11:41:58 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:122:in `exec'
Jun 29 11:41:58 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:27:in `block in new_transport_request'
Jun 29 11:41:58 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:26:in `catch'
Jun 29 11:41:58 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:26:in `new_transport_request'
Jun 29 11:41:58 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1384:in `request'

Jun 29 11:48:35 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `do_write'
Jun 29 11:48:35 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:344:in `write'
Jun 29 11:48:35 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `copy_stream'
Jun 29 11:48:35 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `send_request_with_body_stream'
Jun 29 11:48:35 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:122:in `exec'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:27:in `block in new_transport_request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:26:in `catch'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/patch.rb:26:in `new_transport_request'
Jun 29 11:48:35 :worker production.log:  /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1384:in `request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request_with_newrelic_trace'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent.rb:426:in `disable_all_tracing'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newrelic_trace'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/cross_app_tracing.rb:48:in `tl_trace_http_request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/connection_pool.rb:356:in `request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/net_http_handler.rb:64:in `block in handle'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/connection_pool.rb:131:in `session_for'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/http/net_http_handler.rb:56:in `handle'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:253:in `block in make_sync_request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:282:in `retry_server_errors'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/s3/region_detection.rb:11:in `retry_server_errors'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:249:in `make_sync_request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:511:in `block (2 levels) in client_request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:391:in `log_client_request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:477:in `block in client_request'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:373:in `return_or_raise'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:476:in `client_request'
Jun 29 11:48:35 :worker production.log:  (eval):3:in `put_object'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.64.0/lib/aws/s3/s3_object.rb:1765:in `write_with_put_object'
Jun 29 11:48:35 :worker production.log:  /var/www/platform/shared/dashboard/bundle/ruby/2.2.0/gems/aws-sdk-
```

**Comment by trevorrowe** [comment]
Those look like sample log entries from 5 slow uploads from one day. Is that correct? 

    Jun 29 11:40:22 :worker production.log:  [ 3:40:22.261013828] (8344) [WARN] /opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/openssl/buffering.rb:326:in `syswrite'

This would imply the time is being spent waiting for OpenSSL to write to the socket. It does not appear to be getting stuck in SDK code. Short of instrumenting your code with monkey-patches that collect more fine-grained timing information with context (such as the age of the http connection), I'm not sure how to track this down. Thoughts?

**Comment by jonhyman** [comment]
It was all the same upload. Also it looks like it didn't succeed. I may be
misreading whether or not they succeed, as our code has some automatic
retry logic after about 15 minutes.

Ill keep looking into this on my end. Thanks.

**Comment by jonhyman** [comment]
I don't think this is related to aws-sdk. https://github.com/mperham/sidekiq/issues/702#issuecomment-122429014

**Comment by awood45** [comment]
Thanks for the update! If you do track this down to a particular MRI version, we'd love to hear about it in case it comes up again.
