### ISSUE TITLE
Incorrect Aws::DynamoDB::Client#stub_data method signature

### ISSUE THREAD

**Issue by ajvondrak** [aws/aws-sdk-ruby#867]
Don't mean to nag, but for visibility (before the release that @trevorrowe mentioned would happen), I made a [comment](https://github.com/aws/aws-sdk-ruby/commit/3cf1a5fe324141d76a2a5d86fbba511832509772#commitcomment-12024222) regarding the recent fix to #863.

To add to that comment, this issue shows itself in the following way (so maybe this would be a good test to add):
```
[1] pry(main)> require 'aws-sdk'
=> true

[2] pry(main)> client = Aws::DynamoDB::Client.new(stub_responses: true)
=> #<Aws::DynamoDB::Client>

[3] pry(main)> client.get_item(table_name: 'foo', key: { id: 'bar' })
ArgumentError: wrong number of arguments (1 for 2)
from /Users/alexv/.rvm/gems/ruby-2.1.3/bundler/gems/aws-sdk-ruby-3cf1a5fe3241/aws-sdk-core/lib/aws-sdk-core/dynamodb.rb:25:in `stub_data'

[4] pry(main)> wtf?
Exception: ArgumentError: wrong number of arguments (1 for 2)
--
0: /Users/alexv/.rvm/gems/ruby-2.1.3/bundler/gems/aws-sdk-ruby-3cf1a5fe3241/aws-sdk-core/lib/aws-sdk-core/dynamodb.rb:25:in `stub_data'
1: /Users/alexv/.rvm/gems/ruby-2.1.3/bundler/gems/aws-sdk-ruby-3cf1a5fe3241/aws-sdk-core/lib/aws-sdk-core/client_stubs.rb:182:in `default_stub'
2: /Users/alexv/.rvm/gems/ruby-2.1.3/bundler/gems/aws-sdk-ruby-3cf1a5fe3241/aws-sdk-core/lib/aws-sdk-core/client_stubs.rb:172:in `block in next_stub'
3: /Users/alexv/.rvm/gems/ruby-2.1.3/bundler/gems/aws-sdk-ruby-3cf1a5fe3241/aws-sdk-core/lib/aws-sdk-core/client_stubs.rb:169:in `synchronize'
4: /Users/alexv/.rvm/gems/ruby-2.1.3/bundler/gems/aws-sdk-ruby-3cf1a5fe3241/aws-sdk-core/lib/aws-sdk-core/client_stubs.rb:169:in `next_stub'
5: /Users/alexv/.rvm/gems/ruby-2.1.3/bundler/gems/aws-sdk-ruby-3cf1a5fe3241/aws-sdk-core/lib/aws-sdk-core/plugins/stub_responses.rb:40:in `call'
6: /Users/alexv/.rvm/gems/ruby-2.1.3/bundler/gems/aws-sdk-ruby-3cf1a5fe3241/aws-sdk-core/lib/seahorse/client/plugins/content_length.rb:12:in `call'
7: /Users/alexv/.rvm/gems/ruby-2.1.3/bundler/gems/aws-sdk-ruby-3cf1a5fe3241/aws-sdk-core/lib/aws-sdk-core/plugins/dynamodb_crc32_validation.rb:27:in `call'
8: /Users/alexv/.rvm/gems/ruby-2.1.3/bundler/gems/aws-sdk-ruby-3cf1a5fe3241/aws-sdk-core/lib/aws-sdk-core/json/error_handler.rb:8:in `call'
9: /Users/alexv/.rvm/gems/ruby-2.1.3/bundler/gems/aws-sdk-ruby-3cf1a5fe3241/aws-sdk-core/lib/aws-sdk-core/plugins/request_signer.rb:78:in `call'
```

**Comment by trevorrowe** [comment]
Thanks for the heads up!
