### ISSUE TITLE
How to upload apk file for device farm?

### ISSUE THREAD

**Issue by vbanthia** [aws/aws-sdk-ruby#876]
I am trying to create a new upload for DeviceFarm service but still could not.

Script is below

```ruby
Aws.config.update({
  region: "...",
  credentials: Aws::Credentials.new(...)
})
df_client = Aws::DeviceFarm::Client.new()

upload = df_client.create_upload({
  project_arn: "PROJECT_ARN",
  name: "test.apk",
  content_type: "application/octet-stream",
  type: "ANDROID_APP"
})
```

This is the response I am getting.
```
#<struct Aws::DeviceFarm::Types::CreateUploadResult
 upload=
  #<struct Aws::DeviceFarm::Types::Upload
   arn="xxxxxxxxx",
   name="test.apk",
   created=2015-07-15 20:55:38 +0900,
   type="ANDROID_APP",
   status="INITIALIZED",
   url=
    "URL",
   metadata=nil,
   content_type="application/octet-stream",
   message=nil>>
```

Test binary file is "test.apk" is located in the current directory. 

I am not sure if the file test.apk is being uploaded or not. Can anyone tell me how to upload test.apk file?

Thanks

**Comment by vbanthia** [comment]
Understood how to upload the file.

While creating upload using create_upload api, pre-signed Amazon S3 URL will be returned in response. And then upload apk on that url. (http://docs.aws.amazon.com/AmazonS3/latest/dev/UploadObjectPreSignedURLRubySDK.html)

Sample code:

```ruby
s3_url = "xxxxxxxxx" # got from create_upload response
url = URI.parse(s3_url)
apk_contents = File.open("buggy_app.apk", "rb").read

Net::HTTP.start(url.host) do |http|
  http.send_request("PUT", url.request_uri, apk_contents, {"content-type" => "application/octet-stream"})
end
```

**Comment by JiaYangSF** [comment]
I was trying to run the webapp test that passed in device farm in jenkins, then I got this:
[JENKINS] Archiving /apps/automation/web_mobile/pom.xml to com.myfico.webapp/myFico-WebApp/0.0.1-SNAPSHOT/myFico-WebApp-0.0.1-SNAPSHOT.pom
[JENKINS] Archiving /apps/automation/web_mobile/target/myFico-WebApp-0.0.1-SNAPSHOT.jar to com.myfico.webapp/myFico-WebApp/0.0.1-SNAPSHOT/myFico-WebApp-0.0.1-SNAPSHOT.jar
[JENKINS] Archiving /apps/automation/web_mobile/target/myFico-WebApp-0.0.1-SNAPSHOT-tests.jar to com.myfico.webapp/myFico-WebApp/0.0.1-SNAPSHOT/myFico-WebApp-0.0.1-SNAPSHOT-tests.jar
[JENKINS] Archiving /apps/automation/web_mobile/target/WebApp-SmokeTest-NPPHappyPath-prodID-1.zip to com.myfico.webapp/myFico-WebApp/0.0.1-SNAPSHOT/myFico-WebApp-0.0.1-SNAPSHOT.zip
[AWSDeviceFarm] Using Project 'NPP-WebApp'
[AWSDeviceFarm] Using DevicePool 'Top Devices'
[AWSDeviceFarm] Using App 'app-qa1-debug.apk'
[AWSDeviceFarm] Archiving artifact 'app-qa1-debug.apk'
[AWSDeviceFarm] Uploading app-qa1-debug.apk to S3
ERROR: Build step failed with exception
java.util.UnknownFormatConversionException: Conversion = 'i'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2691)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2720)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.jenkinsci.plugins.awsdevicefarm.AWSDeviceFarm.upload(AWSDeviceFarm.java:385)
	at org.jenkinsci.plugins.awsdevicefarm.AWSDeviceFarm.upload(AWSDeviceFarm.java:354)
	at org.jenkinsci.plugins.awsdevicefarm.AWSDeviceFarm.upload(AWSDeviceFarm.java:341)
	at org.jenkinsci.plugins.awsdevicefarm.AWSDeviceFarm.uploadApp(AWSDeviceFarm.java:211)
	at org.jenkinsci.plugins.awsdevicefarm.AWSDeviceFarmRecorder.perform(AWSDeviceFarmRecorder.java:311)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1047)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Build step 'Run Tests on AWS Device Farm' marked build as failure
Finished: FAILURE

Test Framework:
Appium - TestNg - Java
.apk file located in the root of the workspace
