### ISSUE TITLE
Aws::IAM::Policy.versions goes asplodey.

### ISSUE THREAD

**Issue by MrJoy** [aws/aws-sdk-ruby#879]
```
ERROR: NoMethodError: undefined method `each' for #<Seahorse::Client::Response:0x007fbdfae46960>
ERROR:   /Users/jfrisby/.rvm/gems/ruby-2.1.5@cnc-renbot/gems/aws-sdk-core-2.1.7/lib/seahorse/client/response.rb:81:in `method_missing'
ERROR:   /Users/jfrisby/.rvm/gems/ruby-2.1.5@cnc-renbot/gems/aws-sdk-resources-2.1.7/lib/aws-sdk-resources/operations.rb:127:in `all_batches'
ERROR:   /Users/jfrisby/.rvm/gems/ruby-2.1.5@cnc-renbot/gems/aws-sdk-resources-2.1.7/lib/aws-sdk-resources/collection.rb:18:in `each'
ERROR:   /Users/jfrisby/.rvm/gems/ruby-2.1.5@cnc-renbot/gems/aws-sdk-resources-2.1.7/lib/aws-sdk-resources/collection.rb:18:in `each'
```

(Thereafter in the stack trace is my code / other code I'm using.)

I'd swear this was working fine and broke in the vicinity of when we updated to... 2.1.0-ish?  (we updated on 6/18...)

Our relevant code looks a bit like so:

```ruby
iam         = Aws::IAM::Resource.new(credentials: cred,
                                     region:      ENV.fetch("AWS_REGION"))
policies    = iam.policies(scope: "Local").to_a
# ...
policy      = policies.find { |pp| pp.policy_name == name }
versions    = policy.versions # <-- This goes boom.

**Comment by trevorrowe** [comment]
I've added the missing paginator for `Aws::IAM::Client#list_policy_versions` which should stop this from raising. This fix should be released shortly. Thanks for reporting the issue!
