### ISSUE TITLE
Resource::vpc_peering_connections returning erroneous response

### ISSUE THREAD

**Issue by joaogbcravo** [aws/aws-sdk-ruby#914]
Trying to iterate over peering connections, like documentation says at http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Resource.html#vpc_peering_connections-instance_method

gives the following error:

```ruby
irb(main):001:0> require 'aws-sdk'
=> true
irb(main):002:0> ec2 = Aws::EC2::Resource.new(region: 'us-west-2')
=> #<Aws::EC2::Resource>
irb(main):003:0> ec2.vpc_peering_connections()
=> #<Aws::Resources::Collection type="Aws::EC2::VpcPeeringConnection" limit=nil params={}>
irb(main):004:0> ec2.vpc_peering_connections.each do |vpcpeeringconnection|
irb(main):005:1*   puts vpcpeeringconnection
irb(main):006:1> end
NoMethodError: undefined method `each' for #<Seahorse::Client::Response:0x007fe39164ba50>
	from /Users/cravo/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.1.17/lib/seahorse/client/response.rb:87:in `method_missing'
	from /Users/cravo/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-resources-2.1.17/lib/aws-sdk-resources/operations.rb:127:in `all_batches'
	from /Users/cravo/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-resources-2.1.17/lib/aws-sdk-resources/collection.rb:18:in `each'
	from /Users/cravo/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-resources-2.1.17/lib/aws-sdk-resources/collection.rb:18:in `each'
	from (irb):4
	from /opt/chefdk/embedded/bin/irb:11:in `<main>'
irb(main):007:0>
```

**Comment by trevorrowe** [comment]
Thank you for reporting this issue. I forgot to reference this issue from the commit that is the actual fix, fc89f16f04750936b96910bd4ecbb90287b1dca8.
