### ISSUE TITLE
UNTRAPPED ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by oncletom** [aws/aws-sdk-ruby#930]
Hello,

I started to encounter this error recently, with `aws-sdk-v1-1.66.0`.
```
respond_activity_task_failed(:details=>#<String "/usr/lib/ruby/2.1.0/net/http.rb:923:in `connect'
/usr/lib/ruby/2.1.0/net/http.rb:923:in `block in connect'
/usr/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
/usr/lib/ruby/2.1.0/net/http.rb:923:in `connect'
/usr/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
/usr/lib/ruby/2.1.0/net/http.rb:852:in `start'
/usr/lib/ruby/2.1.0/net/http.rb:1375:in `request'
/usr/lib/ruby/2.1.0/net/http.rb:1398:in `send_entity'
/usr/lib/ruby/2.1.0/net/http.rb:1192:in `patch'
/app/lib/metadata_serializer.rb:27:in `save!'
./bin/worker:31:in `handle'
/app/.gems/gems/foobar_workflow-0.5.3/lib/foobar_workflow/worker.rb:29:in `block in start'
/app/.gems/gems/aws-sdk-v1-1.66.0/lib/aws/simple_workflow/activity_task_collection.rb:112:in `block (2 levels) in poll'
/app/.gems/gems/aws-sdk-v1-1.66.0/lib/aws/simple_workflow/activity_task_collection.rb:86:in `poll_for_single_task'
/app/.gems/gems/aws-sdk-v1-1.66.0/lib/aws/simple_workflow/activity_task_collection.rb:111:in `block in poll'
/app/.gems/gems/aws-sdk-v1-1.66.0/l" ... (1278 bytes)>,:reason=>"UNTRAPPED ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B
```

Any idea why I would encounter that?

Thanks :-)

**Comment by oncletom** [comment]
It seems to be related to the HTTP lib – not aws-sdk.

Sorry for the confusion!

**Comment by davejlong** [comment]
There seems to be a core issue with Ruby's HTTP lib. I've found it in the Mailgun client and AWS SDK client so far. I found a work around for Mailgun by using CURLs certificates, but it doesn't work for AWS. Any known workarounds?

**Comment by oncletom** [comment]
It is mainly due to your OS — it seems to be related to either a CA certificate missing in the chain or a version of OpenSSL ruby is backed by.
