### ISSUE TITLE
getaddrinfo: Name or service not known with opsworks

### ISSUE THREAD

**Issue by HienNguyenAsnet** [aws/aws-sdk-ruby#936]
I try list all stack from opsworks
```
Aws::OpsWorks::Client.new.describe_stacks
```

Then I got error
```
Seahorse::Client::NetworkingError: getaddrinfo: Name or service not known
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:858:in `start'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/seahorse/client/net_http/connection_pool.rb:292:in `start_session'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/seahorse/client/net_http/connection_pool.rb:104:in `session_for'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/seahorse/client/net_http/handler.rb:108:in `session'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/seahorse/client/net_http/handler.rb:60:in `transmit'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/seahorse/client/net_http/handler.rb:34:in `call'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/seahorse/client/plugins/content_length.rb:12:in `call'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/json/error_handler.rb:8:in `call'
... 13 levels...
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/seahorse/client/plugins/endpoint.rb:34:in `call'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/plugins/param_converter.rb:21:in `call'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/seahorse/client/plugins/response_target.rb:18:in `call'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/aws-sdk-core-2.1.4/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from (irb):29
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/rvm/gems/ruby-2.2.2@ruvixx/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Although, I still connect to S3 successfully. Any help?

**Comment by trevorrowe** [comment]
What region are you attempting to connect to? A list of supported OpsWorks regions can be found here:
http://docs.aws.amazon.com/general/latest/gr/rande.html#opsworks_region

**Comment by HienNguyenAsnet** [comment]
@trevorrowe 
```
AWS_REGION=us-west-2
```

Let me know something wrong

**Comment by HienNguyenAsnet** [comment]
I find out the reason. Opsworks only support region ```us-east-1```
Change config ```AWS_REGION``` to ```us-east-1``` then it's will work
```
AWS_REGION=us-east-1
```

Thank @trevorrowe
