### ISSUE TITLE
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by orgar** [aws/aws-sdk-ruby#968]
Hi,
I'm running on ruby 2.2.3, aws-sdk 2.1.31
I'm getting this error when i'm trying to run this code: 

```ruby
Aws.config.update(credentials: Aws::Credentials.new(access_key, secret_key), region: region) 
Aws::S3::Resource.new.bucket(opt[:bucket]).object(File.basename(opt[:file])).upload_file(opt[:file])
```
 

```
[root@mfc $] uname -a
Darwin erans-mbp.upsteed.com 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64
[root@mfc $]
[root@mfc $] gem list
*** LOCAL GEMS ***
amq-protocol (2.0.0, 1.9.2)
aws-sdk (2.1.31, 2.1.15, 1.64.0)
aws-sdk-core (2.1.31, 2.1.15)
aws-sdk-resources (2.1.31, 2.1.15)
aws-sdk-v1 (1.64.0)
bigdecimal (1.2.6)
bundler (1.10.6)
bundler-unload (1.0.2)
bunny (0.9.8)
celluloid (0.16.0)
colorize (0.7.7)
devops-center-api (0.0.2.42)
domain_name (0.5.25)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
highline (1.7.8)
hitimes (1.2.2)
http-cookie (1.0.2)
httparty (0.13.7)
io-console (0.4.3)
jmespath (1.1.3, 1.0.2)
json (1.8.3, 1.8.1)
kworker (0.3.4, 0.2.4)
logstash-event (1.2.02)
logstash-logger (0.11.0, 0.10.1)
mime-types (2.6.2)
mini_portile (0.6.2)
msgpack (0.6.2, 0.6.0)
multi_json (1.11.2)
multi_xml (0.5.5)
netrc (0.10.3)
nokogiri (1.6.6.2)
oj (2.12.12)
pg (0.18.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
redis (3.2.1)
rest-client (1.8.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
stud (0.0.21, 0.0.20)
timers (4.0.1)
unf (0.1.4)
unf_ext (0.0.7.1)
```

```
Error log :  
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/Users/asi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect'
/Users/asi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
/Users/asi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
/Users/asi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:98:in `call'
/Users/asi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
/Users/asi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect'
/Users/asi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
/Users/asi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:858:in `start'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/seahorse/client/net_http/connection_pool.rb:292:in `start_session'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/seahorse/client/net_http/connection_pool.rb:104:in `session_for'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/seahorse/client/net_http/handler.rb:108:in `session'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/seahorse/client/net_http/handler.rb:60:in `transmit'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/seahorse/client/net_http/handler.rb:34:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/seahorse/client/plugins/content_length.rb:12:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/s3_request_signer.rb:149:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/s3_request_signer.rb:33:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/s3_request_signer.rb:124:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/s3_redirects.rb:15:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/retry_errors.rb:87:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/retry_errors.rb:118:in `retry_request'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/retry_errors.rb:101:in `retry_if_possible'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/retry_errors.rb:89:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/retry_errors.rb:118:in `retry_request'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/retry_errors.rb:101:in `retry_if_possible'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/retry_errors.rb:89:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/retry_errors.rb:118:in `retry_request'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/retry_errors.rb:101:in `retry_if_possible'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/retry_errors.rb:89:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/s3_md5s.rb:33:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/s3_expect_100_continue.rb:21:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/s3_bucket_dns.rb:31:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/rest/handler.rb:7:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/aws-sdk-core/plugins/param_converter.rb:21:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/seahorse/client/request.rb:70:in `send_request'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-core-2.1.31/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-resources-2.1.31/lib/aws-sdk-resources/services/s3/file_uploader.rb:42:in `block in put_object'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-resources-2.1.31/lib/aws-sdk-resources/services/s3/file_uploader.rb:49:in `open_file'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-resources-2.1.31/lib/aws-sdk-resources/services/s3/file_uploader.rb:41:in `put_object'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-resources-2.1.31/lib/aws-sdk-resources/services/s3/file_uploader.rb:34:in `upload'
/Users/asi/.rvm/gems/ruby-2.2.3@global/gems/aws-sdk-resources-2.1.31/lib/aws-sdk-resources/services/s3/object.rb:231:in `upload_file'
```

**Comment by trevorrowe** [comment]
```
Error log :  
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

This error indicates that Ruby's OpenSSL was unable to verify the peer certificate while establishing an SSL connection to Amazon S3. This particular error is very common when your system does not have a correctly configured openssl library with certificate. For example, this happens on all Windows installation of Ruby.

As a work-around the SDK ships with an optional SSL cert bundle. Browser frequently bundle their own certs for the same reason. You can opt-in to use the bundled cert by calling:

```
Aws.use_bundled_cert!
```

**Comment by awood45** [comment]
Going to close this for now - please feel free to reopen if this doesn't work for you.

**Comment by scrossan** [comment]
For anybody googling the error message, I had the same problem - @trevorrowe's suggestion fixed it.

You'll want to put `Aws.use_bundled_cert!` where you're requiring the aws-sdk, so for example in my `Rakefile`:
```ruby
# Requires:
require 'pp'
require 'aws-sdk'
require 'pry'
require 'open4'
require 'colorize'

Aws.use_bundled_cert!

# Disable stdout buffer
STDOUT.sync = true

# Include substasks from different namespaces
Dir.glob('rake/*.rake').map { |rake| import rake }
```

Thanks guys!

**Comment by VedAustin** [comment]
I am implementing the above solution but am getting a new error on "resource not found":
```
$ bundle exec ruby bin/sync_sfdc_pull
{:timestamp=>"2017-11-29T17:40:19.871061-0800", :message=>"Successful authentication, session id = 00D29000000DYZp!ARMAQHmmWf7fcUzcHtOqFLVj8gwPYG6ryOVj1Ni3os6OFokEuxP9hw1ZEb4GJlUqbNJthiT6dJz3EbvAj.Jr8aG0tSsnde0A", :level=>:debug, :file=>"/Users/vshetty/prod_intel/yoda-sfdc-sync/lib/sync_sfdc_pull.rb", :line=>"103"}
{:timestamp=>"2017-11-29T17:40:19.872060-0800", :message=>"************ Opportunity ************", :level=>:debug, :file=>"/Users/vshetty/prod_intel/yoda-sfdc-sync/lib/sync_sfdc_pull.rb", :line=>"398"}
{:timestamp=>"2017-11-29T17:40:19.873060-0800", :message=>"Retrieving pull cursor from Dynamo table current-tatooine-cursors for sfdc_pull_Opportunity", :level=>:debug, :file=>"/Users/vshetty/prod_intel/yoda-sfdc-sync/lib/sync_sfdc_pull.rb", :line=>"117"}
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.2.9/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Requested resource not found (Aws::DynamoDB::Errors::ResourceNotFoundException)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.2.9/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:112:in `call'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.2.9/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.2.9/lib/seahorse/client/plugins/response_target.rb:21:in `call'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.2.9/lib/seahorse/client/request.rb:70:in `send_request'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.2.9/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
        from C:/Users/vshetty/prod_intel/yoda-sfdc-sync/lib/sync_sfdc_pull.rb:118:in `get_pull_cursor'
        from C:/Users/vshetty/prod_intel/yoda-sfdc-sync/lib/sync_sfdc_pull.rb:149:in `pull_outdated_records'
        from C:/Users/vshetty/prod_intel/yoda-sfdc-sync/lib/sync_sfdc_pull.rb:399:in `block in go'
        from C:/Users/vshetty/prod_intel/yoda-sfdc-sync/lib/sync_sfdc_pull.rb:397:in `each'
        from C:/Users/vshetty/prod_intel/yoda-sfdc-sync/lib/sync_sfdc_pull.rb:397:in `go'
        from bin/sync_sfdc_pull:4:in `<main>'
```
