### ISSUE TITLE
v1 AWS IAM credentials issue

### ISSUE THREAD

**Issue by eldondevcg** [aws/aws-sdk-ruby#973]
On instances with IAM-based credentials, when fetching from S3 we still periodically get the following error:
```
Missing Credentials.

Unable to find AWS credentials.  You can configure your AWS credentials
a few different ways:

* Call AWS.config with :access_key_id and :secret_access_key

* Export AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to ENV

* On EC2 you can run instances with an IAM instance profile and credentials
  will be auto loaded from the instance metadata service on those
  instances.

* Call AWS.config with :credential_provider.  A credential provider should
  either include AWS::Core::CredentialProviders::Provider or respond to
  the same public methods.

= Ruby on Rails

In a Ruby on Rails application you may also specify your credentials in
the following ways:

* Via a config initializer script using any of the methods mentioned above
  (e.g. RAILS_ROOT/config/initializers/aws-sdk.rb).

* Via a yaml configuration file located at RAILS_ROOT/config/aws.yml.
  This file should be formated like the default RAILS_ROOT/config/database.yml
  file.
```

It has gotten less prevalent after upgrading to 1.66, but still fails intermittently.

**Comment by eldondevcg** [comment]
Here is the relevant backtrace
``` 
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/credential_providers.rb:41:in `credentials'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/credential_providers.rb:404:in `credentials'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/credential_providers.rb:137:in `credentials'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/credential_providers.rb:135:in `each'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/credential_providers.rb:135:in `credentials'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/credential_providers.rb:62:in `access_key_id'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:549:in `build_request'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:491:in `send'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:491:in `client_request'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/response.rb:175:in `call'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/response.rb:175:in `build_request'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/response.rb:114:in `initialize'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:203:in `new'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:203:in `new_response'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:490:in `client_request'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:391:in `log_client_request'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:477:in `client_request'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:373:in `return_or_raise'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:476:in `client_request'
- (eval):3:in `list_object_versions'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/s3/bucket_version_collection.rb:66:in `list_request'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/s3/paginated_collection.rb:29:in `_each_item'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/collection/with_limit_and_next_token.rb:54:in `_each_batch'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/collection.rb:80:in `each_batch'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/core/collection.rb:47:in `each'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/s3/bucket_version_collection.rb:48:in `each'
- /var/bundles/ruby/1.8/gems/aws-sdk-v1-1.66.0/lib/aws/s3/object_version_collection.rb:79:in `each'
```

**Comment by awood45** [comment]
Our default credential provider will only wait for 1 second for the EC2 metadata service to return credentials before failing. If you're experiencing this often, you should explicitly construct the EC2 credential provider `AWS::Core::CredentialProviders::EC2Provider` with retries and a longer timeout. That should resolve this issue.
